### ISSUE TITLE
Wake not working via REST

### ISSUE THREAD

**Issue by arraylabs** [thanksmister/wallpanel-android#10]
Hello, not sure what changed but wake no longer works via the REST API. It was previously (in the last week or two) then stopped a few days ago. Applied the latest update and it still remains broken. If I use postman to send the POST i get a result true when sending wake but the screen remains off. I can also GET the states and screenOn shows false as well. Other commands (like speak for example) seem to work fine.

**Comment by thanksmister** [comment]
Thanks for the report, I will investigate.

**Comment by thanksmister** [comment]
Do you have an example of the post request you are making in Postman?

**Comment by arraylabs** [comment]
Yes, I'm using the below:

POST /api/command HTTP/1.1
Host: 172.30.1.106:2971
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 2d467e30-e4e8-fed9-a17e-f90597a9640b

{
"wake": true
}

that gives:

{
    "result": true
}

But the device doesn't wake. Like I said it did previously then noticed it
stopped waking based on motion sensors (HA sending wake command on motion
detected) then tried via postman (which is how I original tested things for
HA) and it just doesn't do anything.

Thanks!

**Comment by arraylabs** [comment]
@thanksmister I've looked through the device settings but will go through the settings again, hopefully it's just something with my tablet. Galaxy Tab A, 8".

**Comment by thanksmister** [comment]
I could be Android 8, if that's what you are running.   Have you recently updated the OS on that device? I have the same results from Postman sending the same information, but my devices wake.  I have the clock daydream active and no lock on the device.  I will try with an Android 8.0.1 device and see if I can replicate it.

**Comment by thanksmister** [comment]
When I mentioned motion sensors, I meant waking the device when the device detected motion from the camera.  This is an option in the device settings.  When the camera of the device spots motion, it will also wake the screen as an option.  I wanted to know if this was working.

**Comment by arraylabs** [comment]
Sorry, its an older Galaxy Tab A, so probably Android 5 or similar (at the office now so can't check). I know I have the latest version that the tablet supports loaded. I will try the camera motion detection this evening as well.

**Comment by thanksmister** [comment]
Ok, well I have an older Android 5 tablet as well (Nexus 7) and I will double check that that is still working with the latest release.

**Comment by thanksmister** [comment]
Ok, so far I tested this feature on Android 5.0.1 and 6.0.1 and both devices work as expected when calling wake using the REST API.  I was using version v0.8.3 Build 2 from the Google Play store.

**Comment by arraylabs** [comment]
I double checked all the settings and didn't see anything that would cause the issue. I turned on the camera motion detection and it still didn't wake. I eventually did a factory reset of the tablet and re-installed wallpanel and it works without issue again. Appreciate your time and willingness to check things from your end.

**Comment by thanksmister** [comment]
Wow that’s great, I was worried we wouldn’t solve the issue.  Thanks for your efforts as well.  I know it can be frustrating when thing stop working without a clear cause.  It could be your camera hangs and requires a restart.
