### ISSUE TITLE
Reload Page after Wake-up

### ISSUE THREAD

**Issue by reyphilipp** [thanksmister/wallpanel-android#100]
Can you add a option with this feature:
After Wake-up with Motion-detected, can you reload the website?

**Comment by thanksmister** [comment]
You can already receive an MQTT message that motion was detected and then send back a command to refresh the web page.  There is no need to add another option to do this.

**Comment by dragonflyuk** [comment]
I do that already, the slight hiccup occurs if you're in a dark room or out of camera shot, and tap the screen to wake it up. No motion detected, no refresh. Maybe a mqtt message for wake up, would solve that.
