### ISSUE TITLE
Merge Wallpanel, Alarmpanel and Voicepanel into a single app

### ISSUE THREAD

**Issue by lettore** [thanksmister/wallpanel-android#101]
I'm using your work in my home automation system.
I have to say that it's really amazing how well all it works.
In my setup, I need the alarm panel on all devices, but alarm panel is missing some wallpanel functionalities like dimming while in screensaver etc, and voicepanel is another great addon.
I will suggest you merge the three app into one, also for easier development.
You can make this a paid option, it will be a best seller :).

**Comment by thanksmister** [comment]
Sounds good, the features are a bit staggered as some apps have newer ideas implemented and it takes time to retrofit the two other apps.   One consolidated application might be the best fit, but then the separate apps would definitely suffer.    But one app to rule them all would be a good option.   I will see about adding the screensaver brightness and brightness settings to the alarm panel, right now it's only used for day/night mode changes.
