### ISSUE TITLE
MQTT suddenly stops

### ISSUE THREAD

**Issue by Drachenkaetzchen** [thanksmister/wallpanel-android#102]
**Describe the bug**
MQTT publishing stops with no apparent reason

**To Reproduce**
Not sure if this can be reproduced on other devices. On my Nexus 7 I have set the sensor publishing to 1 second, and because movement detection works the app is still running.

My assumption is that something goes wrong when publishing to the MQTT server (maybe a short network outage or publishing takes longer than 1 second). Going to the settings and returning to the dashboard without any changes makes MQTT publishing work again.

I don't know if there are any logs. If there are logs, note that USB connectivity on my Nexus 7 is broken, so I can't access ADB logs :(

**Smartphone (please complete the following information):**
 - Device: Nexus 7
 - OS: Android 6
 - Version: v0.8.7-beta4

**Comment by allofmex** [comment]
In my experience, many devices loose there wifi connection in standby. Even if set to "always connected".
I solved it by a tasker rule:
If wifi disconnected -> wait 5sec -> connect to wifi xy 
That way it's working for me (nexus and various sony devices)

**Comment by thanksmister** [comment]
@allofmex thanks for responding to this, you are a big help as always!

**Comment by thanksmister** [comment]
@Drachenkaetzchen I checked firebase for any crashes specifically related to MQTT or your device and operating system.  I did not find any crashes or issues, so I think this may be device specific.  You may want to check your logs MQTT logs inside HA, this will probably tell you the client disconnected normally.    Most likely cause is as @allofmex has suggested, the WiFi goes to sleep or disconnects.  You can try the screensaver which does not let the screen sleep if you haven't done so already.

**Comment by Drachenkaetzchen** [comment]
> @Drachenkaetzchen I did not find any crashes or issues, so I think this may be device specific. 

Yes, WallPanel still runs because motion detection and turning on the screen works fine.

> Most likely cause is as @allofmex has suggested, the WiFi goes to sleep or disconnects. 

That might be the case, however, MQTT publishing doesn't resume if the WiFi is back. I'll try to increase the MQTT publishing interval and see if this still happens - I have a hunch that it might be the cause.

**Comment by Drachenkaetzchen** [comment]
I increased the interval to 5 seconds, but the disconnect happens again. Here's the Mosquitto Log:

```
1563549899: New connection from 172.22.117.163 on port 1883.
1563549899: Client mywallpanel already connected, closing old connection.
1563549899: Socket error on client mywallpanel, disconnecting.
1563549899: New client connected from 172.22.117.163 as mywallpanel (c0, k60).
```

However, after the new connection no new data is published.

**Comment by thanksmister** [comment]
Do you have a username and password set for your MQTT broker?

**Comment by Drachenkaetzchen** [comment]
> Do you have a username and password set for your MQTT broker?

No, as it's running in my home network. Does it make a difference?

**Comment by thanksmister** [comment]
Well just make sure you are entering the credential in the MQTT setup, I use a username and password and the client reconnecting is normal from the client.   The socket error seems to be the issue, perhaps you can restart your MQTT instance in HA.

**Comment by Drachenkaetzchen** [comment]
> Well just make sure you are entering the credential in the MQTT setup, I use a username and password and the client reconnecting is normal from the client. The socket error seems to be the issue, perhaps you can restart your MQTT instance in HA.

I'm confused - as mentioned above, the MQTT connection fails after some time, and there's no authentication. I have checked the mosquitto log for other socket errors, but given the 15+ Tasmota devices in my network and some with very flaky WiFi connections I see only a few compared to the socket errors of WallPanel.

I think a "retry MQTT after `n` seconds" would be a good option, I'll try to add this as a PR if wanted.

**Comment by thanksmister** [comment]
I don't think a retry after n seconds is going to work, the MQTT library already does reconnect, that is part of its behavior for the Paho Android library.    I know because the client will reconnect to the server if the server is restarted, it is not necessary to have a retry, which would require you to initialize the MQTT client again when it's already initialized.

**Comment by Drachenkaetzchen** [comment]
I have restarted the server and the socket error occurs again after reconnecting:

```

1563563349: New client connected from 127.0.0.1 as 62c2ba3d-0f8c-4f5a-ae07-2284d5976cb6 (c1, k60).
1563563377: mosquitto version 1.5.7 terminating
1563563377: mosquitto version 1.5.7 starting
1563563377: Config loaded from /etc/mosquitto/mosquitto.conf.
1563563377: Opening ipv4 listen socket on port 1883.
1563563377: Opening ipv6 listen socket on port 1883.
1563563377: New connection from 172.22.117.190 on port 1883.
1563563377: New client connected from 172.22.117.190 as DVES_66019B (c1, k10, u'DVES_USER').
1563563377: New connection from 172.22.117.165 on port 1883.
1563563377: New client connected from 172.22.117.165 as DVES_890AAE (c1, k10, u'DVES_USER').
1563563377: New connection from 172.22.117.176 on port 1883.
1563563377: New client connected from 172.22.117.176 as DVES_092CDF (c1, k10, u'DVES_USER').
1563563377: New connection from 172.22.117.175 on port 1883.
1563563377: New client connected from 172.22.117.175 as DVES_6601A1 (c1, k10, u'DVES_USER').
1563563378: New connection from 172.22.117.177 on port 1883.
1563563378: New client connected from 172.22.117.177 as DVES_CF845A (c1, k30, u'DVES_USER').
1563563378: New connection from 172.22.117.192 on port 1883.
1563563378: New client connected from 172.22.117.192 as DVES_86D2B0 (c1, k10, u'DVES_USER').
1563563378: New connection from 172.22.117.195 on port 1883.
1563563378: New client connected from 172.22.117.195 as DVES_65FB75 (c1, k10, u'DVES_USER').
1563563378: New connection from 172.22.117.186 on port 1883.
1563563378: New client connected from 172.22.117.186 as DVES_660019 (c1, k10, u'DVES_USER').
1563563378: New connection from 172.22.117.191 on port 1883.
1563563378: New client connected from 172.22.117.191 as DVES_86B7CD (c1, k10, u'DVES_USER').
1563563378: New connection from 172.22.117.170 on port 1883.
1563563378: New client connected from 172.22.117.170 as DVES_660723 (c1, k10, u'DVES_USER').
1563563378: New connection from 172.22.117.184 on port 1883.
1563563378: New client connected from 172.22.117.184 as DVES_F97B42 (c1, k10, u'DVES_USER').
1563563378: New connection from 172.22.117.185 on port 1883.
1563563378: New client connected from 172.22.117.185 as DVES_CAF548 (c1, k10, u'DVES_USER').
1563563378: New connection from 172.22.117.183 on port 1883.
1563563378: New client connected from 172.22.117.183 as DVES_B2262F (c1, k30, u'DVES_USER').
1563563378: New connection from 127.0.0.1 on port 1883.
1563563378: New connection from 172.22.117.163 on port 1883.
1563563378: Socket error on client mywallpanel, disconnecting.
1563563378: New client connected from 172.22.117.163 as mywallpanel (c0, k60).
1563563379: Socket error on client <unknown>, disconnecting.
1563563379: New connection from 127.0.0.1 on port 1883.
1563563379: New client connected from 127.0.0.1 as 559b7cbd-2463-4ed8-859a-51d645ea77a8 (c1, k60).
```

I then turned on debug logging on the mosquitto server, which has the following lines concerning WallPanel:

```
1563564510: Socket error on client mywallpanel, disconnecting.
1563564510: New client connected from 172.22.117.163 as mywallpanel (c0, k60).
1563564510: Sending CONNACK to mywallpanel (1, 0)
```

As this is reproducible here, I doubt it's a flaky network connection. If I stop the mosquitto server, WallPanel enters the same "won't publish MQTT messages" state including the socket error on reconnect when I start the mosquitto server again.

I only can make MQTT messages work if I restart the app or enter the settings menu and then tapping "Dashboard".

**Comment by Drachenkaetzchen** [comment]
Additional info: Here's what the log looks like after I restart the WallPanel app (same with entering and leaving settings):

```
563564725: Socket error on client mywallpanel, disconnecting.
1563564725: New client connected from 172.22.117.163 as mywallpanel (c0, k60).
1563564725: Sending CONNACK to mywallpanel (1, 0)
1563564726:     wallpanel/mywallpanel/sensor/light (QoS 0)
1563564726: 42016c0c-b8e1-4f1e-ad83-9f5afcec82fa 0 wallpanel/mywallpanel/sensor/light
1563564776: Received DISCONNECT from mywallpanel
1563564776: Client mywallpanel disconnected.
1563564784: Socket error on client mywallpanel, disconnecting.
1563564784: New client connected from 172.22.117.163 as mywallpanel (c0, k60).
1563564784: Sending CONNACK to mywallpanel (1, 0)
1563564784: Received SUBSCRIBE from mywallpanel
1563564784:     wallpanel/mywallpanel/command (QoS 0)
```

Note that the previous connection which has the "socket error" message is being disconnected, at least it looks like it.

**Comment by thanksmister** [comment]
Looks like the code to reconnect is not available the version of the SDK you are using:

`override fun onMQTTDisconnect() {
        Timber.e("onMQTTDisconnect")
        if (hasNetwork()) {
            if (!mqttAlertMessageShown && !mqttConnected && Build.VERSION.SDK_INT > Build.VERSION_CODES.LOLLIPOP) {
                mqttAlertMessageShown = true
                sendAlertMessage(getString(R.string.error_mqtt_connection))
                reconnectHandler.postDelayed(restartMqttRunnable, 180000)
            }
        }
    }

    override fun onMQTTException(message: String) {
        Timber.e("onMQTTException: $message")
        if (hasNetwork()) {
            if (!mqttAlertMessageShown && !mqttConnected && Build.VERSION.SDK_INT > Build.VERSION_CODES.LOLLIPOP) {
                mqttAlertMessageShown = true
                sendAlertMessage(message)
                reconnectHandler.postDelayed(restartMqttRunnable, 180000)
            }
        }
    }`

What @allofmex is still valid, your device is disconnecting it's WiFi connection.  Your WiFi should stay alive, but it doesn't appear to be happening on your device and SDK version.   

If we move the reconnect logic out of the check for the SDK version to have the reconnection happen, it doesn't address the issue with the socket connection error.  The app should not have to constantly restart the MQTT client service because of a continuous network error.

The reason that logic was in place is because of a similar issue on another older device, it caused the constant error message to occur.   The Paho library should also retry the connection, but the socket connection seems to be killing it entirely.  

This could be some issue with Paho and your device or SDK version and its causing the socket error and not the Wifi connection.   I could not say because I would need the exact device to test it. 

I do not think I would remove the check to restart the MQTT client for this particular case.   You may want to try the WallPanel legacy version to see if it has better compatibility with your device.

**Comment by Limych** [comment]
My WallPanel also often loses connection with the MQTT server. The exact reason is not clear. Wallpanel v0.8.7 build 4

**Comment by roflmao** [comment]
This happens on my Wallpanel as well (v0.8.7-beta.4) on a Lenovo Tab4 10. The wallpanel is active but MQTT is not sending. Is there any way i can provide logs?

**Comment by allofmex** [comment]
@Limych @roflmao 
You may run permanent pings from another device in your lan/wifi network to your wallpanel device. If the pings fail after some time, it shows that the network connection got lost and that it is not wallpanel related! (see the second post in this issue report for a possible solution)

**Comment by spahlimi** [comment]
Is your MQTT stopping completely? In my case only the transmission of sensor values to the broker stops. When i send a wake command by mqtt the device wakes up as expected.

**Comment by Ahrenfelde** [comment]
Hi,
I also got trouble with my wallpanel. It´s run on a Asus Tab.
Wallpanel app stops publishing Sensor data over MQTT. I happens regualary.
Wednesday: 4:31AM MQTT stops
Yesterday : 4:21AM
today: 4:11AM

This is very strange.
I will "log" the Online Status with NodeRed and a trigger note. When 2 Minutes is no Input then i got a Telegram message.

**Comment by seamus65** [comment]
Hello,
I have the same issue on an Amazon Fire HD 8.
If the server restarts or is out of communication for any reason the wallpanel sensor information is no longer sent, which causes a problem as I use that to control the charger for the tablet.
Is there any way to have a legacy version for older devices and provide a version with updated mqtt for modern devices?

**Comment by aukedejong** [comment]
Same problem here.
The battery charge state is not updated after a while in Home Assistant.
The other way. When someone presses the doorbell the tablet wakes en plays a sound. Both triggered with MQTT from Home Assistant.

Running on a Samsung Galaxy Tab 8.0 with Android 7.0

**Comment by seamus65** [comment]
I made an automation in home assistant that sends an mqtt message to wallpanel to relaunch when HA restarts or when the internet has been off and comes back on (I have a ping sensor for the internet connection), this appears to have helped so far...

`
- alias: Reset Wallpanel on start up
  initial_state: 'on'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: binary_sensor.internet_available2
    to: 'on'
  action:
  - service: mqtt.publish
    data_template:
      topic: wallpanel/mywallpanel/command
      payload: '{"relaunch": true}'
`

**Comment by aukedejong** [comment]
Nice work-around. I was thinking about sending a relaunch message when wallpanel stops sending sensor updates.

I did some research on the problem.
In the mosquitto logs I see this:

```
1573243522: New client connected from 192.168.1.247 as huiskamer (c0, k60).
1573243612: Client huiskamer has exceeded timeout, disconnecting.
1573243612: Socket error on client huiskamer, disconnecting.
```

The k60 means that the client (wallpanel) specifies a Keepalive Interval of 60 seconds.
For some reason wallpanel stops or not sends at all, PINGREQ messages. Maybe it's a network thing, but Mosquitto broker doens't receive the messages.

I had the sensors update every 60 seconds. Changed it to 50 seconds now. See what happens.

**Comment by pkatzu** [comment]
> I made an automation in home assistant that sends an mqtt message to wallpanel to relaunch when HA restarts or when the internet has been off and comes back on

I understand why the first bit is important, but why Internet off? Or it's (W)LAN?

> I had the sensors update every 60 seconds. Changed it to 50 seconds now. See what happens.

Any news? If MQTT enabled, the app publishes its state and sensors' state, and they both seem to stop sometimes.

I recently notice that randomly the app disconnects, BUT connects back if its motion detection triggers. Don't know what to do with it though..

**Comment by seamus65** [comment]
I found that wallpanel would stop talking over mqtt if there was any communication problems, so internet outage seemed like a good thing to do.

**Comment by thanksmister** [comment]
The MQTT Paho library has a background alarm which pings the server every 60 seconds to stay alive.  There is also some logic to restart the MQTT service if there is an internet outage, but this is not always true on older devices.  Some devices simply kill their internet connection when idle.  You may find a setting to prevent this depending on the device or there are some apps that keep your internet from shutting down.  The MQTT ping should be doing this as well but it doesn't seem to be working on all devices.

**Comment by thanksmister** [comment]
If your MQTT broker goes offline, the application does not throw an error or disconnect. The background alarm that keeps pinging the service continues to function and the alarm establishes connection to the broker.   What I think we have to control is losing actual WiFi connectivity and ensure that the MQTT client in the application reconnects.  This is not the same as ensuring the device WiFi continues to keep its connection, that is up to the device and its default settings or optional settings.    Most of the issues appear to be because the device is disconnecting the WiFi in the background and the MQTT client (the app) is not able to reconnect.

**Comment by thanksmister** [comment]
I put out an update that will disconnect and reconnect the MQTT client on any interruption of the WiFi connection.   From my initial tests is may not be necessary to do this because the MQTT Paho library will reconnect on its own, but I chose to explicitly handle the reconnect and disconnect so that I am certain MQTT is always established.

**Comment by aukedejong** [comment]
Updated Wallpanel and it seams to be fixed. It’s still updating battery status after one night. It never did that before.

Thanks!!

**Comment by aukedejong** [comment]
And sensor updates still working.
I understand the fix is work-around. Do you know why the Paho library doesn't reconnect on its own? Is it a bug in that library or is it something else?  Bug in older Android?

If the problem is in older Android, it could be a reason for me to install an AndroidMod rom in my Galaxy Tab S2 8".

**Comment by R5fan** [comment]
This problem hasnt been solved entirely for me I think. I use MQTT to wake the screen. At night,  my routers reboot. HA seems to be getting MQTT sensor updates after that, but wallpanel doesnt seem to listen to mqtt anymore. In the morning, I always need to wake the tablet manually, and force a reconnect before it starts working again?

**Comment by seamus65** [comment]
> This problem hasnt been solved entirely for me I think. I use MQTT to wake the screen. At night, my routers reboot. HA seems to be getting MQTT sensor updates after that, but wallpanel doesnt seem to listen to mqtt anymore. In the morning, I always need to wake the tablet manually, and force a reconnect before it starts working again?

R5fan, you could try an automation similar to mine to force relaunch after the router reboots:

alias: Reset Wallpanel on start up
initial_state: 'on'
trigger:
  platform: homeassistant
  event: start
  platform: state
  entity_id: binary_sensor.internet_available2
  to: 'on'
  from: 'off'
  action:
  service: mqtt.publish
  data_template:
  topic: wallpanel/mywallpanel/command
  payload: '{"relaunch": true}'

**Comment by thanksmister** [comment]
wake the tablet manually,?  I isn’t the tablet always running Wallpanel as a foreground application?

**Comment by thanksmister** [comment]
The application is connected to your MQTT broker if you are still getting messages.  It is unclear to me if the application is still running in the foreground, from what you describe its sounds like the background service is running, but WallPanel is no longer running in the foreground, which means it cannot receive MQTT updates.  The service is probably continuing to send MQTT messages.   That is a summary of the issue.  However, for this ticket, the original issue of MQTT reconnecting on loss of the broker has already been addressed and resolved.   Your issue is not the same and should be on its own ticket.
