### ISSUE TITLE
F-Droid version

### ISSUE THREAD

**Issue by anliec** [thanksmister/wallpanel-android#104]
Is there any reason for not having a version of this app available on F-Droid ?

I usually look for my app on F-Droid only and the only Home assistant app available there is the pretty old [homeassistant](https://f-droid.org/en/packages/io.homeassistant.android/) app.
It took me some time to figure out there were another open source app available.

I didn't found any mention of F-Droid on this repo, so I took the liberty to open this request, sorry if it's a duplicate.

**Comment by thanksmister** [comment]
I am not interested in having a version for F-Droid.  The application is already available as a downloadable APK file which can be sideloaded on devices that do not support Google Play store.
