### ISSUE TITLE
Cookies not saved in iframe card.

### ISSUE THREAD

**Issue by dragonflyuk** [thanksmister/wallpanel-android#107]
**Describe the bug**
When using the iframe Lovelace card cookies are not saved.

**To Reproduce**

Setup an iframe card that displays a website that requires cookies, in my case I use the BBC sounds website. You will be asked about using cookies everyone you use the site, using a browser for the GUI you are only asked once.

**Expected behavior**

Cookies should be saved correctly

**Smartphone (please complete the following information):**
 - Device: Amazon Fire HD10

**Comment by thanksmister** [comment]
I don't think the WebView component for Android supports iFrames, there is nothing I can do to make this work as the rendering of web pages is entirely up to the version of the Android OS you are using and the device.

**Comment by youknowjack0** [comment]
@thanksmister I believe this behavior can be controlled here: 
https://developer.android.com/reference/android/webkit/CookieManager#acceptThirdPartyCookies(android.webkit.WebView)

(I have a similar use case: loading an iframe with an authorized camera feed; the iframe loads, but the authorization doesn't stick)

**Comment by jessemcdowell** [comment]
Any chance of reopening this? I have the same problem.

With Hubitat dashboards iFrames are the only way (I've found) to inject external sites. In my case, I'm trying to show a Google Calendar. Because the iFrame can't access the cookies, it can't show my calendars unless I open them up to the public internet.
