### ISSUE TITLE
enroll face mqtt

### ISSUE THREAD

**Issue by johan149** [thanksmister/wallpanel-android#108]
it would be great to enroll faces and then after a face detection publish as face1, face2 etc

**Comment by allofmex** [comment]
I would love to see this too. But I guess that would require lot's of work to implement.

**Comment by thanksmister** [comment]
The face detection works on the device and detects faces but not individual faces.  That kind of processing would require cloud processing which means uploading your face to Google cloud for their machine learning library for example.   Not sure if other solutions that would be less complex or so not require training.

**Comment by Limych** [comment]
I am a supporter of minimally giving any data "out" from my smart home. If the function of recognition of specific faces be implemented, I believe that it will be correct if it is optional and disabled by default.

**Comment by thanksmister** [comment]
Yeah, this isn't going to happen because you would also need your own Firebase account to use this feature, it is not a feature you would implement or want to implement for all users.
