### ISSUE TITLE
App not refreshing light state

### ISSUE THREAD

**Issue by swortsoul** [thanksmister/wallpanel-android#109]
I have a Wemo dimmer light that works in home assistant and the regular HAdashboard. The switch on/off updates when you touch it. When you touch the + or = to change the brightness, it works (the light gets brighter or dimmer), but the WallPanel app still shows 0%. The normal web page on the tablet shows it increase/decrease, as it does in home assistant. When I hit "reload", the correct % is then displayed.

**To Reproduce**
1. Start the dashboard
2. Select + or = on the dimmer light.
3. The light actually gets brighter/dimmer, but the WallPanel app still shows 0% (or whatever % it started at.

**Expected behavior**
The WallPanel app should display the correct %

**Screenshots**
I don't think this is necessary. Please let me know if you think it is.

**Smartphone (please complete the following information):**
 - Device: Older Samsung Galaxy Tab 2 7.0 SCH-I705
 - OS: Android 4.1.2
 - Browser Has both Chrome and Firefox installed on it.
 - Version Both up to date

**Additional context**
N/A

**Comment by swortsoul** [comment]
After some more testing, it looks like the screen is not updating in real time. The same thing happens in the default browser. It all works fine using Chrome. I'm not sure how this affects the WallPanel app, but figured the info could be useful.

**Comment by thanksmister** [comment]
Not much I can do about this, the WebView component is used by Android applications and I have not control over the way it handles web pages.   This sounds like a compatibility issue, I think you should be using the older version of WallPanel (https://github.com/thanksmister/wallpanel-android-legacy) which has better support for older versions of Android OS.
