### ISSUE TITLE
Enable/Disable wakeup by motion

### ISSUE THREAD

**Issue by Luc3as** [thanksmister/wallpanel-android#11]
Hello, 
First of all, thank you for amazing app, 
I would have one small feature request. It would be nice if I could enable or disable waking up of screen by motion sensor by MQTT or REST command. Background behind this is I would like to setup automation, and have the screen active whole time as somebody is home, but to have motion wakeup only at night. I could send wakeup command periodically to keep screen on but it could be more elegant if this could be set by commands. 
thanks

**Comment by thanksmister** [comment]
Since this request hasn't been worked or hasn't been voted up, I am closing the request for now.  Thanks!
