### ISSUE TITLE
mjpeg stream is upside down

### ISSUE THREAD

**Issue by flowolf** [thanksmister/wallpanel-android#115]
**Describe the bug**
The camera stream is upside down.

**To Reproduce**
1. set camera to enabled
2. rotate camera to 'none'
3. enable camera streaming
4. camera test looks good, right side up
5. go to dashboard
6. open stream URL, the stream is upside down

**Expected behavior**
the camera test image is rotated the same way as in the stream.
but the preview does not seem to be influenced by the 'rotate camera' setting.
the preview should match the stream orientation.

**Wallpanel running on:**
 - Device: Lenovo Tablet TB-X505L
 - OS: Android 9
 - Browser: None
 - Version v0.8.7 Build 4

**Smartphone (please complete the following information):**
Streamed to:
- Device: Laptop, running Ubuntu
- Browser: Firefox 68.0.2

**Additional context**

**Suggestion:**
It would be great to have a 'rotate 180 degrees' option. This would allow to fix this issue, as well as mount tablets upside down.

**Comment by thanksmister** [comment]
There is a rotate setting for this.

**Comment by flowolf** [comment]
Thanks!
I tried the 'flip horizontal' setting, which now works. weird.

I had the device sent in for repair. So that might be it... 

Thanks for a great App! :smile_cat:

**Comment by thanksmister** [comment]
Great, thanks for getting back to me.  I am going to close this issue now.
