### ISSUE TITLE
Screen does not lock if WallPanel is open

### ISSUE THREAD

**Issue by zappasmart** [thanksmister/wallpanel-android#116]
**Describe the bug**
Screen unlock pattern is configured on the device. When WallPanel is open and device goes to sleep mode, pressing the power button does not show the screen unlock pattern but WallPanel is brought up again.
For security reasons, I'd like to have the system screen unlock pattern displayed to prevent unauthorized access.

**To Reproduce**
1. Configure screen unlock patter on the device security settings
2. Open WallPanel and wait the screen turns off automatically
3. Wait more...
4. Press the device power button
5. Screen turns on and WallPanel is displayed

**Expected behavior**
The screen unlock pattern should be displayed

**Device:**
 - Device: HUAWEI Mediapad M5 Lite
 - OS: Android 8

**Device:**
 - Device: HUAWEI P20 Lite
 - OS: Android 9

**Additional context**
It looks like WallPanel prevents the device to lock. WallPanel is not configured to keep the screen on.

**Comment by thanksmister** [comment]
WallPanel is an application that is meant to run in the foreground, if your intention is to lock your device  then turn off the setting prevent sleep.  This is the setting which is keeping the screen on.
