### ISSUE TITLE
secure password of mqtt

### ISSUE THREAD

**Issue by fonteshugo** [thanksmister/wallpanel-android#117]
I beleave the app is realy good, but I need to secure the mqtt password. Otherwise it's easy to get access to the password and damage the mqtt server. Is it possible?

**Comment by thanksmister** [comment]
I guess you mean in the settings. No you have no feature to prevent someone from entering the settings.

**Comment by fonteshugo** [comment]
Yes i mean in the settings. The Higher issue os the fact that the password os visible
