### ISSUE TITLE
Unable to send PRs

### ISSUE THREAD

**Issue by tringler** [thanksmister/wallpanel-android#12]
Hello @thanksmister,

could you explain how to send PRs to that repo? It is not possible for me, because I forked the original repo and can only send PRs to that repo. It don't let me fork your repo and forward me to the original which I already forked.

Any ideas how to solve it?

Thanks, Thomas

**Comment by thanksmister** [comment]
I am pretty sure you have to fork my repository and to a pull request against it.   You could check out my repository and then copy the changes over to that fork, but you would have to do it manually.

**Comment by thanksmister** [comment]
Couldn't you also check out this project, create a new branch (feature/bug) then submit that branch as a new PR?   The section here, after forking explains branching the project: https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by thanksmister** [comment]
You should be able to fork this repository now.
