### ISSUE TITLE
Documentation update: How to set up project / sideload

### ISSUE THREAD

**Issue by AaronHolbrook** [thanksmister/wallpanel-android#120]
I would love a documentation/walkthrough on how to go about setting up this specific project with Android Studio in order to get it running on my local machine's emulator and then sideload to a physical tablet.

**Comment by thanksmister** [comment]
If you are running Android Studio with the project, it compiles and runs on your connected device, it does not need to be slide loaded.  If you want to sideload the APK, you can download the latest from the project releases tab and look up how to side load the apps using Google.   Setting up projects in Android Studio often runs into issues, I do not think me providing an additional video on the subject will help if you are not already familiar with using Android Studio and developing Android projects.

**Comment by AaronHolbrook** [comment]
I understand not wishing to explain how to use Android Studio, etc; however the intricacies surrounding this specific project could be very useful to know. 

i.e. the first issue I stumbled into was a missing `google-services.json` file located in the `WallPanelApp` directory. This file is necessary due to using the `com.google.gms.google-services` plugin. 

A helpful bit of documentation would be to describe that you would need to go to Google / Firebase to set up this file, add it to the appropriate location / etc.

I'm happy to help contribute documentation as I go through the process, but I need to know how to get past the items that are troublesome.

**Comment by thanksmister** [comment]
I updated the documentation with some information for building locally.  Basically you can remove the firebase dependencies as these are just used for crash reports and analytics.

**Comment by AaronHolbrook** [comment]
Oh, that's great to know, thank you!

**Comment by allofmex** [comment]
> missing google-services.json file

Had the same problem. To build the app, it seems to be sufficient to uncomment line
`apply plugin: 'com.google.gms.google-services'` in apps build.gradle
