### ISSUE TITLE
MQTT doesn't reconnect after connection lost

### ISSUE THREAD

**Issue by dogghy14** [thanksmister/wallpanel-android#122]
MQTT client doesn't reconnect after connection lost caused by a broker restart.

**Comment by thanksmister** [comment]
It would help if you provided the device and the version of Android.

**Comment by dogghy14** [comment]
I’m using a Google Nexus 7 2012 3g (nakasig) with the last official rom (Android version 5.1.1).

Many thanks!

**Comment by thanksmister** [comment]
I am afraid that was done intentionally for devices running Android versions below Lollipop.  Those devices have connection issues when the connection was dropped.  So the device does not try to disconnect on a loss connection for your Android version.  There is nothing to be done unless you want to compile the application yourself and remove that part of the code.

**Comment by dogghy14** [comment]
I updated my Nexus 7 to Android AOSP 7.1.2 and now the MQTT client reconnects after a broker reboot.

Thank you very much for your support
