### ISSUE TITLE
REST API: Error getting state, check Java Console for details

### ISSUE THREAD

**Issue by borland502** [thanksmister/wallpanel-android#126]
When using the REST API, invariably, after some hours the following message will display when the program is launched:  

> Error getting state, check Java Console for details

Once the message appears, the application will no longer work except for the config panel functionality until the REST service API is disabled or the tablet is rebooted.  Right now, I am using the REST service to manually refresh the display every minute from HomeAssistant.  Camera Streaming is also enabled and hooked to MotionEye at 15fps, image flipped 180.

Hardware:
Kindle 7" 7th Generation, latest firmware (can get specifics if needed) with sideloaded Google Apps

Pity, because your app was already awesome without REST, but heaven sent with it.

**Comment by thanksmister** [comment]
That is an Android application error due to a crash on your device.  I suspect that the application is not going to work on your device.   You can try to disable the camera feature or reduce the framerate.  There is also an version of Wall Panel for older devices.  https://github.com/thanksmister/wallpanel-android-legacy

**Comment by borland502** [comment]
Pity.  Thanks for the response.  Thus far the app in its modern incarnation has been rock solid except for the REST API so I guess I can just ditch the camera or use the mqtt.  The camera was more of a curiosity/power save thing for me, rather than the objective.

**Comment by borland502** [comment]
Hmm, one addendum: I turned off the REST API toggle and left the camera streaming active and it's been going for more than 24 hours.  I think whatever causes the crash is directly related to the functionality there rather than the camera.
