### ISSUE TITLE
Always crashing on Fire HD 10 after update

### ISSUE THREAD

**Issue by SteffenM-DE** [thanksmister/wallpanel-android#129]
After the last update on Amazon Fire Tablet HD 10 Wall Panel crashs on start - only short showing the app and than I'm back on home screen.

Regards, Steffen

**Comment by thanksmister** [comment]
Sounds like it is related to https://github.com/thanksmister/wallpanel-android/issues/128.  Can you provide more information about your OS version.   I have an Fire Tablet 7 I could test.

**Comment by SteffenM-DE** [comment]
Of course and thanks for your support:

Fire HD 10 (Gen. 7)
Fire OS 5.6.4.0

I'm no Android specialist, I'm only sideload the playstore to install Wall Panel. So I could use the Fire Tablet for my Home Assistant.

**Comment by thanksmister** [comment]
There are older versions in the release section of this project, you can side-load the previous version until we can pinpoint this issue.

**Comment by SteffenM-DE** [comment]
Can you explain how to do that?

**Comment by thanksmister** [comment]
Download on your tablet the .apk file from this link https://github.com/thanksmister/wallpanel-android/releases/tag/v0.8.7.4.   Open the APK on your tablet and it should as you to install the app.   There is a lot of information on the web, but this might help http://www.supportrix.com/kb/how-to-sideload-apps-from-another-android-device-onto-your-kindle-fire-tablet/.

**Comment by nabulke** [comment]
I have the same issue on my Kindle Fire HD (7Gen). After clean reinstallation I could reach the setup screen until I activated the camera sensor. Now it keeps closing/crashing at application start.

**Comment by thanksmister** [comment]
I have seen a crash for the Camera, but only with Android 5.1 and Huawei devices.   I am going to run some tests on my Fire tablet.  I suspect that when Google forced all applications to be 64 bit compliant, this caused issues on some devices and older versions of Android.

**Comment by nabulke** [comment]
Thank you Michael for your support on that issue! If I can provide any further information, please let me know.

**Comment by thanksmister** [comment]
I am able to reproduce the crash on Android 5.1.1  API 22, which is what my Fire tablet 7 is currently running.  This is consistent with the other crashes I have seen for Android 5.1.1 after migrating the application to 64 bit compatibility.

**Comment by thanksmister** [comment]
I have isolated the issue to RenderScript, which we use to do motion detection with the camera.   I will have to remove the ability for devices running Android 5.1.1 or below from using the motion detection feature.

**Comment by thanksmister** [comment]
I pushed out a fix in v0.8.8-beta.7 which will be available in the Google Play store soon.   I reverted the RenderScript library to an older version, the camera features should still work.

**Comment by thanksmister** [comment]
@nabulke have any success?

**Comment by SteffenM-DE** [comment]
New Version at the App Store is working again on my Fire HD 10.
Thank you.

**Comment by thanksmister** [comment]
Closing, thanks!

**Comment by nabulke** [comment]
> 
> 
> @nabulke have any success?

Yes, with the latest update from the App store it works withouts problems.
Thank you for you fast help!
