### ISSUE TITLE
cant open dashboard

### ISSUE THREAD

**Issue by newone230** [thanksmister/wallpanel-android#130]
on android 9.0
after inserting my local home assistant addres to dashboard url i get error err_cleartext_not_permitted

address is http://10.0.0.135:8123

- few days ago, it worked well
- from computer browser its ok

any help?

**Comment by thanksmister** [comment]
You know which version of the application you are running?

**Comment by newone230** [comment]
0.8.8. build 7

**Comment by thanksmister** [comment]
Ok, look for an update coming on Google Play, v0.8.8 build 8 or you can side load the latest release with a fix for clear type: https://github.com/thanksmister/wallpanel-android/releases/tag/v0.8.8.8

**Comment by newone230** [comment]
0.8.8.  build 8 is OK 

thank you very much

**Comment by thanksmister** [comment]
great, closing this issue.
