### ISSUE TITLE
Sleep/Wakeup logic.

### ISSUE THREAD

**Issue by vegetate7** [thanksmister/wallpanel-android#138]
I'm using Samsung Galaxy TAB2 with Android 6.0.1. I amnot sure if my issue is version or device related.

The "Prevent Screen Sleep" option work as intended: the screen is never turning off.
But If I disable this option, screen turns of as the System's "go to Sleep mode" timer set up.
Regardless of Motion and Face detect envents, and MQTT "wake" command. Any of those events can wake the device sucessfully, but screen anyway turns off even for short time. "waketime" parameter have no effect.

Suggested solution 1: Make "wake on motion" and "wake on face detected" events to reset System's Idle timer, or turn on "Prevent Screen Sleep" for some time. Make same for MQTT "wake" command.

Suggested solution 2: Add MQTT command for sending screen to sleep, while keeping "Prevent Screen Sleep" option set "On"

**Comment by olili** [comment]
Same Tablett (Galaxy Tab2 7", Lineage 13.1=Android 6.1) with me, same issue. 
Wakeup by Camera-Motion-Detection is not working - motion detection within camera test is working fine.  
No problems with FireTab 7 (2019, Lineage). 

Any idea why wake-up working with tihs Tab? O.

**Comment by vegetate7** [comment]
Camera-Motion-Detection resricted by minimal LUX setting. Try to lower it to reasonable value. You can chek reported values by MQTT monitorig.

**Comment by olili** [comment]
Thx. 
Lowered LUX to 100, 10 and finally 1: no improvement.

**Comment by thanksmister** [comment]
This may not work with all cameras or devices, sorry.   Without testing on the same device, I have no way to reproduce or test the issue.  It seems like if it works in test, is should work the same when launching WallPanel desktop.  There is no difference between the two.

**Comment by thanksmister** [comment]
Oh... you also need to use some type of screensaver with the application to have motion detection continue to work.  You said " System's "go to Sleep mode"   which implies your device is going to sleep and nothing is going to work after that.  You would need to use either Daydream or the built-in screensaver in order to always keep Wallpanel running in the foreground and the camera active.
