### ISSUE TITLE
NodeRed User and Password

### ISSUE THREAD

**Issue by jemarr** [thanksmister/wallpanel-android#139]
Hi.

I want to run Wallpanel on a tablet to show NodeRed dashboard. I've configured NodeRed's dashboard access with an user and password protection, and an ssl certificate.... so I enter on Chrome this url: https://my_pi_ip:1880/ui and then I type user and password.

So, how to do that with wallpanel ?, I've not found any way to access an url with user and password and dismiss any ssl error...

thanks

**Comment by thanksmister** [comment]
Just use that address in the settings for the dashboard url.  The app just loads web pages, so it will load whatever page you want.  Login happens on that webpage.   If you need to, you can append the username and password on the end of the url as params, like https://my_pi_ip:1880/ui?username=myusername&password=mypassword.  However it sounds like you just need to login to the webpage once it renders.
