### ISSUE TITLE
CPU wake lock

### ISSUE THREAD

**Issue by crispyduck00** [thanksmister/wallpanel-android#147]
On my Android 4.4.2 motion detection is not able to wake the device from sleep. Seems some kind of CPU wake lock is needed that this function works.
It works when camera streaming is enabled and I also tested the Fully Kiosk Browser where motion detection also only works when CPU wake lock is enabled.

I dont want to use the built in screensaver feature because I am using Wallpanel together with another app in floating mode (Xposed XHalo floating) and in this case the Wallpanel screensaver wont dimm the floating window.

**Comment by thanksmister** [comment]
That is how it works in this application, you must use the keep awake feature in order to ensure the application is always running in the foreground.  You can use Daydream on Android as a screensaver if you have it, but otherwise, you need to use the built in screensaver.
