### ISSUE TITLE
Add setting to override default device locale so Text-to-speech language can be different than device locale

### ISSUE THREAD

**Issue by agners** [thanksmister/wallpanel-android#148]
**Describe the bug**
I try to use English UK in a device set to English U.S. 

**To Reproduce**
1. Go to 'Settings' -> 'Language & Input' -> 'Text-to-speech output'
2. Click on Cog wheel right of the 'Google Text-tospeech Engine' to change settings
3. Click on 'Install voice data' and install additional voice data
4. Select Language of installed voice
5. Go back and click on 'Listen to an example'
6. Use WallPanel API `speak` API and listen to another example. Observe the difference.

**Expected behavior**
The language and voice used by WallPanel should be the same as configured in the Android settings.

**Smartphone (please complete the following information):**
 - Device: [e.g. Nexus 7]
 - OS: [e.g. Android 6.0.1]
 - Version [e.g. v.0.9.1]

**Additional context**
Also tried restarting WallPanel and the whole device, it seems not to make a difference.

Ideally the API should allow to select a language (if not, default from Android settings should be taken).

It seems that the code overwrites the language from the current locale setting.
https://github.com/thanksmister/wallpanel-android/blob/master/WallPanelApp/src/main/java/com/thanksmister/iot/wallpanel/modules/TextToSpeechModule.kt#L57

**Comment by thanksmister** [comment]
There is nothing else the application can do to configure the TTS, it follows whatever the device is set at, you may have to restart the device or the application in order for it to pick up changes on the device.   But this is not a bug in the application.   It is not forcing the application to use any particular region for TTS.

**Comment by agners** [comment]
As I wrote in the additional context, I did restart the application as well as the device, not change.

I liked where the language property of the `textToSpeech` object is overwritten by the current default locale, couldn't that be the culprit?

**Comment by thanksmister** [comment]
Could be, the default locale is also taken from the device.

**Comment by agners** [comment]
When I change the system Language to "English (United Kingdom)" the voice does change, so it seems to pick up the system language. The problem is, I'd rather prefer to leave the system language to United States but prefer the United Kingdom Text-to-Speech setting.

**Comment by thanksmister** [comment]
That is the issue, the device follows the system.  The application would need a setting to override the default system of the device in order to use the TTS you want.  This then becomes a feature request.

**Comment by agners** [comment]
From what I can tell Android by default distinguish between between System locale and Text-to-speech locale (whereas the second is by default set to "Use system language". However, WallPanel does not honor the Text-to-speech locale but always forces Text-to-speech locale to use system locale. In my opinion there is no need for a WallPanel setting, it just should take what the user has defined in the Android Text-to-speech settings.

**Comment by thanksmister** [comment]
Yeah, we would have to just comment out this line `textToSpeech?.language = Locale.getDefault()` in the TTS module.

**Comment by aukedejong** [comment]
I'm having the same issue. Are you still planing to fix this?  Looks like a simple fix, reading your previous comment.
Thanks.
