### ISSUE TITLE
Keep screen on is not fully worked

### ISSUE THREAD

**Issue by milesking** [thanksmister/wallpanel-android#15]
Thanks for your great job,
I have a Kindle Fire 2nd gen 8.9 inch, flashed CM13 which is an android 6.0 build. 
I toggled keep screen on, it works ... for hours. And then it will go back to settings, then sleep.

Well, I did not config Hassio or lovelace as dashboard. I customized Hadashboard on port 5050, and config to wallpanel.

The webviewer is android 6.0 default one.

**Comment by milesking** [comment]
It might be cm13's fault. I flashed cm12, and seems ok for over 3 hours.

**Comment by thanksmister** [comment]
It's unlikely to be an issue with the application. There is no mechanism for automatically changing the screens from the dashboard back to the settings.  This would happen only with user interaction such as hitting the back button on the device.  My guess is this is a bug with the OS you are using.   Also, I can't reproduce this without also reproducing your environment.   This seems very specific to your device and OS version.
