### ISSUE TITLE
Support ONVIF or RTSP streaming of the camera in place of MJPEG

### ISSUE THREAD

**Issue by mattstein111** [thanksmister/wallpanel-android#150]
The MJPEG capture is great, but since the camera is live anyway it would be great to expose the camera via ONVIF or RTSP for use in security camera style setups.

Ideally, configurable in the Camera settings, with a couple requisite configurables (user/pass/etc).

**Comment by thanksmister** [comment]
There are no libraries to support those formats on Android. None that are viable to implement and open source at least.   MJPEG is all that will be supported.

**Comment by mattstein111** [comment]
> There are no libraries to support those formats on Android. None that are viable to implement and open source at least. MJPEG is all that will be supported.

Thanks for the quick consideration. I thought I saw an OSS implementation built into a different Android app, but must have been mistaken.

**Comment by thanksmister** [comment]
It is possible there are, but again, none that I have seen that would be viable or free to implement.  If you find something that you think would work, please open a PR and submit the code.

**Comment by mattstein111** [comment]
Yes, I'll take a look around, and maybe play with it a bit. It would be a great capability if it were possible/free/easy.  Thanks for considering.

**Comment by thanksmister** [comment]
I will leave this open as a possible feature request, maybe there are new solutions.   Also look for solutions that may be JavaScript based as I am thinking about moving the codebase to Flutter.

**Comment by danielperna84** [comment]
I vote to allow the user to chose between mjpeg and rtsp, should rtsp be supported some day. rtsp is great for capturing. But mjpeg easily can be embedded / viewed in a browser. In my case I use this to display a mjpeg stream within my dashoard when the doorbell rings. Maybe rtsp can be embedded in a similar way. But with mjpeg it's just really easy to do this.

**Comment by tjwally** [comment]
Does this help in any way?
https://github.com/fyhertz/libstreaming

**Comment by thanksmister** [comment]
This is too complicated of a feature to add and there is no community help on this feature.  Closing for lack of community interest in developing this feature.   I personally don't think its ideal because already we have issues with camera's running constantly on the devices.
