### ISSUE TITLE
Home-Assistant Lovelace stays at page Initializing

### ISSUE THREAD

**Issue by mariowitdoek** [thanksmister/wallpanel-android#152]
**Describe the bug**
When connecting to http://192.168.1.11:8123 the page loads with the HA logo and stays on 'Initializing'. At the bottom the is shortly a long URL that looks like a URL redirect.

**Expected behavior**
Load the page :)

**Smartphone (please complete the following information):**
 - Device: Samsung GTN8013
 - OS: Android 6.01 (cyanogenmod 13.0-201)
 - Browser: standard chrome 
 - Version: 79.0.3945.93

**Additional context**
I tried with legacy version and latest but same result.
Opening the HA page with chrome works.
I changed HA to authorize with trusted networks in stead of multiple users but same result.
Nothing to see in the log of HA.

**Comment by thanksmister** [comment]
This is not a bug with the application, this is either browser incompatibility with the HA page or an issue with HA.

**Comment by mariowitdoek** [comment]
thanks mister thanksmister,
yes I look further and for the legacy I didn't see that there was a config setting for the browser. I choose the crosswalk browser and it loaded. Sorry for my mistake.
Maybe I will post this behaviour on HA forum (or buy a new tablet, but it still works :().

BTW Tx for your app and KUTGW (it is all what is needed for a wallpanel :p)

Mario
