### ISSUE TITLE
Wake sceeen on tap

### ISSUE THREAD

**Issue by pkatzu** [thanksmister/wallpanel-android#159]
**Is your feature request related to a problem? Please describe.**
In the dark the motion detection does not work so to turn on screen one has to push a physical button on their device to access the content.

**Describe the solution you'd like**
It would be great to have an option like "Wake on tap"

**Describe alternatives you've considered**
It's impossible to use another apps that turns screen on as they interfere with either the picture displayed or access to camera.

**Additional context**

**Comment by thanksmister** [comment]
If you use the screensaver feature, you will wake on tap.  The application is meant to be run in the foreground continuously.  So it is suggested to use either a screensaver on the device or the built-in screen saver.  The reason you have to push the button seems to be that you are allowing the device to go to sleep without an active screensaver.

**Comment by pkatzu** [comment]
I didn't use the app's screensaver feature as I wanted the screen to be completely off when not in use (and the app runs in foreground).
The only setting of the device is `Sleep after` and there is no such thing as screesaver (there is Daydream settings but it doesn't look like a screensaver feature to me).
So I have no choice but to use the app's clock screensaver. For this to work I had to enable "Prevent screen from sleep" as well. That way it does turn screen on when I tap it.
Is that what you suggested?
Could you tell me if there is a way to have a "Blank screen" screensaver?

**Comment by thanksmister** [comment]
The Daydream is a screensaver built into Android.

**Comment by thanksmister** [comment]
> It would be great to have an option like "Wake on tap"

Using the screensaver is the only way to provide this feature and as we discussed you can use the built-int screensaver or Daydream.   There has to be something to tap on and the app also has to be in the foreground.  The screensaver provides the touch area to tab to wake the device.
