### ISSUE TITLE
Screen state update only sent once via MQTT

### ISSUE THREAD

**Issue by h4lloween** [thanksmister/wallpanel-android#16]
Hi,

I really love your app! I have a small issue though:
When setting up MQTT the screen state (true/false) is only being sent once.
After that no more submissions are made to the MQTT - all other sensor values (motion, battery) work fine.

Pls let me know in case you need any log files/details, etc.

**Comment by thanksmister** [comment]
Yeah, this is true, there is no call to send an MQTT message when the user becomes present.  This will have to be added.  I think this is called initially but never again, so the functionality is there, its just not connected to

**Comment by thanksmister** [comment]
Closing issue as reporter is unresponsive.
