### ISSUE TITLE
Launch Intent from MQTT/REST

### ISSUE THREAD

**Issue by shbatm** [thanksmister/wallpanel-android#160]
**Is your feature request related to a problem? Please describe.**
I'd like a programmatic way to launch a full screen direct rtsp stream from one of my cameras when motion is detected. I can do this currently by using Tasker to launch a [VLC Intent](https://wiki.videolan.org/Android_Player_Intents/). 

**Describe the solution you'd like**
It would be an awesome feature if this was generalized to take a MQTT or REST payload and launch it as an Intent on the device. Something of the form

```json
{
  "action": "android.intent.action.VIEW",
  "mime_type": "video/*",
  "data": "rtsp://someurl",
  "extra": [],
  "package": "org.videolan.vlc",
  "class": "org.videolan.vlc.StartActivity",
  "target": "Activity"
}
```

**Describe alternatives you've considered**
Could use an MQTT app to set up a subscriber and launch Tasker, but it be great to do it directly from the existing listeners in WallPanel. 

**Additional context**
Would also need a way to return WallPanel back to focus and/or exit the launched app.

**Comment by thanksmister** [comment]
I think we have another similar request to launch intents locally.  The issue is that we cannot go back to the application or close the opened app that launched with the intent.  It would be a one way ticket to the newly opened application.  I am not sure something like Tasker could handle bringing WallPanel back to the foreground, that is probably all that is required.

**Comment by shbatm** [comment]
Where does the MQTT Listener live? If it's in the background as a service (is it listening when the app is backgrounded) could you just re-open the app with a second call to the WallPanel intent? Or maybe use a timeout to return back?

Forgive any ignorance if this isn't possible, Android / Java are not my wheelhouse. 
Willing to poke around when I get some time though...

**Comment by thanksmister** [comment]
You are correct in your thinking, there is a background service running, but it is sometimes hard to discern if the application is in the background.   You could introduce a timeout that relaunches the intent of the app, or make a call to bring the app into the foreground.   You could listen to two incoming MQTT messages, one to launch external intent, the other to bring the app back into the foreground.

Where this gets possibly messy is the timing of swapping apps and also making sure the device does not put the background app (wallpanel) asleep or go into sleep mode.  Without being in the foreground, the app is no longer keeping the device from sleeping and it become vulnerable to Androids garbage collection.   

I am open to the idea of trying to launch intents through MQTT and bringing the app back into the foreground via MQTT.

**Comment by thanksmister** [comment]
I think launching other application could be achieved through other means.  Please investigate the use of Termux, Tasker or other app to launch applications or switch between them.  Some of those options can be called with MQTT from your home automation platform.   There are many intents to handle and this might be out of scope for this application.
