### ISSUE TITLE
Zoom not working

### ISSUE THREAD

**Issue by R5fan** [thanksmister/wallpanel-android#161]
First of all, thanks Mister for keeping this awesome project alive!

Zoom level doesnt seem to do anything on any of my android devices (all running android 9). On my tablet with 1200px horizontal resolution I always have 2 columns. On my phone with 1080px I only get one.  In landscape mode my tablet with 1920px will show 4 columns, on my phone with 2340px I get 2 ?

I tried various zoom level settings, I cant spot any difference.

**Comment by thanksmister** [comment]
Zoom is marked experimental, it may not work at all depending on your device.
