### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by djstkg** [thanksmister/wallpanel-android#165]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I use FHEM home automation with FTUI GUI which has BasicAuth enabled. Would be nice to have BasicAuth support in you app.

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**

**Additional context**

**Comment by thanksmister** [comment]
No, this will not be supported.
