### ISSUE TITLE
Camera Snapshot url

### ISSUE THREAD

**Issue by Trrw** [thanksmister/wallpanel-android#166]
Can you add a snapshot url (jpg)? I would like to use the app as a security camera in ioBroker.

**Comment by thanksmister** [comment]
Not sure what you are asking for?  You want to get an image url of the camera?

**Comment by Trrw** [comment]
Sorry, yes I would like a url where an image is generated when called. So for example /snapshot.jpg then shows exactly the image from the camera when the url was called. Something like that would be great :)

**Comment by thanksmister** [comment]
Not sure you can get a public url to the image on the camera, is that what you are suggesting?  We can post that image some place, I do this in the Alarm Panel application.  Alternatively, if you are streaming using MJPEG to Home Assistant, you could do something there to capture an image, no?

**Comment by rufusgor** [comment]
I support it, I really need this function.

**Comment by thanksmister** [comment]
The only way to get this feature is for someone to build it and do a pull request.  I appreciate that people like this feature and their feedback, but we have so many feature reqeust.
