### ISSUE TITLE
http://local-ip:8123 doesn’t load

### ISSUE THREAD

**Issue by WireFuCo** [thanksmister/wallpanel-android#167]
**Describe the bug**
Downloaded the latest version to my Android Tablet, KitKat 4.4.4. When I configure the dashboard url to my local instance of home assistant (http) I just get a blue banner at the top.
I also tried my nabu casa url which is https with no luck.

**To Reproduce**
1. Configure dashboard url to: "http://x.x.x.x:8123
2. Click on Dashboard link
3. See blank page with blue banner at the top.

**Expected Behavior**
Load up my home assistant dashboard 

L

**Smartphone (please complete the following information):**
 - Samsung Galaxy Tab E
 - OS: ANDROID KitKat 4.4.4
 - 0.9.1

**Comment by thanksmister** [comment]
The application uses the built-in WebView component of Android.  The application cannot do anything to manipulate or make the html page you choose to render better.  This is entirely dependent on the compatibility of the version of WebView your device has and the code of the webpage you are trying to display.   This is entirely unrelated to Chrome browser, the WebView uses a subset of Chrome and may not offer the same compatibility.
