### ISSUE TITLE
Lovelace swipe Navigation breaks webview

### ISSUE THREAD

**Issue by boesing** [thanksmister/wallpanel-android#168]
**Describe the bug**
Hey there, I am using a homeassistant plugin for lovelace (installed via HACS):
https://github.com/maykar/lovelace-swipe-navigation

Plugin works great in chrome browser but with wallpanel, the screen pinches to the top left corner (landscape).

**To Reproduce**
- Use 7" Tablet (I am on Nexus 7)
- Connect to homeassistant (localip:8123) with enabled swipe plugin
- Swipe in landscape mode

I get random screen changes. I think you need at least 3 dashboards (doesnt matter if empty or not) to see the issue.

**Expected behavior**
Browser Window does not shring to 1/3 of the screen (the rest of the screen is white)

**Screenshots**

![image](https://user-images.githubusercontent.com/2189546/78507434-3a8c1680-7780-11ea-976f-15a3bda27ba0.png)

**Tablet**
 - Device: ASUS Nexus 7 (2013)
 - OS: Android 6.0.1
 - Browser Chrome
 - Version 80
- App Version 1.2

**Comment by thanksmister** [comment]
The application uses the built-in WebView component of Android.  The application cannot do anything to manipulate or make the html page you choose to render better.  This is entirely dependent on the compatibility of the version of WebView your device has and the code of the webpage you are trying to display.   This is entirely unrelated to Chrome browser, the WebView uses a subset of Chrome and may not offer the same compatibility.

**Comment by nagyrobi** [comment]
Use Bromite WebView to upgrade the built-in WebView of various Android versions:
https://github.com/bromite/bromite
There are instructions on how to replace completely the WebView engine for rooted, or even unrooted devices.

Bromite project seems to be kept up-to-date and besides a simple WebView implementation, has some good aspects related to privacy and video playback ;-)
