### ISSUE TITLE
Movement detection overheating ?

### ISSUE THREAD

**Issue by agusalex** [thanksmister/wallpanel-android#169]
I know this is hard to reproduce and maybe I had bad luck but wanted to let you guys know that when having movement detection on I burned two tablets in a row (both lasted 2 days). Mind you they were cheap, but one was brand new and they where different models and brands. I just left them running plugged in with movement detection and screensaver. I used them to display TileBoard for Home Assistant.
I love the work you guys are doing and keep it up!  Do you suggest any hardware that wont quit on me ?

**Comment by thanksmister** [comment]
The application is not doing anything special, it's just using two different camera images to detect differences between them, it's not really intensive at all.  This should not be any more hardware intensive than just having the camera on  for long periods of time.   I don't think you can really say this is an issue with the application anymore than a video application.   It could be the power supply or the screen being on continuously that causes an issue on the tablets.   I don't have any hardware suggestions other than do not buy whatever you bought.  I run the software on cheap Amazon Fire tablets without issues, but I use the stock power adapters as well.

**Comment by voyo** [comment]
I can confirm this problem with overheating.
I was using old/crashed Yotaphone 2 (Android 5.0). Camera motion detection was enabled, phone was plugged to original charger (with battery).  I was always had an impression it is much hotter when motion detection is enabled, but I left it like that. Then some day battery exploded, fortunately nothing more has damaged.
Yesterday I plugged it again, on my desk, without battery at all, just using my lab power supply, with current monitoring.
my observations, with below environment - 
fresh OS (lollipop), nothing else installed beside WallPanel, MQTT(60s reporting intervals), HTTP server, most time on screen saver(clock) :
- motion detection with front camera enabled (15 FPS) -  it draws between 0.6-1.1 A 
- camera motion disabled - it draws from 0.22 to 0.4 A current, after some time phone is definitely cooler

I'm not sure whether it is related to maybe old Android (older, less effective API ? ), or this particular hardware. But definitely something have influence on power usage (thus overheating).

**Comment by allofmex** [comment]
I noticed the same on various Sony devices. Devices are getting hot.
 I assume, active camera consumes a lot of power. (App independent)
@voyo can you test power consumption with normal camera app too? (Live view and movie recording)
By the way: how do you power the phone without battery? Power supply connected to internal battery pins?

**Comment by thanksmister** [comment]
This is not an application problem, this is a hardware issue on certain devices.  Devices that experience overheating when running the camera all the time should not use the motion or streaming video features of the application.  There may be other hardware fixes as @allofmex has mentioned, but as for the application, this is not an issue I can address.

**Comment by voyo** [comment]
@allofmex, @thanksmister   - yeah, I confirmed - with wallpanel not started, and default camera app running (just video displayed from front camera) - my device is overheating as well after some time.
I thought it can be maybe old API problem, but this clearly proves it probably is not. Obviously some devices cannot have camera running all the time... (this is worth mentioning in wallpannel documentation or whatsoever).

how to run phone without battery - I was lucky, my device was ok to accept 3.6V power supply directly without battery, (android is just showing constantly 50% for battery) but if your is not - google for how to emulate the resistance for the BSI and BTEMP (thats the keywords)

**Comment by thanksmister** [comment]
The only recommendation is not to use the camera features, this is not an issue we will fix.  Camera is used to provide camera streaming and face detection, do not use these features if your device has issues with the camera always being active.
