### ISSUE TITLE
Option to set WallPanel as Home App

### ISSUE THREAD

**Issue by nagyrobi** [thanksmister/wallpanel-android#170]
Please add an option to set it as a home launcher app. Add a shortcut to Android Settings to the menu, so that one can reach back to restore the oringinal launcher if he/she needs to.

This would be a great way to ensure it's always running.

**Comment by thanksmister** [comment]
Yeah, I like this option.  WallPanel should always be running in the forefront, so having it be the launcher app makes sense.  I would even like to add kiosk features to lock the application in the foreground more, but I think some users might oppose this idea.

**Comment by bverkron** [comment]
Would love to see both (foreground and kiosk)! You have my vote!
