### ISSUE TITLE
Screensaver - Screen not dimming

### ISSUE THREAD

**Issue by iklang** [thanksmister/wallpanel-android#173]
Hi,

Thanks for your amazing work. I love every features of this app but I had one huge problem. The screen cannot be dimmed while inactive. I've had the same problem as this issue.

https://github.com/thanksmister/wallpanel-android/issues/87

Did he resolve his problem? How?

I'm using Amazon Fire 7 7th gen. And installed app form Google Play.
Tried on Fire OS 5.6.40, 5.3.7.0
The tablet has no brightness permissions settings. 

Thanks,
- Klang

**Comment by iklang** [comment]
I've tried the app on Amazon Fire 7 (9th gen), Fire OS 6.3.1.0 and the dim function is working. So, I guess it's the hardware/os limitation on Fire 7 (7th gen)/Fire OS 5?

I had so may Fire 7 (7th gen) tablets lying around and would love to make it work on them. Do you have any suggestion? Root them? Can I upgrade Fire OS from 5 to 6 on Fire 7 (7th gen)?

Thanks,
- Klang

**Comment by iklang** [comment]
Is there a way to dim 100% without screen saver or clock?

**Comment by thanksmister** [comment]
I also cannot address why your Amazon Fire 7 7th generation, I use an Amazon Fire 7  7th generation as well, but do not have any issues.  I am running stock FireOS version 5.3.7.

**Comment by thanksmister** [comment]
> Is there a way to dim 100% without screen saver or clock?

No, you cannot dim the screen to 100%, that would be turning it off.   You can set the screen brightness using MQTT.  Please refer to the documentation https://github.com/thanksmister/wallpanel-android#application-state-data.

**Comment by iklang** [comment]
> I also cannot address why your Amazon Fire 7 7th generation, I use an Amazon Fire 7 7th generation as well, but do not have any issues. I am running stock FireOS version 5.3.7.

Hmm.. 

I just open a brand new Amazon Fire 7 7th generation (It came with Fire OS 5.6.0) and install wallpanel through Google Play right away. Same problem Cannot dim it. 

What's different between yours and mine? Did you root it? Did you install Google Play? Or just side load your app directly? Should I tried any particular version of your app?

Thanks,
- Klang

**Comment by thanksmister** [comment]
Maybe this is a permissions or settings issue.  For the application to control dimming you have to set it in the settings and also grant permissions.  My Fire table is not special, direct from Amazon with stock OS and not rooted.   

Be sure you have this permission active for your device. 

![Screenshot_1587243485](https://user-images.githubusercontent.com/142340/79671127-5343f580-819e-11ea-89d3-f5e3760376cb.png)

Then set dim value and turn on screen saver or force screen to be always on in the settings.  You need to use the capture button to capture the current screen setting.

**Comment by iklang** [comment]
That's the one. I cannot find this permission setting page on my Amazon Fire 7 7th generation. Please tell me how to access it? I checked all my setting menu and I could not find this setting.

Thanks.

**Comment by thanksmister** [comment]
I think if you reinstall the application,  you will see this permission asked for the first time you turn on screen brightness in the settings.

**Comment by thanksmister** [comment]
Well on Amazon OS this permission is not asked for because I think it can be done without permission.   So basically it should just work.   Which it doesn’t seem to be for you.

**Comment by iklang** [comment]
Well that's too bad. 

Are you sure your tablet is Amazon Fire 7 7th generation (2017)? 

Thanks a lot for helping me.
Klang

**Comment by thanksmister** [comment]
Yes, I have the same.  If it doesn't work on your device, its probably not going to work due to the devices operating system.  I suggest manually dimming the device and using a screen saver.  If you want a black screen saver then use the image screen saver feature with a black image.  That is the best I can offer as a workaround for the moment.

**Comment by iklang** [comment]
What is the image screen saver feature? I don't see where I can set my own image as the screen saver.

Thanks

**Comment by thanksmister** [comment]
> What is the image screen saver feature? I don't see where I can set my own image as the screen saver.

No, sorry, you can only us unsplash images.  I am certainly open to pull requests if you would like to work on that feature.

**Comment by iklang** [comment]
I would love to try that features. Thanks a lot.

**Comment by maltemosler** [comment]
I have the same dimming issue. (FireHD 8 gen 7) 

Every dim function doesn't work - Dim screen by 90% when screensaver is active or sending mqtt to the tablet doesn't work.

Sending other mqtt commands like reload or wake are working as expected. 

do you have the version without advertising? Maybe this is the difference

**Comment by thanksmister** [comment]
> do you have the version without advertising? Maybe this is the difference

There is no advertising in this application. It is a free open source project.  I this feature doesn't work for you then its may not be compatible with your device.  As others have reported, there seems to be an issue with permissions and dimming on Fire OS devices.

**Comment by maltemosler** [comment]
Woops I meant there a two versions of the **FireHD**, one with advertising and one without. When you turn on the display it shows advertising even without pin and maybe because of this behaviour I had the idea that this could be the difference. 

I didn't mean this btw **awesome** application. 
**Sorry** for not beeing clear.

**Comment by thanksmister** [comment]
I am not familiar with that Fire, and I still think that the brightness issues could be related to Fire tablets or the Fire OS.   I do have a Fire tablet and it does not seem to have this issue.  So until I can test and see the issue, I am not able to address it with a software udpate.

**Comment by iklang** [comment]
> Woops I meant there a two versions of the FireHD, one with advertising and one without. When you turn on the display it shows advertising even without pin and maybe because of this behaviour I had the idea that this could be the difference.

When you buy a fire tablet, there are two options. "With Special Offers" or "Without Special Offers". "With Special Offers" is $15 cheaper but will display Amazon ads on the lock screen. What he asked was which option is your fire tablet? 

Mine is "With Special Offers" and the dim function doesn't work. I'm very interest to know this too as I'm still looking for the different between your fire tablet (dim function works) and mine (dim function does not work).

**Comment by iklang** [comment]
@maltemosler What is your Fire OS version? Did you update your Fire OS to the latest?

**Comment by maltemosler** [comment]
Yeah I am using the newest version and I also removed the ads with a little hack. 
But this should'nt matter I found the bug in the code 🥇

**Comment by thanksmister** [comment]
@maltemosler I am merging your changes now and will create a new version of the application soone for distribution.  Thanks for your contribution!!

**Comment by iklang** [comment]
>  I also removed the ads with a little hack.

Can you tell me how? Thanks.

**Comment by maltemosler** [comment]
@iklang 
https://www.youtube.com/watch?v=l7aiftfufS8&

@thanksmister 
Thanks for the fast merge. The issue can now be closed 👍

**Comment by iklang** [comment]
> https://www.youtube.com/watch?v=l7aiftfufS8&

Thanks a lot.
