### ISSUE TITLE
Brightness Settings and Screen Saver

### ISSUE THREAD

**Issue by iklang** [thanksmister/wallpanel-android#174]
May I suggest something

1. You should let user set the default brightness via text input field 1-255. The capture current brightness is so confused.
2. You should let user set the dim brightness via text input field 1-255. Less confused and more control.
3. Add just a plain black screen as an option besides the clock and wallpaper screensaver. Combine this with the ability to set brightness to 1 (from #2) will be the closest to turning off the screen.
4. Or even better, let user choose the url as the screen saver. With this, user can customize what they want for the screen saver.

Thanks,
Klang

**Comment by thanksmister** [comment]
I would happy to accept pull requests for features you think would improve the project.

**Comment by iklang** [comment]
=)
