### ISSUE TITLE
Feature request: MQTT and HTTP Commands: Set the dim level

### ISSUE THREAD

**Issue by iklang** [thanksmister/wallpanel-android#176]
Hi,

The screensaver function is pretty cool. I've set the dim screen to 50% which works great during the day. 

However, I want the screen to dim 99% at night when no people using it to save the energy and screen life. Right now I can set the screen brightness via mqtt to 1 during the 10:00pm - 5:00am. But during that time, if someone touch the screen, the brightness will remain very dim since the main brightness has been set to 1. 

If the app has a mqtt command to set the dim level, it would solve the problem.

Thanks,
- Klang

**Comment by thanksmister** [comment]
The dim level is a percentage of the brightness level you set.  You would need to set the brightness using MQTT or HTTP.  You can either set this based on receiving a MQTT message of user activity or you can do this by time.  But I do not think there is a need for another MQTT command.

**Comment by iklang** [comment]
> You can either set this based on receiving a MQTT message of user activity

Is there an event when the screen becomes active from the screensaver? I don't want to change the brightness based on the motion.

**Comment by thanksmister** [comment]
No, there is no such detailed event, its just event for "screenOn":true

**Comment by iklang** [comment]
Currently, there is no way to detect when the screen become active from the screensaver. I think users will benefit from having mqtt to set the dim level. I'll try to find another way to achieve my goal. 

Thanks for your awesome app,
Klang
