### ISSUE TITLE
random wallpapers screensaver - timer?

### ISSUE THREAD

**Issue by nagyrobi** [thanksmister/wallpanel-android#181]
How difficult would it be to load a new image every 5 minutes?
I see in the code 
```
//wallPaperHandler?.postDelayed(this, TimeUnit.SECONDS.toMillis(900L))
```
Is it enough to uncomment this line?

(I am acutally using my own picture gallery from my internal server with a very simple php to throw a random image just like unsplash.it)

Edit: it is. 900 means 15 minutes. Excellent.

**Comment by nagyrobi** [comment]
Or maybe implement an MQTT command to trigger loading a new picture.

**Comment by liamwx** [comment]
I came here to request the same feature. I like the random screensavers and would love it to get a new random one every N hours.

**Comment by thanksmister** [comment]
There was already a pull request for this feature, https://github.com/thanksmister/wallpanel-android/pull/195.   I just need to put out a new build, coming soon!
