### ISSUE TITLE
Random wallpaper PHP script

### ISSUE THREAD

**Issue by nagyrobi** [thanksmister/wallpanel-android#184]
For anyone interested, [here's a quick & dirty PHP script](https://github.com/nagyrobi/random-picture-php-script) to mimic very basic unsplash.it functionality with your own folder with pictures. 

Of course it doesn't do cropping resizing etc. on the fly but in PHP almost anything is possible. WallPanel will center the image to fill in the display without distorting the aspect ratio. 
The best would be to prepare files corresponding to the resolution of the display.

**Comment by thanksmister** [comment]
Would be nice if we had a section in the documentation to capture some of this for users interested in extending functionality of wallpanel through additional applications or functionality.

**Comment by nagyrobi** [comment]
do you have any Idea how could I change in `WallPanelApp/src/main/java/com/thanksmister/iot/wallpanel/ui/views/ScreenSaverView.kt` around line 134 so that in `UNSPLASH_IT_URL` we could pass the value of mqttClientId as a parameter to the URL?

I am copiling my own build with my own internal URL to the wallpaper script above. I'd use an unique ID for each display (the existing mqttClientId would be perfect for this) so that on the server side I could serve apropriate pictures for each display (different content).

Since I'm no java programmer I have no clue how could I bring the value of mqttClientId variable from other parts of the app here. In good old Visual Basic days it was possible to declare a variable as public. I don't see a way to do it here....

**Comment by thanksmister** [comment]
We save this value in SharedPreferences for Android within the settings.  So you can get this value by doing getting it from the Configuration class, which is like a wrapper for the SharedPreferences, you would call configuration.mqttClientId wherever configuration is available.  

The screensaver gets called from BaseActivity in method showScreenSaver() and the class BaseActivity has access to the configuration class.  You would pass the configuration.mqttClientId value into the showScreenSaver method, which then passes it into the ScreenSaverView in the constructor.

**Comment by thanksmister** [comment]
You are doing very well for a non-java programmer.

**Comment by nagyrobi** [comment]
Ah nevermind. Meanwile I solved this from the server side. Since I use a fixed IP address (static DHCP lease) for the tablet, I can decide within PHP for which tablet we do serving: based on `$_SERVER['REMOTE_ADDR'];`
