### ISSUE TITLE
Pro/Paid Version of the App

### ISSUE THREAD

**Issue by mattstein111** [thanksmister/wallpanel-android#187]
Feature request:

(inspired by another feature request in another thread, and really just formalizing the idea here)

I'd gladly pay for this app. In current form, a donation may be appropriate, but with a few more small features I would certainly pay per tablet, or per Google account, etc. I'm using it on the Amazon Fire tablets, so putting it on the Amazon store would be easiest for me, as I don't want to have to put the whole Google stack on them just to pay for the app.  Either way, the idea is for a paid version. Implementation notwithstanding.

**Comment by nagyrobi** [comment]
If there's a plan for a paid version, please keep out any dependency from Google's closed ecosystem like Google Play Services etc.

The whole thing under the hood that's most important is privacy, using WallPanel with home automation like Home Assistant is currently possible completely offline, separated from any internet access.

There are great hardwares out there which can be (re)used as wall panels by using custom roms without any Gapps at all, making these run faster and more stable. No need for any Google account to operate a wall panel in a private environment.

**Comment by thanksmister** [comment]
I was able to use the app on my Amazon Fire 7, but its not the best tablet.  It is a custom version of Android and it has some issues I can't solve.  Sometimes the app just quits without reason or warning, it seems the Fire OS does this, no idea why.

**Comment by thanksmister** [comment]
> If there's a plan for a paid version, please keep out any dependency from Google's closed ecosystem like Google Play Services etc.

You cannot really avoid hits, the face recognition or TTS features is part of Google services as well as the crash analytics I use.  But the application does not talk with Google or transmit data.  There are not enough good open source libraries to accomplish all that you want without also using Google.   However, the app does not require Google Play or Google services to be installed, just the dependencies in the application.

**Comment by nagyrobi** [comment]
> I was able to use the app on my Amazon Fire 7, but its not the best tablet. It is a custom version of Android and it has some issues I can't solve. Sometimes the app just quits without reason or warning, it seems the Fire OS does this, no idea why.

Try to look here: https://forum.xda-developers.com/amazon-fire/orig-development
Pick any LineageOS ROM and revive your tablet to run fast and stable.

**Comment by nagyrobi** [comment]
> the app does not require Google Play or Google services to be installed, just the dependencies in the application.


That's fine as long as any future paid version can comply with this. I have WallPanel running on devices with pure LineageOS without any proprietary Google apps on them. Motion detection by the camera works perfect.

**Comment by thanksmister** [comment]
> I'd gladly pay for this app. In current form, a donation may be appropriate, but with a few more small features I would certainly pay per tablet, or per Google account, etc.

It's not just a matter of money, it's a matter of time. If you have a paid version, then I can architect and hire a developer to work on the project paid for out of the revenue from app sales.  Most open source projects have many contributors to add new features, but this one is mostly done by me, which conflicts with my actual paid work.

**Comment by thanksmister** [comment]
> > the app does not require Google Play or Google services to be installed, just the dependencies in the application.
> 
> That's fine as long as any future paid version can comply with this. I have WallPanel running on devices with pure LineageOS without any proprietary Google apps on them. Motion detection by the camera works perfect. Also TTS, using third party offline TTS engine sideloaded.

Paid applications would be loaded from Google Play where payments are collected.  It is much more difficult to manage a paid project and distribute apk separately from the store.  I would also like to move to using Flutter which provides cross platform capability.  We might lose some ability on iOS that can be offer on Android or I may have to use libraries from Google that are supported on both platforms.   Open source 100% is nice, but it does not make it always possible to have a good application that works.   Think about voice recognition, QR code scanning, Face recognition for Android and iOS.  The best libraries are from companies.

**Comment by thanksmister** [comment]
The requirements for any future version of WallPanel app should be as follows:

1) Works on local network (not same as offline, but communicates on local network).

2) Does not require external service call to operate, such as communicate outside network to 3rd party service in order to work properly.

3) Be private by design, does not expose user or application data unless used for crash reports or analytics (app analytics is used for crashes and also to analyze use of paid application for future features).  

4) Use agnostic protocol such as MQTT or websockets to talk to home automation platform, should not be tied to specific home automation platform. 

5) Be cross-platform and work similar on both platforms as much as possible.

**Comment by thanksmister** [comment]
> Try to look here: https://forum.xda-developers.com/amazon-fire/orig-development
> Pick any LineageOS ROM and revive your tablet to run fast and stable.

I am planning on rooting this device, but overall the Amazon tablets are a low level device and not the best choice for running applications.  The price is the reason to buy them, but they minimal devices as a result.   Maybe the HD versions work better, I do not know.

**Comment by nagyrobi** [comment]
> Open source 100% is nice, but it does not make it always possible to have a good application that works. Think about voice recognition, QR code scanning, Face recognition for Android and iOS. The best libraries are from companies.

OK. I agree that for these "extras" a paid application would justify. Where you'd have to use such proprietary libraries to bring in "fancy" features. Maybe people wanting to use these are less keen on privacy and having proprietary ecosystems running on their units.

But features not requiring anything special like [root access](https://github.com/thanksmister/wallpanel-android/issues/186) or motion detection etc could be kept in a fully free 100% open source separate version, which would still allow sideloading and not requiring any sort of Google to operate or be put in operation.

**Comment by thanksmister** [comment]
@nagyrobi yes, the open source version will always continue, but it will not have the same feature set, or it will have features that lag the paid verison.

**Comment by nagyrobi** [comment]
Cool. I agree that some of the existing functionality relying on proprietary libraries could be moved to paid version too.

**Comment by thanksmister** [comment]
I am thinking a pro/paid version would have more tools for rooted devices. @nagyrobi can you maybe list all the features that would be nice in a version of the app that runs on a rooted device.  This would be Android only, the device would be rooted or running custom software such as Grandstream devices or specialized tablets.   

I know I would like a device that runs full screen and cannot be put into the background, the options available that I have seen are really not user friendly or they use some type of enterprise software for managed devices.  But I would think you could achieve this on a rooted device.

**Comment by nagyrobi** [comment]
I'm sorry but thought until now that you're on the side of openness. I still think that features requiring rooting the units should be kept in the free/opensource version, whilst fancy features like sound and face recognition etc should be moved to the pro/paid version of the app.

Here's why:
- someone taking the effort to learn and dig into the internals of the units, even by rooting it (thus also voiding warranty) spends a lot of time and work to achieve results. This proactive mind should be encouraged by openness and open sourcing and freedom.
- on the other side: people wanting quick results and fancy stuff, without too much work put in could go with ready-made proprietary solutions which indeed justify payment. These people would be much more happy to pay than the ones in the previous point.
- things needed to add root-related capabilities to WallPanel are all open sourced. It would be fair to keep them alike in WallPanel too.
