### ISSUE TITLE
Small feedback/vib when a button is pushed? 

### ISSUE THREAD

**Issue by adangster1** [thanksmister/wallpanel-android#189]
Hi.. I am not exactly sure if this is hassio limitations ..but is there a way ..on click>> make the wallpanel app to create a small feedback..like a quick  vibration...so the user know that something is activated..ie switch turn on when touch will cause 1 vib..like gui feedback  on android 

Thanks

**Comment by thanksmister** [comment]
You cannot do this from the webpage, this is called haptic feadback.  The app does not receive notifications from the rendered page or manipulate the page.

**Comment by adangster1** [comment]
Thanks
