### ISSUE TITLE
Don't show history_graph cards

### ISSUE THREAD

**Issue by xabileiro** [thanksmister/wallpanel-android#19]
I tried the application on a mobile and a tablet with Android 7 and it works perfectly, but instead on a tablet with Android 4.2.2 it does not show the history_graph cards.

**Comment by thanksmister** [comment]
Hey thanks for asking the question.  Yeah, on older devices you have an out of date WebView which means you can't render the same web pages as newer devices.  You can try the legacy browser in the settings or you can look for a new WebView update on Google Play.

**Comment by xabileiro** [comment]
I tried to change the browser and it does not work. If I select webview it does not show anything and if I select it shows everything except the history_graph.
On the other hand, if I open the frontend with chrome it works perfectly.
Anyway, thank you for your quick response.
