### ISSUE TITLE
Coordination of documentation of feature integration of third party apps/space for show-off of community projects

### ISSUE THREAD

**Issue by ulno** [thanksmister/wallpanel-android#191]
I commented in issue #186 that a lot of the recent feature request can be solved through third-party apps (and often through running scripts or node-red in termux).

I assume that several people would be willing to share/show-off their set-ups here. I thought I could open this issue to help coordinating these documentation efforts.

I am working on a couple of home automation youtube videos featuring android based wall panels (running wallpanel and sshd in termux), mycroft, rhasspy, and node-red (I am not personally using hass, even if I often recommend it in my home autmation classes. Therefore, wallpanel is usually just running node-red dashboards for me), I will look if I can make some documentation cross-link suggestions, but things are moving very slowly at the moment, so it might still take a couple of weeks until I have something meaningful to share here.

Rhasspy has a show-off group in their discourse - @thanksmister do you have something like that, or should we use this issue here to collect ideas? I am not sure if github offers a way for that (maybe the wiki?) or if that requires some external tool like discourse. Maybe, having a special doc-subfolder against which we could make pull-requests could be an easy solution for creating "community"-project-documentation? Please add other ideas to realize this as response to this issue.

**Comment by thanksmister** [comment]
@ulno I think I will start a discourse group or do something like this for discussion of all my projects.  I started working on a home alarm system recently using Node-Red running on an Android device using termux with a custom Android application in kiosk mode.  

The idea is to have a stand alone alarm hub that talks using MQTT to the alarm app and other security sensors that can also work offline.   I like your option of having a node-red dashboard running in WallPanel as well.  I would look forward to any documentation you can share and will let you know when I setup a chat channel for projects.

**Comment by thanksmister** [comment]
@ulno finally got discourse up and running, here is the link https://community.thanksmister.com.  I will be adding this to all the repositories so users can go there to discuss or share information.
