### ISSUE TITLE
Passing Intent Data

### ISSUE THREAD

**Issue by hoasis2** [thanksmister/wallpanel-android#193]
I wonder how to start Wallpanel from the adb shell passing a different Dashboard URL as intent data. Any suggestions?

**Comment by thanksmister** [comment]
You could check Stackoverflow, this is really question about launching intents.  The application does not have a way to pass intent data on app launch.  You would change the dashboard url by sending an MQTT command, the application should read this command when starting MQTT, maybe you need retain true on that MQTT message.   This is also a good question to ask on the new community page, hopefully other users can help answer this type of question.  https://community.thanksmister.com/.

**Comment by hoasis2** [comment]
Thanks for the clarification!
