### ISSUE TITLE
App not responding to commands via MQTT

### ISSUE THREAD

**Issue by Joecorleone** [thanksmister/wallpanel-android#196]
!!!! I found the reason after reading the documentation once more and comparing with sensor data sent by my wallPanel: 
It does not publish to the baseTopic

From documentation:
> For MQTT

    WallPanel publishes all sensors to MQTT under [baseTopic]/sensor
    Each sensor publishes to a subtopic based on the type of sensor
        Example: wallpanel/mywallpanel/sensor/battery

However, in my case it publishes to "wallpanel/sensor/motion"
So the issue is wrong and should be **App does not use baseTopic for publishing and receiving commands**

**Describe the bug**
I am using openHab to send commands to WallPanel via MQTT. However, the app appears not to be receiving anything. E.g. {"eval": "alert('Hello World!');"} nor {"relaunch": true} seem to have an effect.
I am using MQTT.fx to monitor the messages sent via mqtt. The tablet I am using is sending sensor data correctly and openHab is receiving it. Furthermore, the command from openHab is sent and formatted correctly:
![WallPanel01](https://user-images.githubusercontent.com/2007417/83396207-ead27000-a3fb-11ea-891a-90b2ea823461.png)
Even sending the command from MQTT.fx directly didn't help.
Thus, I don't believe the problem to be with openHab, but just to be sure here is the javascript transformation used to create the JSON for mqtt:

    (function(x){

    var result = new Object();
	
	if (x == 'true'){
		result.relaunch = true;
	} else {
		result.eval = "alert('Hello World!');";
	}

    return JSON.stringify(result);
    
    })(input)

Originally, I used "mywallpanel" for the baseTopic, no luck either. 
Is there a way, to see the mqtt commands received by wallpanel?

**To Reproduce**
1. Install WallPanel on tablet
2. Install MQTT.fx on laptop
3. connect to MQTT broker
4. Publish message >>{"eval": "alert('Hello World!');"}<< to wallpanel/mywallpanel/command

**Expected behavior**
To show the alert

**Screenshots**
MQTT settings in WallPanel
![WallPanel02](https://user-images.githubusercontent.com/2007417/83398413-992be480-a3ff-11ea-964c-70bf6d182c67.png)

**Smartphone (please complete the following information):**
 - Device: Google Nexus 10 (2012)
 - OS: Android 5.1.1
 - Stock browser
 - Version WebView 83.0.4103.83
 - WallPanel version v0.9.2 Build 1

**Additional context**
What I am trying to achieve is to have the tablet in a drawer. Upon opening the drawer the display should wake up and upon closing the display should switch off. Basically, the camera based motion sensor would be enough. Switching on works perfectly. However, inside the drawer it is dark, thus when the display times out, wallPanel detects "motion" and wakes the display again. Sending mqtt commands from openHab I planned to circumvent said problem. Since nobody here is reporting problems with mqtt commands on that level, I assume it might be something specific to my setup.
Any idea would be very welcome, or an alternative approach equally so.

**Comment by thanksmister** [comment]
I am pretty certain that the app does receive commands.  This could be an issue with the format you are using to send the command, maybe even something as simple as wrong quotes.   

You also have an issue with your use case, the app cannot function if the screen sleeps, the motion detection would not work and you would not receive commands if your device also turns off wifi.   

So to get motion to work, you need to either use Daydream from Google or the screensaver options in the application. 

The default base topic for receiving commands is "wallpanel/mywallpanel/" out of the box.  So to send an alert command to this wallpanel would be formatted like this: 

`{"topic":"wallpanel/mywallpanel/command", "payload":"{'speak':'Hello!'}"}`

I would test this before trying eval, as maybe there is an issue with the web page rendering it, so just try with either text to speech.

**Comment by Joecorleone** [comment]
Dear thanksmister, thanks for your reply. 
I honestly was confused myself, when I read my question :-D

To clarify, the app is receiving commands, and e.g. {'speak':'Hello!'} works. However, with my MQTT settings ("Base Topic": wallpanel/ and "Client ID": corridor ) I expected the correct command topic to be "wallpanel/corridor/command", which is not the case. It only works when I publish to "wallpanel/command". The same applies to the sensors. I expected the motion sensor to publish in topic "wallpanel/corridor/motion", but instead it is "wallpanel/motion". 

Regarding my use case, yes there is a problem .... . The device switches off WIFI after a while in sleep, thus waking it remotely is not reliable. I will play around with daydream and the screensaver.

**Comment by Joecorleone** [comment]
A quick update on my case and how I tried to solve it just with the options provided by wallpanel. Sadly there is a cornercase which I could not solve. Maybe someone has an idea how to do this with wallpanel (see below).
As mentioned before, the tablet is in a drawer. I want the display to switch on when I open the drawer and to switch off when closing. The latter does not have to be instant, within a few minutes is fine. When the drawer is closed external light is blocked. 

Issue: Using the wallpanel trigger on motion does not work by itself, because when the drawer is closed and the screen goes into screensaver a motion is triggered and wakes the screen.
Solution: I put a QR code on the inside of the cupboard above the drawer in a way it can only be read by wallpanel, when the drawer is closed. It is sent to openHab (but that should work with home assistant) to change a "qrSwitch" to ON. Now, when a motion is triggered the signal is sent to openHab and when the "qrSwitch" is ON it is set to OFF, but no wake signal is sent back to wallpanel. Later when the drawer is opened the motion signal is sent again, this time "qrSwitch" is OFF, thus a wake signal is sent to wallpanel. This works for me when choosing a dim daydream, but not with wallpanel's screensaver as detecting a QR code is considered an activity (I believe).
Cornercase: All fine? Mostly. My last issue is, that at night the room with the cupboard is dark, thus the camera does not detect a motion when opening the drawer ... . ... At this point, I only see a separate Door/Window sensor to give me the desired result. But I would be happy to be wrong.

**Comment by thanksmister** [comment]
_My last issue is, that at night the room with the cupboard is dark, thus the camera does not detect a motion when opening the drawer_ 

If the room is dark, there will be no motion detected because it works on the difference between light and dark to detect motion.  Perhaps you should install a light that turns on/off when opening the drawer.

**Comment by thanksmister** [comment]
This works for me when choosing a dim daydream, but not with wallpanel's screensaver as detecting a QR code is considered an activity (I believe).

Yeah, clever solution with the QR codes.  I believe the camera should still work with the built-in screensaver, but perhaps its very low light?  The camera is always detecting faces or QR codes if present.  You can test this with the screensaver on and face detection or motion detection wake.  If either is detected, the built-in screensaver is turned off and the device wakes.

**Comment by thanksmister** [comment]
> To clarify, the app is receiving commands, and e.g. {'speak':'Hello!'} works. However, with my MQTT settings ("Base Topic": wallpanel/ and "Client ID": corridor ) I expected the correct command topic to be "wallpanel/corridor/command", which is not the case. It only works when I publish to "wallpanel/command". The same applies to the sensors. I expected the motion sensor to publish in topic "wallpanel/corridor/motion", but instead it is "wallpanel/motion".
> 

The client id is actually used for identifying the device with the MQTT broker.  However, it looks like in the settings something is disconnected with either the base topic or the client id.   You should only modify the base topic and the second part after the / is the part you would modify.  

WallPanel publishes state to topic [baseTopic]/state
Default Topic: wallpanel/mywallpanel/state

I have to take a look and see the value for client id, I do not think this is associated with base topic, so changing it would not result in [baseTopic]/[client_id], you would modify that in the base topic field only.

**Comment by thanksmister** [comment]
I think you would do something like this, notice the different names for client and the base topic.

<img width="340" alt="Screen Shot 2020-07-01 at 1 53 25 PM" src="https://user-images.githubusercontent.com/142340/86270824-3ebea900-bba2-11ea-878c-b56606e08790.png">
