### ISSUE TITLE
A way to change the behaviour of device back botton

### ISSUE THREAD

**Issue by hoasis2** [thanksmister/wallpanel-android#198]
Thanks for this app. I installed it on a TV of my elderly parrents and it works good. They have only one problem on AndroidTV and it is the "device back botton".

Usualy my mom presses the "back" botton on the TV remote to close an app and she is confused if the "Settings" of the app comes up here and she stucks there. :(

Is there a way to change the way to open settings? Like swipe up?

**Comment by thanksmister** [comment]
I do not have plans on changing this to support the behavior swipe up behavior.   There may be changes in the future that does remove the back button, but I cannot give a time table of when that will happen.

**Comment by hoasis2** [comment]
I see. Probably there are hardly any users who use the app on AndroidTV.

**Comment by thanksmister** [comment]
You are the first I am aware of, but I do agree that the back button is not a good user experience on any device.  So this will be going away in the future.  If you do hit the back button twice, the app will close.  Sorry I could not help at this time.

**Comment by thanksmister** [comment]
@hoasis2 if you could, please share any screen shots, interested to see how it looks on Android TV, thanks!

**Comment by hoasis2** [comment]
Issue solved with the floating settings button. 👍

Thank you!
