### ISSUE TITLE
Enable Touch Sounds

### ISSUE THREAD

**Issue by GazAt105** [thanksmister/wallpanel-android#200]
Hi

Just a feature request thanks.

Is it possible to enable touch sounds in the WallPanel app?

I have enabled "touch sounds" in settings and other apps appear to honour this setting.

**Comment by thanksmister** [comment]
Where are you wanting to have touch sounds?  We cannot enable them on the rendered web page.  So this would only be for the settings.

**Comment by GazAt105** [comment]
Yes I was wanting to enable it in the rendered web page. If this cannot be done then so be it.
