### ISSUE TITLE
Intermittent behaviour responding to MQTT commands

### ISSUE THREAD

**Issue by obiwanzamora** [thanksmister/wallpanel-android#202]
**Describe the bug**
MQTT commands are not being consistently actioned. When sending commands such as wake and url, they are only sometimes actioned.

**To Reproduce**
1. Publish MQTT message
```
{
    "url": "http://192.168.1.94:8123/alarm-control-panel/0"
}
```
2. Wallpanel does not consistently action the commands.

**Expected behavior**
Wallpanel consistently to respond to the MQTT commands

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Kindle Fire 7
 - OS: Fire OS 6

**Additional context**
See below MQTT log to show commands being published and lack of update from wallpanel.

```
Message 27 received on wallpanel/lounge/command at 16:33:
{
    "wake": true
}
QoS: 0 - Retain: false
```
```
Message 28 received on wallpanel/lounge/command at 16:33:
{
    "url": "http://192.168.1.94:8123/alarm-control-panel/0"
}
QoS: 0 - Retain: false
```
```
Message 29 received on wallpanel/lounge/state at 16:34:
{
    "currentUrl": "http://192.168.1.94:8123/lovelace-lounge/lounge",
    "screenOn": true,
    "brightness": 46
}
QoS: 0 - Retain: false
```

**Comment by thanksmister** [comment]
I would check your connectivity and that the application is always in the foreground and also that device does not sleep.

**Comment by obiwanzamora** [comment]
As far as I'm aware the device is not sleeping and application is in foreground. I can see the clock screen saver on the device when testing. Presumably if it wasn't I would not be getting the /state messages?

**Comment by thanksmister** [comment]
Have you investigated if the wifi is still connected?

**Comment by obiwanzamora** [comment]
It must be or I wouldn't be getting the state and sensor messages?

**Comment by yanoosh** [comment]
I think I have a similar problem. I get information about the device status via MQTT and send command back depending on the content of the message. Commands works perfect until screen is on. It looks like the application is working because waking up with the motion sensor turns on the screen.

**Comment by aukedejong** [comment]
Maybe I have a related issue:
When sending a MQTT wake and eval JS command in one command or two commands without delay, the JS is not evaluated.
It I add a delay of 1 second between the 2 MQTT commands, the JS is evaluated.

I think JS is only evaluated when the WebView command has focus.

**Comment by thanksmister** [comment]
Possibly issue with Paho library, I am updating to the latest version in upcoming release.

**Comment by thanksmister** [comment]
> I think I have a similar problem. I get information about the device status via MQTT and send command back depending on the content of the message. Commands works perfect until screen is on. It looks like the application is working because waking up with the motion sensor turns on the screen.

Screen on or screensaver?   If the screen is off, most devices will also kill wifi or remove background services, which the app uses to communicate over MQTT

**Comment by thanksmister** [comment]
This topic quickly became dumping ground for any MQTT issue, I believe the issue is related to two things, MQTT Paho library updated required to fix disconnects and users allowing devices to sleep which kills background commands for MQTT.  Topic closed for further comments.
