### ISSUE TITLE
Homeassistant Slider not working

### ISSUE THREAD

**Issue by tadly** [thanksmister/wallpanel-android#203]
**Describe the bug**
For some reason sliders aren't working through wallpanel. I verified this on multiple devices.
On those devices it works inside chrome so I assume this might be an issue with androids webview maybe?

**To Reproduce**
1. Have a slider in homeassistant (e.g. volume for media-player or custom slider)
2. Try and slide it

**Expected behavior**
Should do what a slider does.

**Smartphone (please complete the following information):**
 - Device: Pixel 3, Lenovo Tab 4 8 plus
 - OS: Android
 - Browser stock

**Comment by thanksmister** [comment]
The ability to render LoveLace components really depends on your device and its support for displaying web pages within an Android application.  The WebView component is what we use and this varies from device to device, it is not the same as using Chrome on your device.   There is not much you can do but try to use different LoveLace setup or something else besides LoveLace for HA.
