### ISSUE TITLE
Home Assistant Lovelace panel not loading (sometimes)

### ISSUE THREAD

**Issue by thexperiments** [thanksmister/wallpanel-android#204]
**Describe the bug**
Most of the time (currently I can't get it to work but it previously was sporadically working) the lovelace dashboard is not loading.

**To Reproduce**
1. Set up the dashboard URL to point to your lovelace UI "http://internal-address:8123/lovelace-yourdashboard"
2. Go to dashboard
3. Log into HA (working)
4. Dashboard working
5. After some time/refreshes notice that only blue top lovelace bar is visible, no dashboard content or menus

**Expected behavior**
Dashboard is shown all the time

**Smartphone (please complete the following information):**
 - Device: Lenovo tb2-x30f
 - OS: Android (Lineage 7.1)
 - Version: Latest from playstore

**Additional context**
SSL not used

Are there ways to troubleshoot this?
Are there ways to clear the "browser" cache?

Previously read of problems with default webview renderer, is this still an issue?

Thanks

**Comment by thexperiments** [comment]
Just walked by the tablet and it is shown again... Maybe to heavy JS somewhere so that loading takes forever? Any tips on debugging this?

**Comment by thexperiments** [comment]
Was not working again after login in freshly. Now I switched the webview implementation in the developer options of android from **AOSPWebview** to **Chrome Stable** and it seems to work much better, let's see.

**Comment by thanksmister** [comment]
Yeah, this is an upstream error, I cannot make Lovelace page perform well, that depends on Lovelace and the capabilities of your devices WebView component.  I was not aware you could change your version of WebView to something not provided in the Google Store.  You are referring to this?  https://chromium.googlesource.com/chromium/src/+/HEAD/android_webview/docs/aosp-system-integration.md

**Comment by thanksmister** [comment]
You could try a less intense web page for Home Assistant, like Tileboard, which seems to work well.
