### ISSUE TITLE
Face detection threshold

### ISSUE THREAD

**Issue by derandiunddasbo** [thanksmister/wallpanel-android#205]
**Is your feature request related to a problem? Please describe.**
ATM the face detection on my Galaxy Tab A is quite sensitive. It detects faces up to 5 meters away from the tablet which leads to many "false positives", i.e. unwanted screen activations.

**Describe the solution you'd like**
Some kind of threshold for face detection. For example it may be possible to measure the size of the face in the camera image and to trigger face detection only if the face detected covers more than x percent of the area in the camera image.

**Describe alternatives you've considered**
A time threshold maybe an alternative to measuring the area. I.e. only trigger face detection, if a face is detected for more than x (milli-)seconds subsequently.

**Comment by thanksmister** [comment]
Face detection uses the Android on device Face API.  This library does not have a feature to decrease or increase the sensitivity of detecting faces.  I think it only has an option to detect large face and small face.   https://developers.google.com/android/reference/com/google/android/gms/vision/face/package-summary.   We do not use cloud face detection, so options are limited.

**Comment by derandiunddasbo** [comment]
Ok, and if I read the code correctly, the app already uses the large face detection, i.e. `setProminentFaceOnly(true)`, doesn't it?

**Comment by thanksmister** [comment]
Yeah, so I think this is as best we can do using the local ML library for face detection.  You might have better results with motion detection, it has a sensitivity sensor.

**Comment by derandiunddasbo** [comment]
Ok, I'll try with that.
