### ISSUE TITLE
Send amount of motion to MQTT

### ISSUE THREAD

**Issue by swordh** [thanksmister/wallpanel-android#206]
It would be a nice feature to have the motion to include the amount of motion registered in MQTT. This way it would be easy to use the amount of motion to trigger diffrent things and use diffrent values depending on if you are home, away, sleeping and so on.

**Comment by duczz** [comment]
@thanksmister It should be all trigger features in MQTT, this is one of the important things on an Adapter, thats why im using currently fully

**Comment by thanksmister** [comment]
That is not how the motion is working in the application, its measuring the difference between light/dark and there is no way to adjust the sensitivity.  It's measuring on a single pixel for changes.
