### ISSUE TITLE
Camera control via Rest-Methode not working

### ISSUE THREAD

**Issue by duczz** [thanksmister/wallpanel-android#207]
It does not work for me to disable/activate the camera via Rest-Methode.

**Comment by thanksmister** [comment]
Yeah, I think there are some issues with disabling it once it's enabled.  You have to do this in the sttings for the time being.

**Comment by duczz** [comment]
Can you say until when this will be fixed?

**Comment by bverkron** [comment]
I have the same issue with the MQTT method. Once enabled I cannot disable it with an MQTT message. All other commands work as expected so far.

**Comment by flashbacck** [comment]
Same issue. I've noticed if you do send the Camera:False command via MQTT, and then browse to the MJPEG settings page, it will be correctly set off. At that point the stream DOES turn off, but then becomes unresponsive to attempts to turn it on again.

**Comment by bverkron** [comment]
Interesting. I had no success getting it to turn off via MQTT
