### ISSUE TITLE
Browser refresh triggers too easily

### ISSUE THREAD

**Issue by bverkron** [thanksmister/wallpanel-android#209]
**Describe the bug**
Might be an underlying OS issue and how it handles multi touch interaction but I have no way to tell.

Whenever I am pinching (say in an embedded webpage in the dashboard) or sometimes even just trying to drag a slider left / right the Browser Refresh gets triggered. I have to be extremely careful in my movements not to trigger it. Even when trying very carefully to keep my fingers aligned horizontal so one is not above the other even by a little bit. Even then it's a real struggle to avoid triggering it.

**To Reproduce**
1. Open embedded webpage in Dashboard. A map of some kind works well
2. Pinch to zoom out
3. Pull down to refresh icon will start appearing at the top

Can repeat with horizontal sliders too.

**Expected behavior**
Browser refresh only trigged when pulling down from top of screen or a significant distance anywhere else on the screen?

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab A 10.1
 - OS: Android 10 / OneUI 2.0
 - Browser: WallPanel Android app
 - Version: Latest as of today (sorry don't have it in front of me)

**Additional context**

Maybe it's not picking up the fact that multiple touch points are in use and is just really sensitive to even slight downward swipe gestures?

**Comment by bverkron** [comment]
Noticing the same behaviour with the new calendar card too. I can scroll down (swipe up) to get to the bottom of the agenda view but most of the time when I try to scroll back up (swipe down) it immediately starts to trigger the Browser Refresh feature.  Haven't identified the exact nuances that make or better or worse. Sometimes it's fine but most of the time it triggers the refresh.

**Comment by thanksmister** [comment]
The solution is unfortunately not to use this feature because the rendered webpage can interfere with the pull to refresh and there is not a lot that can be done unless we disable scrolling on the web interface.   You can alternatively use the MQTT command to reload a page.

**Comment by bverkron** [comment]
Fair enough. Might try that. Closing.
