### ISSUE TITLE
Camera stream

### ISSUE THREAD

**Issue by LaBoss** [thanksmister/wallpanel-android#21]
Good Morning,

I have now installed the latest version of WallPanel and I have a problem with the video stream. The image appears all green ...

https://imgur.com/a/EYCL3LZ

I've already tried reducing the FPS to 1 and no effect. In the previous version (the original) worked correctly.

The tablet in question is a samsung GT-P7500 with android 7.1

Any help or tips?

Thank you

**Comment by thanksmister** [comment]
I don’t have any tips to solve this issue other than what you have already tried.   What was shown in the video tester?   

The previous version of the application is still available on GitHub if you had better luck.

**Comment by thanksmister** [comment]
Closing this issue as reporter was non-responsive.
