### ISSUE TITLE
Disable screen saver if video media playing or if Wall Panel is in the background

### ISSUE THREAD

**Issue by bverkron** [thanksmister/wallpanel-android#210]
Granted these could be two separate feature requests but they're related. Let me know if you want me to split them.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm trying to watch a video in the dashboard or I've toggled to another app and the screensaver kicks in and dims the screen. In the case of other apps having focus I have to manually swipe down from the top of the screen and increase the brightness so I can see what I'm doing in the other app.

**Describe the solution you'd like**

* If a video is playing in the inside WallPanel disable the screensaver. However, this could be tricky if people have camera feeds on their dashboard. Not sure if there is an easy way to distinguish between say picture cards on the Dashboard with a video feed and an embedded youtube video, for example.

* If WallPanel is not the foreground app disable the screensaver.

**Describe alternatives you've considered**
None really. I need the screensaver and don't see any ways around the frustrations without added options / features in WallPanel.

**Comment by thanksmister** [comment]
There is no way to know a video is playing, the app just renders the HTML, it does not and should not inspect it.  The screensaver is activated based on user inactivity.   I suggest you switch to using the device screensaver instead.

**Comment by bverkron** [comment]
Makes sense, thanks for the input.
