### ISSUE TITLE
Face detection not work, "missing appropriate library to process face detection"

### ISSUE THREAD

**Issue by Maurotb** [thanksmister/wallpanel-android#211]
**Describe the bug**

When i exit from setting, i see this error
"missing appropriate library to process face detection"
and face detection not work

**Smartphone (please complete the following information):**
Samsung n8000
LineageOS 7.1 + GAPP NANO

What i need to install?
Thanks

**Comment by thanksmister** [comment]
You need google services, its included.

**Comment by Maurotb** [comment]
ok minimum gapp is micro version
