### ISSUE TITLE
Ability to launch other Android apps via MQTT / Rest

### ISSUE THREAD

**Issue by bverkron** [thanksmister/wallpanel-android#213]
**Is your feature request related to a problem? Please describe.**
If I get an alter on my wall panel that the garage door is open I have to manually walk over and use the app switcher to open the Wyze app to see if the garage door is open for a reason (kids, etc) and can be safely closed

**Describe the solution you'd like**
I would like to be able to launch another app (Wyze for example) based on certain Home Assistant events or triggers. So for example if the garage door alert goes off it will automatically launch the Wyze app so I can see what's up and take the desired action (maybe even just a voice command on my phone to close the door if it's clear).

**Describe alternatives you've considered**
Install another similar app like Ariela which has that [feature](http://ariela.surodev.com/2019/01/14/apps-mqtt-sensor/)?

**Comment by thanksmister** [comment]
This application is meant to run as a dedicated panel, if its not in the foreground it will lose functionality, if you go to another application, it will have no way to go back.
