### ISSUE TITLE
Background color from HA not being honored

### ISSUE THREAD

**Issue by jsnyderman** [thanksmister/wallpanel-android#216]
I removed Wall Panel from a tablet which was working fin.   Upon reinstalling it, the background in Lovelace UI is default white.   But the theme has an almost black background and did used to work before the reinstall.

Theme code is 
      # Backgrounds
      primary-background-color: 'hsl(var(--huesat) 16%)'
      secondary-background-color: 'hsl(var(--huesat) 16%)' # background behind cards
      paper-listbox-background-color: 'hsl(var(--huesat) 16%)'
      paper-card-background-color: 'hsl(var(--huesat) 12%)'
      paper-dialog-background-color: 'var(--paper-card-background-color)'
      table-row-background-color: 'hsl(var(--huesat) 12%)'
      table-row-alternative-background-color: 'hsl(var(--huesat) 10%)'
      card-background-color: 'var(--paper-card-background-color)'

Thank you for any insight

**Comment by RoelVideler** [comment]
Same issue here, only recently started using WallPanel so I've only known this behavior. Running Android 10 on a Samsung S4 and Android 7 (I think) on an NVidia Shield K1.

**Comment by thanksmister** [comment]
WallPanel does not set the background color, this is part of the website.  WallPanel only displays the or tries to render the HTML/CSS of the page.  I may have issues if it cannot render the page.  Android uses the WebView component to render html pages, this is not the same as Chrome browser.   I cannot address this issue, you have to change your theme in HA.

**Comment by RoelVideler** [comment]
Thanks for your work and replying! I have set the background, but you're right that it also doesn't render in the built in non-chrome browser. Going to look for whatever may cause that. Theme is set for black and works fine on other browsers.
