### ISSUE TITLE
configuration data storage

### ISSUE THREAD

**Issue by 150d** [thanksmister/wallpanel-android#219]
Where does wallpanel store its configuration data (dashboard url, mqtt settings etc?) Is there a settings file that can be edited manually?

Background: One of my wall-mount tablets has problems with its touch screen that make it hard to use a keyboard to enter data. It would be great if I could just push a settings file onto the device instead of having to input options on the device itself.

**Comment by thanksmister** [comment]
The application uses something called SharedPreferences.  This can be accessed, but it's not so easy.  Here is some more information https://stackoverflow.com/questions/23635644/how-can-i-view-the-shared-preferences-file-using-android-studio#:~:text=Open%20the%20device%20monitor%20by,will%20be%20the%20desired%20SharedPreferences.

**Comment by 150d** [comment]
Understood. I will find another way; thanks for the answer.
