### ISSUE TITLE
MQTT error message pops up on almost every interaction with the tablet

### ISSUE THREAD

**Issue by exxamalte** [thanksmister/wallpanel-android#22]
After https://github.com/thanksmister/wallpanel-android/issues/20 has been fixed, now when there is an issue with the MQTT connection, an dialogue box pops up saying "There was an error initializing the MQTT client, please check your settings".
I can click "OK" and the message disappears, but almost every interaction with the browser (tap, scroll, pulling up the main Android menu, camera motion detection) brings the error message back up on the screen.

On a related note: I have no idea why the app loses the MQTT connection every couple of days, and why it's unable to reconnect. The MQTT broker is up and running, and other devices continue to publish without any problems.

Tablet: Fire HD 8
Version: 0.8.4 Build 2

**Comment by dreed47** [comment]
im getting same (

**Comment by thanksmister** [comment]
I have no idea why your particular device disconnects from the MQTT service every couple of days, its probably related to whatever device settings you have.  Take a look at the device settings to see if its turning off the WiFi or how the device is sleeping.  

If the device sleeps, then the application will stop working.  Most devices have an option to use Daydream, but I am not sure this is an option on the Fire HD. 

I can probably address the issue that if you somehow lose a connection the MQTT client won't reconnect to the broker, but I can not address your device breaking connectivity with the broker.   I will issue an update to reconnect automatically (or try to) if the MQTT connection is broken.

**Comment by thanksmister** [comment]
I rolled out a new update with an attempt to show the dialog but also try to reconnect the MQTT client.  Look for version v0.8.4-beta.3.
