### ISSUE TITLE
Switch to wallpanel using mqtt

### ISSUE THREAD

**Issue by wormiedk** [thanksmister/wallpanel-android#220]
**Is your feature request related to a problem? Please describe.**
I would have expected that the {"relaunch": true} MQTT command would put the wallpanel app in the foreground when submitted

**Describe the solution you'd like**
Possibiliy of switching to wallpanel using an mqtt command

**Describe alternatives you've considered**
Some android program to launch wallpanel after a given timeout

**Comment by thanksmister** [comment]
The command relaunch reloads the same url, it does not relaunch the application.  As the docs say "Relaunches the dashboard from configured launchUrl".  This just refreshes the dashboard. 

The issue with your feature request is that if the app is in the background, it can no longer receive updates.  Wallpanel is an app that must be run in the foreground, like a kiosk application.  If the app is in the background, you may not receive any MQTT commands.
