### ISSUE TITLE
Wallpaper screensaver settings

### ISSUE THREAD

**Issue by tungmeister** [thanksmister/wallpanel-android#223]
Going off the previous feature request I made could you add some settings for the wallpaper screensaver. I'd like the option to increase the frequency that new images are pulled (looking at the commits it's currently 15 minutes?)
I'd also like the option to display a clock in the bottom left-hand corner over the image, similar to the photo frame on the nexus hub?

**Comment by thanksmister** [comment]
This will be included in the next update.
