### ISSUE TITLE
WallPanel seems to struggle with Live Camera cards from HASS?

### ISSUE THREAD

**Issue by Flight777** [thanksmister/wallpanel-android#224]
**Describe the bug**
I've 4 camera's set-up which have live cards running in HASS. Loading these up in WallPanel however, is very problematic. Often some don't get displayed (either white or just blank) or it slows the whole app done. Opening this same dashboard with Chrome on the tablet works very well without any performance issues.

**Expected behavior**
No slow-down/lag in the whole app for extended periods of time and proper display of the dashboard.

**Screenshots**
Dashboard as described:
![image](https://user-images.githubusercontent.com/5236143/100659061-587e3b00-3350-11eb-9f85-458c4c773d64.png)

**Smartphone (please complete the following information):**
 - Device: Galaxy Tab A7 10.4 (2020)
 - OS: Android 10

**Comment by thanksmister** [comment]
I think there is an option to use hardware acceleration some place in the settings, under camera?   Other than that, WallPanel only loads a web page, it does not interact with the web page loaded.  There is nothing than can be done to improve the viewing your cameras other than use some other HTML page.  Have you tried something other than Lovelace?

**Comment by Flight777** [comment]
Haha you are super fast 👍 

You mean in WallPanel right? Yes that is on, but still the same issue. Again, same tablet but with Chrome works perfect, it loads up in a pinch.

It seems WallPanel has issues with opening/loading streams that Home Assistant is generating somehow? The whole apps also takes a huge performance hit after trying to load that page.

Another test I did, is first open the dashboard in Chrome, then refresh WallPanel which also seems to help WallPanel for unknown reason to at least display the streams correctly?

If I can do any further troubleshooting, I'm happy to take your guidance :)

**Comment by thanksmister** [comment]
This has nothing to do with Chrome, Android applications use something called the WebView component (you can look in Google Play for updates). This does not render the same as Chrome, it just uses a subset of Chromes ability.   The issue is that Lovelace has become complex and therefore requires something like a native browser to render its pages.   I suggest you try to have one stream per tab or use something like TileBoard.  There is nothing I can do to address this issue.
