### ISSUE TITLE
How to disable browsers cache?

### ISSUE THREAD

**Issue by Gooman-rus** [thanksmister/wallpanel-android#225]
Is it possible to disable Wallpanel browsers cache? 
I need this because I use dynamically defined icons and images on my page. Also I use automation on the HomeAssistant in order to update Wallpanel page every 1 hour. 
But pretty often images are cached and only manual page refresh (using swipe down on the tablet screen) can update these images.

**Comment by thanksmister** [comment]
You can clear the cache using a command called clearCache.  Check the documentation https://github.com/thanksmister/wallpanel-android#mqtt-and-http-commands.

**Comment by Gooman-rus** [comment]
I use this POST request body to the wallpanel:
`{"relaunch": true, "reload": true, "clearCache": true}`

but nothing happens: dynamically defined images (via JavaScript) are not changing. At the same time I can manually refresh wallpanel's page using swipe down on the screen and images will be update. What am I doing wrong?

**Comment by thanksmister** [comment]
You are probably just not formatting the request properly.   You can test this in Home Assistant under the MQTT integration, there is a testing tool to send and listen to MQTT topics.

**Comment by Gooman-rus** [comment]
You saying that I should test HTTP POST request using MQTT?

**Comment by thanksmister** [comment]
I assumed you were using MQTT.  I don't know of an issue with HTTP POST commands not working.

**Comment by Gooman-rus** [comment]
It appears to be that cache clearing and relaunch/reload are working if the screen is on. Is it like it should be?

**Comment by thanksmister** [comment]
If it only works while the screen is on, then it sounds as though you are losing your connection when the device sleeps, either the wifi is disconnected or the app is in the background.   If the device screen is off, this means the app is probably not connected.  You should always run the app using either the Android screensaver or the application screensaver, but not let the device lock or sleep.

**Comment by Gooman-rus** [comment]
How I can run the app as an Android screensaver? Is it possible to run the app as a screensaver but with screen turned off?

**Comment by thanksmister** [comment]
No, you run the app using Daydream as your screensaver or you use the app's built-in screensaver feature.   You cannot turn off the screen if you want to stay connected to the server, turning off the screen backgrounds the application so it no longer receives updates.  This app was built to be a full-screen application which runs on a dedicated device.

**Comment by Gooman-rus** [comment]
I use logic to turn on and turn off the screen if the motion is detected. So I need the screen to be off sometimes. I have been found the hack in my case in order to get the screen fully refreshed with cache clearing:

1. Turn on the screen using `wake` command.
2. Reload/refresh and clear cache.
3. Turn off the screen.

Thank you.

**Comment by thanksmister** [comment]
If the screen is off, you lose connectivity with the server and it stops functioning.   If your screen is off, you won't receive a wake command because it won't be receiving any commands.  This is not an option we will be adding either. The application is meant to run fullscreen on a dedicated device with a screensaver, either DayDream or the built in screensaver.  If you use DayDream it dims the screen, the built-in screensaver also has a dimming option.
