### ISSUE TITLE
Camera motion detection stops working after a few days

### ISSUE THREAD

**Issue by bigcookie** [thanksmister/wallpanel-android#226]
**Describe the bug**
I use Wallpanel to display my Home Assistant webpage. I use the apps clock screensaver and the camera motion detection to wake it up. All works fine, but after 3+ days, motion detection stops working reliably (on a Lenovo Tab M10HD TB-X505F). I can fix this by hitting the "back" button to open settings and then simply clicking on "Dashboard" on the top right to get back to my webpage.
I use Wallpanel in Kiosk mode in Android (pin app), so that you cannot push it to background easily. 

**To Reproduce**
1. Install Wallpanel
2. Create dashboard url and save it
3. Use following settings (I try to list things which might be different from default, but not list all)
- Open On Device Boot = enabled
- Show Browser activity = enabled
- Browser Refresh = enabled
- Hardware acceleration = enabled
- Screen brightness = enabled
- Capture brightness value (I used it once)
- Clock screen saver = enabled
- Start screensaver = after 2 minutes of inactivity
- Dim Screen = by 50% when screensaver is active
- Camera settings
-- Camer enabled = enabled
-- Selected camera = Front (1440x1080)
-- Camera FPS = 10
-- Motion detection
--- Motion detection enabled = enabled 
--- Wakes screen = enabled
--- Motion reset time = 30
--- MAx Leniency = 3
--- Minimum Luma = 100
Optional: 3. Enabled "App pinning/kiosk mode" in android
Optional: 4. Pin Wallpanel to foreground
5. Click on dashboard to show your URL
6. Test screensaver, dimming and motion based waking up (works)
7. wait 3+ days
8. Screensaver is shown, clock still moves on the screen, but camera motion detection based setup is not working. Tap on the screen still wakes everything up. Webpage is refreshed - bascially all works as expected except camera based motion detection

I tested also without app pinning. Issue is still there.

**Expected behavior**
Motion detection should still work, waking the app up when in screensaver mode

**Screenshots**
n.a.

**Smartphone (please complete the following information):**
- Lenovo Tab M10HD TB-X505F
- Android 9

**Additional context**
I tried to make sure that it is really bright to wake up the app. I used all lights in the aisle or a flashlight -to check if this issue is connected to minimum lumina. But this didnt work.
So for now, I simply hit "back" and then "dashboard" again and it works for some days.

**Comment by thanksmister** [comment]
Sounds like the camera encountered some error and has stopped working.   Going into the settings stops the camera and then when you return to the app, it starts again.    I found an exception in the crash reports for your device and others like it, it seems to be failing to produce a bitmap image from the camera at some point, so it stops working.   This is the crash report:

```
java.lang.RuntimeException: 
  at android.view.DisplayListCanvas.throwIfCannotDraw (DisplayListCanvas.java:229)
  at android.view.RecordingCanvas.drawBitmap (RecordingCanvas.java:98)
  at android.graphics.drawable.BitmapDrawable.draw (BitmapDrawable.java:545)
  at com.squareup.picasso.PicassoDrawable.draw (PicassoDrawable.java:109)
  at android.widget.ImageView.onDraw (ImageView.java:1360)
  at android.view.View.draw (View.java:20211)
  at android.view.View.updateDisplayListIfDirty (View.java:19086)
  at android.view.View.draw (View.java:19939)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4333)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4112)
  at android.view.View.draw (View.java:20214)
  at android.view.View.updateDisplayListIfDirty (View.java:19086)
  at android.view.View.draw (View.java:19939)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4333)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4112)
  at android.view.View.updateDisplayListIfDirty (View.java:19077)
  at android.view.View.draw (View.java:19939)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4333)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4112)
  at android.view.View.updateDisplayListIfDirty (View.java:19077)
  at android.view.View.draw (View.java:19939)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4333)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4112)
  at android.view.View.draw (View.java:20214)
  at com.android.internal.policy.DecorView.draw (DecorView.java:780)
  at android.view.View.updateDisplayListIfDirty (View.java:19086)
  at android.view.ThreadedRenderer.updateViewTreeDisplayList (ThreadedRenderer.java:686)
  at android.view.ThreadedRenderer.updateRootDisplayList (ThreadedRenderer.java:692)
  at android.view.ThreadedRenderer.draw (ThreadedRenderer.java:801)
  at android.view.ViewRootImpl.draw (ViewRootImpl.java:3327)
  at android.view.ViewRootImpl.performDraw (ViewRootImpl.java:3124)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2493)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1468)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:7208)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1012)
  at android.view.Choreographer.doCallbacks (Choreographer.java:823)
  at android.view.Choreographer.doFrame (Choreographer.java:758)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:998)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:6859)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)
```

**Comment by bigcookie** [comment]
I am not running the image screensaver. I think the device has some issues with screensaver and according power settings. I tried tasker and motion detector prior and received some camera errors (stopped working), but on much much higher frequency.  The device has no real screensaver, but an suspend mode instead, which I had to use with tasker.

So yes, the camera stopped working might be a good cause. If there is a check on this and automatic restart of the camera - would be great.
According to Lenovo the device should get an Android 10 update - but so far this hasnt happend...

Let me know, if I can do anything to help.

**Comment by thanksmister** [comment]
We have a command the restarts or stops the camera, but I have had some user's say this does not work.  There is nothing that tells us if the camera is not working, it only publishes over MQTT when motion is detected.  I don't know how we would know the camera stopped from that.  You could send a MQTT command ever 3 days to start the camera?

**Comment by bigcookie** [comment]
Yes, I can send an MQTT command every hour/day - whatever frequency is desired...

**Comment by thanksmister** [comment]
Try sending it daily to see if it does anything.  I am looking to see if I have any reports still.

**Comment by bigcookie** [comment]
Can you let me know the command? I didnt find it here: https://github.com/thanksmister/wallpanel-android
Or do you mean the one to turn on/off streaming? So I would need to turn it on, then off again?

**Comment by thanksmister** [comment]
{"camera": true} | Turns on/off camera streaming, requires camera to be enabled.

You would send false to turn it off, true to turn in on. I think you just want to send true.

**Comment by bigcookie** [comment]
Ok, I thought this would only enable streaming... Automation generated on daily basis. I assume it will only work when camera was stopping prior. So probably I should send that every 5 minutes or so :-)...

I tried my command structure with the brightness command - it works. When I try sending the payload '{"camera": false}', the motion detection still works, which means camera stays on... Is this intended?
(I was thinking of first sending "false", then "true", to get a "fresh" start)

**Comment by thanksmister** [comment]
It does not work to turn off the camera, it might work to turn it on if it stops.

**Comment by bigcookie** [comment]
Hello, I encountered the issue today again and tried to send to /wallpanel/lenovo/command the following
{"camera": false}
{"camera": true}
it didnt work. I checked the connection by sending brightness commands - which worked. So I could tell that the mqtt ccommand was correct.

I couldnt get the camera woken up. The issue seems device specific... Not sure what I can do -probably I need to wait for the Android 10 update. Or you have another idea...

Thanks for your fast and great support already provided!

**Comment by thanksmister** [comment]
I am not sure this issue can be addressed other than not using the camera on that device.

**Comment by bigcookie** [comment]
I assumed so. Consider this topic closed... I will try a few other things... But the device seem to be broken by design... :-(

**Comment by thanksmister** [comment]
Yeah the issues are filled with Lenovo problems, not sure why this particular brand has so many issues.

**Comment by habitoti** [comment]
I have a 2013 Nexus 7 and it has the exact same behavior, so not sure whether it‘s device specific. Is there any way to just reboot the whole device every night? Either forced remotely, or locally as a Wallpaper feature?

**Comment by bigcookie** [comment]
Hello @habitoti - not sure what helped. I am now sending the camera true command every 5 min via MQTT - it didnt disable/enable the camera, but probably it helps you - worth to try. Additionally Android 10 for my Lenovo pad came out. Since then I had no problems, but this is only a few days now...

**Comment by habitoti** [comment]
The last Android version available for this old Nexus 7 is 6.01. I‘ll give the regular camera:true a shot, sure doesn‘t hurt. Additionally I installed Fast Reboot Pro. It can cleanup the device regularly, e.g. also whenever the screen goes off. Not sure whether this actually helps, but doesn‘t hurt either ;-)

**Comment by daemongloom** [comment]
The same happens for my Samsung Galaxy Tab 8.9 (P7300). So it's definitely not vendor-specific.

**Comment by bigcookie** [comment]
New update from my side: Android 10 actually didnt solve the problem, it got a bit worse (camera stops working more quickly).
My solution:
As I use the tablet for monitoring my home, I dont need it constantly at night. I used the feature to turn off and on the tablet at specific times, then I used Tasker to launch "Wallpanel" after start when Wifi is connected. Wallpanel handles for me screensaving, motion detection and shows my webpage for home automation.
I hope this will help as the camera normally is stable for at least a day...

Probably this is worth to try - depending on your use case.

**Comment by thanksmister** [comment]
The topic is expanding past the original posters issue.  The camera running continuously on most device can lead to memory issues or the app getting garbage collected (stops running).   I have no way to improve this other than suggest not to use the camera.  We do have an issue with the camera not being able to stop or start, but there is no solution as the camera feature is used in many ways, face detection, qr code reading, motion detection, and MJPEG streaming.   Stopping the camera means stopping all those features and they do not restart without app restart.   Until that is sorted, there may be no resolution to this issue.

**Comment by thanksmister** [comment]
We have introduced a new approach to reduce CPU/Battery consumption by capturing and processing images based on FPS settings in the camera settings of the application.  Lower the FPS value to reduce the amount of images captured, this will lower your CPU usage and increase battery.   The other option is to monitor your device's battery and charging types (battery, plugged) using the MQTT sensor publishing.  You can then remotely enable/disable the camera using MQTT or HTTP commands as needed.

**Comment by thanksmister** [comment]
My other comment is that on some devices, you just cannot run camera features and if you are having issues, you should stop using them on that device.  Camera operations are intensive and not suitable to run all the time.
