### ISSUE TITLE
Return to default screen

### ISSUE THREAD

**Issue by qwertyjon** [thanksmister/wallpanel-android#227]
I'm new to the app, but loving it. Is it possible to automatically return to the dashboard web page when the screen saver is dismissed? E.g. user1 walks up and does some stuff and walks away, screensaver comes on, user2 walks up and has the same start screen as user1.

Hope that makes sense.

**Comment by thanksmister** [comment]
I think you are talking about changing the web page url?  If you want to load a specific web url then you would need to use the MQTT command to change it.  It's up to you how to set this up, if the screen wakes, that information is sent to HA as sensor data, so you could use that information to send back a URL to load using the MQTT command based on a timer or some other conditions.

**Comment by thanksmister** [comment]
The web page is not the default application.  If you want to have this, then it would better not to use Alarm Panel, but instead use WallPanel app which renders a web page.  The webpage is merely a convenience so you may control other devices from the alarm panel, but it is not the purpose of the app.
