### ISSUE TITLE
Submit WallPanel to the Amazon Appstore

### ISSUE THREAD

**Issue by pattyland** [thanksmister/wallpanel-android#228]
**Is your feature request related to a problem? Please describe.**
Side loading an APK, especially on Fire OS Devices is time consuming

**Describe the solution you'd like**
Submit WallPanel to the Amazon Appstore: https://wikipedia.org/wiki/Amazon_Appstore

**Describe alternatives you've considered**
Beside side loading I don’t think that there is an alternative

**Additional context**

**Comment by thanksmister** [comment]
Yeah I probably should do that since the the Fire Tablet does seem like a popular choice for tablets.  I have three myself running both the alarm app and wallpanel.   Thanks!

**Comment by pattyland** [comment]
Since this is probably optional: It would also be cool if WallPanel ended up on the Fire TV. Even without touch, displaying it on a TV could be a cool use case.

**Comment by thanksmister** [comment]
I submitted this today, it's up to Amazon to approve it before its available in the store.   @pattyland I am not sure without touch how anyone would be able to configure the application.  I do not have a Fire TV to test, but I do run this on several Fire OS tablets and it works well.

**Comment by pattyland** [comment]
That was fast, thank you!
You can control any non special Android Application on the Fire TV with the remote and the on screen keyboard. I guess it like using accessibility tools or a phone? I made a few photos from my TV for you:
1. Configuring the URL
1. Configured backend
1. Home Assistant Login with trusted network provider. I've seems to have some problems with that, but that's not related to WallPanel

![IMG_3312](https://user-images.githubusercontent.com/838758/103821044-b7c91c80-506d-11eb-98a5-145cd7bc5733.jpg)
![IMG_3313](https://user-images.githubusercontent.com/838758/103821054-bb5ca380-506d-11eb-9b43-f801c71c347b.jpg)
![IMG_3314](https://user-images.githubusercontent.com/838758/103821057-bc8dd080-506d-11eb-8677-11b10bc9474a.jpg)

**Comment by thanksmister** [comment]
So it works now?

**Comment by pattyland** [comment]
I sideloaded the App. I don't see the app in the Amazon App Store if that was your question.

**Comment by thanksmister** [comment]
Yeah, still waiting for approval, but so glad to know this should work Fire TV

**Comment by thanksmister** [comment]
This should be published now on the Amazon Appstore, just search for WallPanel

**Comment by pattyland** [comment]
Looking good: https://www.amazon.com/dp/B08S8XZ7LN/

**Comment by pattyland** [comment]
> Looking good: https://www.amazon.com/dp/B08S8XZ7LN/

(At the moment the installation on Fire TV devices is not allowed)

**Comment by thanksmister** [comment]
@pattyland not allowed?  Has this changed, why would they put into the app store if its not allowed?

**Comment by pattyland** [comment]
Up to now, I have had more experience with the Apple AppStore, where as a developer I could set whether my app would work on cell phones, tablets, TVs or watches. Are there no such options on Amazon? At the moment, the app is only shown as compatible with very few devices, among others not with the Fire TV:

![Screenshot 2021-01-18 163301](https://user-images.githubusercontent.com/838758/104935355-6abd4280-59ab-11eb-80d4-f57baf47ff8d.jpg)

**Comment by thanksmister** [comment]
This might entirely be up to the version of Android and the libraries it shows.   I can side-load the app without issue, but not sure what criteria it's using to exclude/include devices in app distribution.

**Comment by thanksmister** [comment]
<img width="1220" alt="Screen Shot 2021-01-18 at 1 32 34 PM" src="https://user-images.githubusercontent.com/142340/104941288-a21ef580-5991-11eb-98e3-f5bbb078a0e9.png">

These are the options for app distribution, there are no options to add/remove devices.

**Comment by thanksmister** [comment]
Supported devices list:

<img width="1141" alt="Screen Shot 2021-01-18 at 1 34 41 PM" src="https://user-images.githubusercontent.com/142340/104941510-ed390880-5991-11eb-8558-823f8cd0ad54.png">

**Comment by thanksmister** [comment]
There is no support for Fire TV unless I modify the app.

<img width="1083" alt="Screen Shot 2021-01-18 at 1 35 26 PM" src="https://user-images.githubusercontent.com/142340/104941599-093caa00-5992-11eb-9579-f40faaf58916.png">

**Comment by clyra** [comment]
+1 for fire tv! I use to use wallpanel with hadashboard on my fire tablets. One cool feature of wallpanel is that I can change the url/dashboard using MQTT, so even without support for the touch and remote (which isnt the case) it still very useful for the fire tv!

@pattyland how did you "sideloaded" it?

**Comment by thanksmister** [comment]
Not sure yet how to make this compatible for Fire TV, still investigating.   @clyra you can side load this by going to the release section of this project and downloading the APK file, then open that file to install.  Amazon devices let you install applications from the APK.

**Comment by clyra** [comment]
Got it! It was easier than i thought with adb tool. so for so good. working beautifully. Thanks!
