### ISSUE TITLE
Performance hit while using WebView - consider alternatives?

### ISSUE THREAD

**Issue by jkaberg** [thanksmister/wallpanel-android#229]
**Is your feature request related to a problem? Please describe.**
Using the  very latest of Wallpanel in combination with Home Assistant on a Lenovo Tab M10 HD (with Android 10) results in awfull slugish performance. From my tests Chrome and Firefox works just fine with Home Assistant on the very same tablet, so I assume this to be an WebView issue

**Describe the solution you'd like**
Change WebView with something modern and better? Atleast an option todo so, and for legacy devices keep WebView?

**Describe alternatives you've considered**
[GeckoView ](https://mozilla.github.io/geckoview/) or something else?

**Comment by thanksmister** [comment]
I don't think GeckoView is an option given how out of date that library is with the rest of Android.  I have tried it before but it restrains the version of Android you can support to older versions only.   You really have no choice, you can turn on hardware acceleration option in the settings or use a dashbaord other than lovelace for HA, something like Tileboard would be better.    Have you also looked for a WebView updated in Google Play, it's possible there is a new version.

**Comment by spudje** [comment]
I have similar experience on the little brother tablet Lenovo Tab M8 :) It became almost unusable. I also noticed the app won't stay in front of the lock screen anymore. This used to work, even without "pinning" the app.

**Comment by thanksmister** [comment]
There are not real viable alternatives to using WebView.   There are options to install the open source version of WebView which may give users some benefits, especially those running custom OS from manufacturers.   But there is no other solution I can offer.  Closing this as won't fix.

**Comment by LeoLTM** [comment]
I have a similar problem: 
Old tablet (Android 4.4), no way to update WebView, no custom ROM available. 
The lovelace login screen won't show in the WallPanel app, but Opera and Firefox do just fine (they just don't have WallPanels functionality).

So GeckoView is really no option for you? I think, it's built into Firefox Klar afaik, and this works very well. 
I don't know what Opera uses but that'd be another one to consider.
