### ISSUE TITLE
Camera name, date/time on stream

### ISSUE THREAD

**Issue by seanmurphy1661** [thanksmister/wallpanel-android#243]
This is a request for additional information on the Camera Stream.

Minimum feature would show the name of the device in one corner of the video and the date/time in another. The attached MotionEyeOS screenshot shows an example. 

Full feature set could include placement options, named camera. 
 
![Screen Shot 2021-02-16 at 10 15 01 AM](https://user-images.githubusercontent.com/4969079/108082520-2ff90980-7040-11eb-9b33-25804f16509c.png)

**Comment by thanksmister** [comment]
WallPanel only display a webpage, you have to handle this in Home Assistant.  WallPanel does not interact with the web page directly.
