### ISSUE TITLE
Motion detection not working in Android 11?

### ISSUE THREAD

**Issue by sepodele** [thanksmister/wallpanel-android#245]
My Android 11 device is not detecting motion and I assume it's because camera permissions can't be set to "Always" to work when screen is off.

https://stackoverflow.com/questions/64306994/access-microphone-camera-in-background-in-android-11

**Comment by thanksmister** [comment]
The application is designed to work when the device is always on, you can use Daydream or the built-in screensaver.  If you let the device sleep, lock the screen, turn off device, the functionality may not work.

**Comment by sepodele** [comment]
Gotcha. Thanks.
