### ISSUE TITLE
v0.9.3-beta.6 not loading webpage, stuck on permission request?

### ISSUE THREAD

**Issue by BoneheadFraggle** [thanksmister/wallpanel-android#248]
**Describe the bug**
When WallPanel loads the webpage for the first time after a reboot, the page is not loaded. 
If I enter Settings, a notification "Camera permission granted" is shown.
If I exit Settings without changing anything, the page is loaded correctly.
I have two identical phones, configured identically, same network, same webpage, same user in HA - but one with v0.9.1-build.0 and one with v0.9.3-beta.6 (to the right)
The one with v0.9.1-build.0 loads the page at startup, v0.9.3-beta.6 does not.

**To Reproduce**
1. Reboot phone
2. Wait for it...
3. Webpage is not loaded (maybe partly since I see a HA blue header?)
4. Enter Settings
5. Exit Settings
6. Webpage is loaded

**Expected behavior**
Webpage should be loaded without entering Settings first

**Screenshots**
https://youtu.be/hWK367eP6Ag

**Smartphone (please complete the following information):**
 - Device: Sony Z3
 - OS: Android 6.0.1
 - Browser Stock browser

**Additional context**
**Phone Config:**
  Screen Standby: 15s

**WallPanel:**
  Open On Device Boot: Yes
  Show Browser Activity: No
  Browser Refresh: No
  HW Acc: No
  Prevent Screen Sleep: No
  Screen Brightness: No
  Blank Screen Saver: No
  Clock Screen Saver: No
  Wallpaper Screen Saver: No
  Start screensaver after.. : 30s
  **Camera Settings:**
    Camera Enabled: Yes
    Motion Detection:
      Motion Detection Enabled: Yes
      Wakes Screen: Yes
      Motion reset: 15s
      Maximum Leniency: 10
      Minimum Luma: 100

**Comment by thanksmister** [comment]
We can't control the webpage and we don't interact with permission requests.  I can reproduce those only when starting the app on device start, seems like some race condition with loading the view and loading the page on start of device.

**Comment by thanksmister** [comment]
Try appending `lovelace/default_view` or whatever dashboard you want to the url.  I think something has changed with the way HA is loading the login page if you just go to the root address, i.e. http://192.168.1.0:8123.

**Comment by thanksmister** [comment]
I think I have addressed this, look for a new beta version shortly

**Comment by BoneheadFraggle** [comment]
I just upgraded the Z3 with v0.9.3-beta.6 in the film to v0.9.3-beta.7 and the webpage loads as expected after restart, so I can confirm you already found what was causing the error. Nice work!

A few other things seems to have been introduced, like it seems I can't set WallPanel as launcher any more and I get a little inconsistent behavior when I press phone's back button vs. the back arrow in the app, but I guess that is caused by troubleshooting. Please ping me if I should raise an issue on that.

**Comment by thanksmister** [comment]
I fixed the back button put out a new updated.   I don't see issue with setting the app as the home launcher, try going into the device settings then applications, should have option there to set WallPanel as launcher/home app.  There is a button in the settings to "reset" the home app as well.

**Comment by BoneheadFraggle** [comment]
In v0.9.3-beta.7 the option "Clear Home Screen" is there, but not the Set as launcher as a have seen previously.
Will try new new version!

**Comment by BoneheadFraggle** [comment]
I had to check again for the "set as home app/launcher", but I can't find it. 
Just cleared the app data to see if that changed things, but no.
These pictures are from v0.9.3-beta.8.

![1](https://user-images.githubusercontent.com/2287810/110219095-6bf3f180-7ebd-11eb-9488-f6cdf1c18a1a.png)
![2](https://user-images.githubusercontent.com/2287810/110219097-6e564b80-7ebd-11eb-965b-7d511c19c7ff.png)
![3](https://user-images.githubusercontent.com/2287810/110219098-70b8a580-7ebd-11eb-98ee-cd22bc150c2c.png)
![4](https://user-images.githubusercontent.com/2287810/110219100-731aff80-7ebd-11eb-95d6-b8cb72f5e04d.png)

**Comment by thanksmister** [comment]
That’s an Android device feature so it’s in the device settings under the application, you won’t find it in the wall panel app, you have to set the device home app from the device settings if the launcher prompt doesn’t already show.  Usually the app will ask.

**Comment by BoneheadFraggle** [comment]
Ok! Maybe consider adding a small hint in the config page then to make it easier to find and use.
And maybe even disable the "Start On Device Boot" option when it is set as Home App since it is a bit redundant then.

Anyway, love the Home app feature and from my perspective the app works great again. Thanks a lot!

**Comment by thanksmister** [comment]
Also each device has its own support for setting the launcher or home app.  Usually the app will ask but sometimes you set it manually, and some devices some have option.

**Comment by thanksmister** [comment]
Thy thin is you can’t know if that divine has set your app as a home app, it’s completely outside the app.   Also setting a home app is usually automatic, it prompts you when launching the app on most devices.  There is not much I can do to change how and when it’s implemented or know if I should turn off on device boot.   The only thing I can do is clear the devices home setting which is why there is a setting for that.
