### ISSUE TITLE
Launching an intent from the webpage

### ISSUE THREAD

**Issue by neuroverflow** [thanksmister/wallpanel-android#249]
Offer the possibility to run an intent / launch a package using a JS function catched by the kiosk.
Fully Kiosk browser does that. The goal is to integrate a button Netflix for example in your Home Assistant dashboard that starts the application on the tablet.
Thank you! (and good work!)

**Comment by thanksmister** [comment]
It’s possible if you add some interface to the Android WebView.  If you have more information on how it works please add to this issue.

**Comment by neuroverflow** [comment]
Well if I had to do it I would implement it this way; http://rapidprogrammer.com/android-how-to-call-native-java-methods-from-webview-javascript
The problem is how to execute it from the home assistant, with fully kiosk browser you need to activate an option in the settings of the software to authorize JS execution 

Below is the code I use with FKB in HA:

entities:
- icon: 'mdi:web'
    name: Netflix
    type: weblink
    url: 'javascript:fully.startApplication(''com.netflix.mediaclient'')'
type: entities

**Comment by thanksmister** [comment]
That is a JavaScript interface, so you would add one to the WebView custom for WallPanel.

**Comment by TheAlphaLaw** [comment]
Looks like this feature was added in latest beta release. It does not appear to function though. Receiving "Unknown URL Scheme". 

Testing with  
`"{"url": intent:#Intent;launchFlags=0x10000000;component=com.amazon.avod/com.amazon.avod.client.activity.HomeScreenActivity"} `

Receiving an "Unknown URL Scheme Error". Is this an error on my part? Same command works on FKB.

**Comment by thanksmister** [comment]
@neuroverflow helped implement this feature, maybe he can help out testing the issue.  I am using this code:

```
 override fun shouldOverrideUrlLoading(view: WebView, url: String): Boolean {
                // open intent urls with native application
                isRedirect = true
                if (url.startsWith("intent:")) {
                    val separated = url.split(";").toTypedArray()
                    separated[0] // this will contain "intent:#Intent"
                    separated[1] // this will contain "launch flag"
                    separated[2] // this will contain "component"
                    separated[3] // this will contain "end"
                    val component = separated[2].removePrefix("component=")
                    val classname = component.split("/").toTypedArray()
                    val pkgName = classname[0] // this will set the packageName:
                    val clsName = classname[1] // this will set the className:
                    val intent = Intent()
                    intent.action = Intent.ACTION_VIEW
                    intent.setClassName(pkgName, clsName)
                    startActivity(intent)
                    return true
                } else {
                    view.loadUrl(url)
                    return true
                }
            }

```

**Comment by thanksmister** [comment]
I will make this a separate method and create some tests to make sure we are parsing the URL correctly.

**Comment by thanksmister** [comment]
Seems to me you want your url formatted like this:

`"intent:#Intent;launchFlags=0x10000000;component=com.amazon.avod/.client.activity.HomeScreenActivity;end"`

**Comment by TheAlphaLaw** [comment]
> Seems to me you want your url formatted like this:
> 
> `"intent:#Intent;launchFlags=0x10000000;component=com.amazon.avod/.client.activity.HomeScreenActivity;end"`

I may be doing something incorrectly. Can you verify that my payload is correct, please?

`{"url": "intent:#Intent;launchFlags=0x10000000;component=com.amazon.avod/.client.activity.HomeScreenActivity;end"}`

I am receiving the following error. "net::ERR_UNKOWN_URL_SCHEME".

Testing with an external webpage does work `{"url": "https://google.com"}`

**Comment by pawelnguyen** [comment]
I'm also trying to use this feature. No luck so far with publishing a `url` via mqtt, I'm getting same `ERR_UNKNOWN_URL_SCHEME` error.

Is it possible that it doesn't work because `shouldOverrideUrlLoading (WebView view, String url)` was deprecated?
https://developer.android.com/reference/android/webkit/WebViewClient#shouldOverrideUrlLoading(android.webkit.WebView,%20java.lang.String)

**Comment by thanksmister** [comment]
I am still testing, this feature is still under development.  I will post a new app update when I get everything working properly.  Thanks.

**Comment by thanksmister** [comment]
Test version URL https://github.com/thanksmister/wallpanel-android/releases/tag/v0.9.4.3

**Comment by TheAlphaLaw** [comment]
> Test version URL https://github.com/thanksmister/wallpanel-android/releases/tag/v0.9.4.3

Working great now, love it! 

Is it possible to set a timer to return to wallpanel after launching the new app? I know this can be done with a macro app if not. Thanks!

**Comment by thanksmister** [comment]
I don' think there is a reliable way to have WallPanel return to itself after launching another application.   You might try sending an intent to launch the WallPanel app, maybe magically it would work.  I am closing this ticket.

**Comment by pawelnguyen** [comment]
thanks a lot @thanksmister, latest release works great :)

To anyone trying to launch Spotify - this worked for me:
```
service: mqtt.publish
data:
  topic: wallpanel/mywallpanel/command
  payload: '{"url": "intent:#Intent;launchFlags=0x10000000;component=com.spotify.music/com.spotify.music.MainActivity;end"}'
```

Initially I used intent schema url from old readme link https://support.actiontiles.com/en/communities/12/topics/1255-open-android-app-or-app-activity-via-url-formatted-shortcut and it did not successfully launch Spotify, instead it restarted Wallpanel in my case.

Also in my case sending an intent to launch WallPanel app didn't work after it is switched to another app.

Thanks again 👍

**Comment by pawelnguyen** [comment]
@TheAlphaLaw I've set up this app that auto opens WallPanel every 1h, hopefully it'll work fine enough for me
https://play.google.com/store/apps/details?id=com.argonremote.openappscheduler&hl=en_US&gl=US
