### ISSUE TITLE
Invalid Code

### ISSUE THREAD

**Issue by costa-alex** [thanksmister/wallpanel-android#255]
Hi,
just updated to the latest version but now I can't enter the settings menu. 

The floating icon for the settings asks me a code, I enter the default one (1234) but it always says "code is invalid, please try again"
I've already uninstalled and did a fresh install but the issue remains.

Thanks

**Comment by thanksmister** [comment]
Try with the updated release, I just published it.

**Comment by costa-alex** [comment]
Thanks, it's fixed on version v0.9.4-beta.2.
