### ISSUE TITLE
Wireless charge support in MQTT/API

### ISSUE THREAD

**Issue by gsemet** [thanksmister/wallpanel-android#257]
**Is your feature request related to a problem? Please describe.**
When Fire HD 8 is wirelessly charging, the state in MQTT is reported as
```
"charging":true,"acPlugged":false,"usbPlugged":false
```

**Describe the solution you'd like**
I would expect `acPlugged` to be `true` or a new item `qiPlugged` to be turned `true`.

**Comment by thanksmister** [comment]
The application reports what the system reports, so this would be an issue with Fire OS and not the application.  We use Android SDK to get that from the system.
