### ISSUE TITLE
Only auto-dim when wallpanel is active

### ISSUE THREAD

**Issue by gsemet** [thanksmister/wallpanel-android#258]
**Describe the bug**
When auto-dim is enabled after for example 30s, we expect to dim only when the main panel is active, not when it is in the settings page or on another application.

**To Reproduce**
1. Set screensaver to 30s and set dim to 99%.
2. Click on settings
3. Wait 30 seconds
4. See the screen being dimmed while you are trying to change a setting

**Expected behavior**
Start and stop the screensaver timer only when in the main sequence. Kill the screensaver timer when loosing focus (application goes in background) or when entering the settings section

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thanksmister** [comment]
The entire app dims for night mode, that is the behavior.
