### ISSUE TITLE
Could we make the Settings access through a software / the back button optional?

### ISSUE THREAD

**Issue by rahaaas** [thanksmister/wallpanel-android#259]
My Home Assistant dashboards are going to need re-organising to make way for the new Settings button, with a risk of users accidentally pressing it. Could we please make the back button / software button an optional choice?

**Comment by thanksmister** [comment]
No it’s not possible.  You have 4 locations for the settings button and can make  it invisible.  Are you certain you can’t make it work?

**Comment by thanksmister** [comment]
In a kiosk app you have no access to the back buttons.  This is also the issue when using the application on a Fire TV.  This is why the button exists and also why there is a code to unlock the settings.  There should be a way to get to the settings without a back button.

**Comment by rahaaas** [comment]
I appreciate your response, and of course it’s your (not-to-be-taken-for-granted-free) application, but I’ve already had two people trigger it accidentally, and then freak out when confronted with the code screen. 

I take your points about the true kiosk application not having access to back buttons, but I do think there could be a more elegant way, rather than just a button. Perhaps a swipe or similar could be considered? 

Thanks again.

**Comment by thanksmister** [comment]
I understand that the new way isn’t working for your particular users but I think this method does work for most use cases.  Have you tried moving the button to a corner of the app and also making in invisible?  

That has the same exact effect as users accidentally swiping in the screen or hitting the back button.  Wherever we put the button or add the behavior it’s going to have the same issues, some users are going to find it.  That’s why it’s code protected now.  

There may be others ways to do this but for now this is the best implementation and I do believe it’s better with the majority of users.  Swiping has its own issues as someone will have a web page that’s also swipes, like Tileboard and then they have issues.

My thought is to eventually have a way that’s the web page can call a JavaScript method to open the settings, then there is no need to have a button.  You might want to just run the HA application in fullscreen mode as it has the feature already to open the settings from the menu on the HA dashboard.

**Comment by clyra** [comment]
Hi,

Coming late to the discussion, but I'm in the same situation of @rahaaas . I use wallpannel with hadasboard+ha, and usually i use all screen space with buttons, so choosing a corner is not that good because there should be a button there already. Since there's a rest/mqtt api, one approach would be letting the user use that api to toggle the setting button visibilty (let the button be visible by default and only allow to  hide by api).

**Comment by thanksmister** [comment]
@clyra that's another approach, then you could use a button to trigger the MQTT command.  Thanks for the suggestion.
