### ISSUE TITLE
languageCode on text to speak 

### ISSUE THREAD

**Issue by pixiandreas** [thanksmister/wallpanel-android#26]
Use languageCode in message.

**Comment by JoHaNMcR** [comment]
this would be so great!

**Comment by andrewjswan** [comment]
That would be great and would probably solve my problem:
In the phone, Google TTS is configured, the language in the default TTS settings is Russian, the language pack is loaded, the required voice is selected, but if I send a command with the Russian text, the phone is silent, if with English it pronounces, if mixed, it pronounces only English phrases.

**Comment by thanksmister** [comment]
This is has been completed https://github.com/thanksmister/wallpanel-android/issues/230
