### ISSUE TITLE
Grandstream phone click to call URI

### ISSUE THREAD

**Issue by samturner3** [thanksmister/wallpanel-android#260]
Hi,
I have home assistant running using wall panel android app on my [grandsteam android GXV3370](http://www.grandstream.com/products/ip-video-telephony/ip-video-phones-android/product/gxv3370). 

I am simply attempting to call a phone number when clicking a button. The button is configured as a URL. Aka click a link in web browser (on desk phone) to initiate call on desk phone (same device).

I have posted this question on grandstream forum but I thought i'd ask here too.

I have tried the http tel link `tel:123`, not working. I get an error about uri scheme. This is an android thing, not sure how to make it work on this phone. Maybe because i’m doing this from within an android app, not the native web browser?

Perhaps this could work using an intent scheme url?

This seems like an android thing but not sure if it’s implemented / how to use to create call on grandstream phone.

Things I have already researched:
This is NOT click to call (click phone number in computer web browser to start call on desk phone)
This is NOT action urls (send action to sip server when phone performs some action)
This is NOT to do with grandstreams’s softphone that runs on android devices. (wave)
This is click link url on the desk phone its self to start a call.

Screenshot of home assistant button example:
<img width="724" alt="Screen Shot 2021-04-08 at 10 08 29 pm" src="https://user-images.githubusercontent.com/14887388/114028728-23fd2b80-98bc-11eb-8104-28586a85bf5b.png">

Posted same question on:
https://community.home-assistant.io/t/wall-panel-android-running-on-grandstream-desk-phone-click-to-call-uri/297336
https://forums.grandstream.com/t/click-to-call-within-android-app-on-desk-phone/46963

**Comment by thanksmister** [comment]
I have the same Grandstream model.  It seems you would need to find the right schema to open the Grandstream phone app.  I believe their are apps that find package and intent of installed apps.  

I know Fully Kiosk has some way to find and assign an app to open.  

This seems possible if we can find the correct intent.  However, opening the app is not the same as making it dial a number.  That I don’t know, seems that the phone app would need to handle a properly formatted intent much like Gmail app can handle starting a new email with the correct intent.

**Comment by thanksmister** [comment]
I am closing this because lack of response from OP.

**Comment by samturner3** [comment]
FYI conversation continued on grandstream forums:

https://forums.grandstream.com/t/click-to-call-within-android-app-on-desk-phone/46963/3
