### ISSUE TITLE
Hard to get wall panel working with Android 11

### ISSUE THREAD

**Issue by etxttul** [thanksmister/wallpanel-android#261]
**Describe the bug**
I'm running wall panel on a raspberry pi 4B with 4Gbyte RAM with a Raspberry pi USB camera.
The software (android) is LineageOS 18.1 - KonstaKANG (Android 11) 
https://konstakang.com/devices/rpi4/
Connected to the Raspberry, I have a touchscreen (BlitzWolf® BW-PCM3 15.6 Inch Touchable FHD 1080P Type C Portable Computer)
The setup works fine with fully kiosk.

When I get it working it works great, but it takes some trick to get it working and when I got it working, I need to use a strict no touch policy. 

In simple words, I can't make the screen wake up on motion from the camera. The camera is working, which I can see both in the camera test and the fact that it work in fully kiosk.

Weirdly, I can get it working by running fully kiosk for a couple of cycles (meaning let the screen saver go off and wake it up with the camera), then switch to wall panel.

However, whenever I go to the settings (from the working state), the wake up on motions stops working and I have to go back to the trick with running fully kiosk for a couple of cycles again, hence the no touch policy :-)

My setup is nice, but odd, in worst case I can live with it as I have a work-around. 

Btw. I have tried to start from scratch a number of times (meaning loading android from scratch)

**To Reproduce**
The wake up on motion detection don't work. If it works it stops working when entering the settings.

**Expected behavior**
I like the screen to wake up on motion from the camera.

**Screenshots**

**Smartphone (please complete the following information):**
raspberry pi 4B with 4Gbyte ram 
Raspberry pi USB camera.
https://www.amazon.se/gp/product/B078Y5N9X2/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1
The software is LineageOS 18.1 - KonstaKANG (Android 11) 
https://konstakang.com/devices/rpi4/
BlitzWolf® BW-PCM3 15.6 Inch Touchable FHD 1080P Type C Portable Computer

**Additional context**

Tjolahopptjolahej
Tobe

**Comment by thanksmister** [comment]
This project runs only on Android, the RPi project has stopped when Google stopped support for Android Things for RPi4.

**Comment by thanksmister** [comment]
It might be you are missing some of the google play libraries and support.   Since this is a custom build, be sure you installed Google Play services as well.

**Comment by thanksmister** [comment]
What I wanting to work on is a version of this application built with Flutter for embedded devices.  However, so far Google has not released any information about using Flutter for RPi.     It would be easy to port the application over and have access to native device pins for motion and screen.  I have no idea about this type of configuration, sounds painful :D.

**Comment by etxttul** [comment]
You are probably right when it comes to google play liberies, I believe I installed the pico version of open_gapps, so for sure not the full version. Android is not the obvious choice for raspberry pi, but I choose it because of the ease of doing kiosk/wall panel (your app)
But as said after fiddling around a bit, I can get it working, so no worries, when working it is stable.
Attaching picture of my installation.

![overview](https://user-images.githubusercontent.com/58366158/114202685-b8689c00-9957-11eb-97f5-aa246f7e7fe4.jpg)

**Comment by etxttul** [comment]
Hi,
I never heard about flutter before. The reason for doing the wall panel on android was that this seems to be the easiest way to do with a screensaver waking up by a camera. Running it on a Raspberry pi is of course a price issue and the fact that I had one at home. (I used run an old Samsung tab, but it was just to old and slow). I have to say that this combination with android and raspberry pi 4 is just on the limit. It is just responsive enough, most of the time  If there was something thinner than android to run wall panel on I believe it would great. I'm just not the guy to tell what OS that would be.  As it is browser based, my completely unqualified guess would be Chromium OS? or Raspberry pi os it self? at least that one is optimized for raspberry.

**Comment by thanksmister** [comment]
If you want to run this on Raspberry Pi, my suggestion would be to just use kiosk mode on RPi with Chromium loading a web page, you would then use MQTT library on same RPi to control the Chromium browser.    Basically you would rebuild the app using MQTT, Chromium, and Python.    Flutter is supposed to compile to RPi or microcontrollers but I have yet to see a working version.  Flutter would run on the device, I am guessing replacing the OS of the device much the way Android Things did when it was supported.

**Comment by etxttul** [comment]
Thanks for the advice, I might consider it as a project for the next long dark Swedish winter, I'm not that tech savy and have quite some to learn before being able to do something like that. The main feature I like with wall panel is the screen saver and the wake up by motion detector, that don't seem to be that easy to do. In the meantime, I bought a fan for the pie and pumped up the frequency from 1.5GHz to 2 GHz (simply done in PI settings in the android). This made it a bit more responsive, not perfect, but better. 

Thanks again
Tobe

**Comment by thanksmister** [comment]
I will put that on my side project list, I had a project previously that used a PRI sensor for waking up the device, this actually works better than using the camera, less intensive.  I have an old touchscreen and RPi3 just waiting for a project.

**Comment by etxttul** [comment]
Let me know how it went and how you did it. I'm curious as my RPI4 4GB on android is just barely responsive enough.

**Comment by thanksmister** [comment]
Will do!!
