### ISSUE TITLE
How do I launch the app? 

### ISSUE THREAD

**Issue by johnwintergm** [thanksmister/wallpanel-android#266]
A stupid question: I want to use it with fire OS.  How do I launch the app.  I see the "settings" page.  But where do I start it?  Thanks

**Comment by thanksmister** [comment]
Just go back from the setting screen, the main view is the app, it renders webpages.  So whatever webpage you have set in the settings renders as the main view of the app.

**Comment by thanksmister** [comment]
I am closing this as OP has not responded.

**Comment by johnwintergm** [comment]
Thanks.  Just now noticed the response.
