### ISSUE TITLE
Displays blank screen with latest version of Grafana

### ISSUE THREAD

**Issue by bwims** [thanksmister/wallpanel-android#267]
**Describe the bug**

**To Reproduce**
1. Go to local raspberry pi server
2. Click on power button
3. Scroll down to N/A
4. See error - blank screen

**Expected behavior**

I had the system configured to display a Grafana dashboard in kiosk mode which worked fine until Grafana was updated.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Nook HD
 - OS: Android Cyanogenmod 4.4.4
 - Browser stock browser, kiwi
 - Version latest available

**Additional context**
I am using a repurposed Android 4.4 system based on cyanogenmod.  The included browser there could not display the dashboard either.

However, I installed the latest Kiwi browser which _can_ display the dashboard.

I have upgraded Wallpanel to the latest version and disabled the cyanogenbod browser, but the wallpanel screen is still blank.

Question:  Does Wallpanel use its own browser or the default browser on the system?

If the former, It may be that the latest version of Grafana is using a feature not supported by your browser.

**Comment by thanksmister** [comment]
This has been posted many times, the Android applications do not use the installed web browsers, they use WebView component to render web pages.  If the website can't be rendered with WebView, then you have a choice to either update WebView or display a less complex web page.   This is not an application issue but an issue with your version of Android OS and WebView.

**Comment by bwims** [comment]
What an unhelpful comment.  I don't have webview installed, so it must not have been around for 4.4, it doesn't even appear in the google play list.  As for "many times", I searched for all issues including the word "browser", so the problems must have been more esoteric.

Clearly your app is useless.  Never mind.  Kiwi works fine for my purposes.  UNINSTALLED.

**Comment by thanksmister** [comment]
WebView is part of the Android SDK and as I explained it’s what Android applications use to display web pages.  Every android app has WebView.  

Whatever wen version you have on your device has nothing to do with the apps ability to display web pages.  Before posting an issue please take the time to first search for the issue. This has been answered many times.  

If all you want to do now is just disparage the app instead of trying to listen then I do not think I care to assist you further.
