### ISSUE TITLE
Webview component not installed on Asus ZenPad 3 8.0 with Android 8

### ISSUE THREAD

**Issue by rafuz** [thanksmister/wallpanel-android#27]
Describe the bug:
Cannot view web pages in Wallpanel on specific Android device

 - Device: Asus ZenPad 3 8.0
 - OS: Android 8

Error showing is that the Webview component is not installed.
Webview is installed but disabled by default on this device. It cannot be enabled without root.

**Comment by thanksmister** [comment]
Can you check which version of the application you have under settings and then about.  I pushed out Teo updates yesterday and one had a bug.

**Comment by rafuz** [comment]
I will check as soon ad I can

**Comment by thanksmister** [comment]
The latest release is v0.8.4-beta.6.

**Comment by thanksmister** [comment]
I have created a legacy version of wallpanel which uses Crosswalk for rendering web pages: https://github.com/thanksmister/wallpanel-android-legacy.

**Comment by rafuz** [comment]
I have updated the app tonight and it is fine now.
