### ISSUE TITLE
Delayed refresh/reload of web page on startup

### ISSUE THREAD

**Issue by mrthosi** [thanksmister/wallpanel-android#270]
When I set "open on device boot" and default home app too, two loading happens at startup. It is enough time to the second instance to load the (homeassinstant) web page successfully, but sometimes I have issues when two instances are loaded (eg. motion sensor doesn't work).
When I disable "open on device boot", and tablet is restarted, the home screen is loaded (too quickly), but WIFI is still not connected (yet), so only "web page not available" ("net:: ERR_INTERNET_DISCONNECTED") happens.

Maybe a configurable startup delay would be great, or checking "internet_disconnected" followed by automatic page reload may solve this problem.

If I not set default home app to WallPanel (but OneUI), just "open on device boot", it works, but most updates cause not loading of the default home app, but asks for choosing one of them (and the page will not be loaded until user input). (Yes, I can disable auto update of applications for a workaround.)

**Comment by thanksmister** [comment]
I don't think you need to use both open on device boot and home screen, if the app is the home screen it will also load when the device restarts.   I think we have another issue some place about handling errors with WiFi disconnect.   The app does not know if you set it as the home screen, so I recommend not setting restart on boot.    

You can add your issue with wifi disconnect to this ticket https://github.com/thanksmister/wallpanel-android/issues/265, that was a bug already filed and seems to fit your issue.   Basically we want to try to handle wifi disconnect issues and reload the page for the user.

**Comment by thanksmister** [comment]
I have added a way for the page to detect if there is a network disconnect and reload.  It can do this also for page load errors.  Please try with version https://github.com/thanksmister/wallpanel-android/releases/tag/v0.9.4.9.
