### ISSUE TITLE
Add http message decoding

### ISSUE THREAD

**Issue by vladik1969** [thanksmister/wallpanel-android#271]
Hello.
Could you add message decoding to the "speak" http function? Now I will not be able to send text in Russian for TTS. Everything works through MQTT. But if MQTT is enabled, the tablet wakes up every 2 minutes.

**Comment by thanksmister** [comment]
We process (decode) http and mqtt messages the same way.  Sending a command using HTTP is the same as sending the command using MQTT.   Perhaps you are not formatting the speak command correctly?

**Comment by vladik1969** [comment]
Thanks for the answer.
If I send Russian text via MQTT, it is pronounced. When sending the same message over HTTP, Russian text does not work, but English words are pronounced.

**Comment by vladik1969** [comment]
I don't see decode function in the code.

**Comment by thanksmister** [comment]
Decode was your term, but in the WallPanelService class we have a method that parses JSON or string's for incoming commands, this is used from HTTP or MQTT:

```
private fun processCommand(commandJson: JSONObject): Boolean {
        Timber.d("processCommand $commandJson")
        try {
            if (commandJson.has(COMMAND_CAMERA)) {
                val enableCamera = commandJson.getBoolean(COMMAND_CAMERA)
                if (!enableCamera) {
                    stopCamera()
                } else if (enableCamera) {
                    restartCamera()
                }
            }
            if (commandJson.has(COMMAND_URL)) {
                browseUrl(commandJson.getString(COMMAND_URL))
            }
            if (commandJson.has(COMMAND_RELAUNCH)) {
                if (commandJson.getBoolean(COMMAND_RELAUNCH)) {
                    browseUrl(configuration.appLaunchUrl)
                }
            }
            if (commandJson.has(COMMAND_WAKE)) {
                if (commandJson.getBoolean(COMMAND_WAKE).or(false)) {
                    val wakeTime = commandJson.optLong(COMMAND_WAKETIME, SCREEN_WAKE_TIME / 1000) * 1000
                    wakeScreenOn(wakeTime)
                } else {
                    wakeScreenOff()
                }
            }
            if (commandJson.has(COMMAND_BRIGHTNESS)) {
                // This will permanently change the screen brightness level
                val brightness = commandJson.getInt(COMMAND_BRIGHTNESS)
                changeScreenBrightness(brightness)
            }
            if (commandJson.has(COMMAND_RELOAD)) {
                if (commandJson.getBoolean(COMMAND_RELOAD)) {
                    reloadPage()
                }
            }
            if (commandJson.has(COMMAND_CLEAR_CACHE)) {
                if (commandJson.getBoolean(COMMAND_CLEAR_CACHE)) {
                    clearBrowserCache()
                }
            }
            if (commandJson.has(COMMAND_EVAL)) {
                evalJavascript(commandJson.getString(COMMAND_EVAL))
            }
            if (commandJson.has(COMMAND_AUDIO)) {
                playAudio(commandJson.getString(COMMAND_AUDIO))
            }
            if (commandJson.has(COMMAND_SPEAK)) {
                speakMessage(commandJson.getString(COMMAND_SPEAK))
            }
            if (commandJson.has(COMMAND_SETTINGS)) {
                openSettings()
            }
            if (commandJson.has(COMMAND_VOLUME)) {
                setVolume((commandJson.getInt(COMMAND_VOLUME).toFloat() / 100))
            }
        } catch (ex: JSONException) {
            Timber.e("Invalid JSON passed as a command: " + commandJson.toString())
            return false
        }

        return true
    }
```

**Comment by vladik1969** [comment]
I mean encoding-decoding non-ASCII messages over the Internet (URLEncoder.encode - URLDecoder.decode)

**Comment by vladik1969** [comment]
If you do not encode Russian text, then the mail request will contain only questions, not Russian characters. But if you encode the text, then the post request will reach your program, but will not be decoded.

**Comment by thanksmister** [comment]
Oh, you mean decoding the speak message because it's in Russian?   It is confusing, because you mentioned MQTT vs HTTP, this would be same issue for both, neither one of them decode unless it's automatically done.   Can you send me a valid sample of the speak command in Russian and I can test it to see the issue.

**Comment by thanksmister** [comment]
> If you do not encode Russian text, then the mail request will contain only questions, not Russian characters. But if you encode the text, then the post request will reach your program, but will not be decoded.

I think I understand.  Please provide an example for me to test and I will see if I can fix this.

**Comment by vladik1969** [comment]
This is not required for MQTT as the protocol works fine with UTF-8. 
For example, {"speak": "Привет world"}. Pronounced only "world".

**Comment by thanksmister** [comment]
> This is not required for MQTT as the protocol works fine with UTF-8.
> For example, {"speak": "Привет world"}. Pronounced only "world".

That makes sense.  I will try to get HTTP working.  There is some issue with MQTT Paho library on devices running Android 9 or above and the Paho library seems to lack support so there is no fix.

**Comment by thanksmister** [comment]
@vladik1969 do you know Android?  Do you want to try to fix this in a new pull request?   Seems that you know some programming.

**Comment by vladik1969** [comment]
MQTT working fine.
You just need to add URLDecoder.decode to this location.
            if (commandJson.has(COMMAND_SPEAK)) {
                speakMessage(commandJson.getString(COMMAND_SPEAK))
            }
I'm sorry, I don't know Android and Java.

**Comment by vladik1969** [comment]
I think, what You could add new command "COMMAND_DECODE_SPEAK", and add next code:

            if (commandJson.has(COMMAND_DECODE_SPEAK)) {
                speakMessage(URLDecoder.decode(commandJson.getString(COMMAND_DECODE_SPEAK), "UTF-8"))
            }

**Comment by thanksmister** [comment]
Ok the issue was with the way we configure the server, or rather the http server package we are using, it did not properly handle posts with character set utf-8 and garbled the strings.   To get this working, you must send your json as utf-8 in the http post like this:

```
curl --location --request POST 'http://192.168.86.34:2971/api/command' \
--header 'Content-Type: application/json;charset=UTF-8' \
--data-raw '{
    "speak": "¡Aló mundo"                        
}'
```

The content type `json;charset=UTF-8` must be present.

**Comment by thanksmister** [comment]
This will be available in the next release.

**Comment by thanksmister** [comment]
Please try with https://github.com/thanksmister/wallpanel-android/releases/tag/v0.9.4.9.

**Comment by vladik1969** [comment]
Hello. I couldn't answer earlier. I tried version 0.9.4.9. This function works in it. Many thanks.
