### ISSUE TITLE
Remove Refresh Gesture or Make it Optional

### ISSUE THREAD

**Issue by ogrady** [thanksmister/wallpanel-android#273]
**Is your feature request related to a problem? Please describe.**
Swiping down on the WallPanel currently triggers a refresh of the dashboard. While useful at times, this comes extremely unhandy with everything that requires a downward-swiping-motion, like scrolling down dropdown-menues or pulling a ring-gauge all the way down to minimum or maximum.

**Describe the solution you'd like**
Either refreshing via a refresh-button or introduce an option to toggle between refresh-button and swipe motion to refresh would solve the problem.

**Describe alternatives you've considered**
I have considered switching all my ring-rauges to linear left-to-right gauges. But since the problem also occured with the language dropdown, this is no longer a feasible solution. (I need to scroll down, as HomeAssistant seems to sort languages by prevalence and I can't get from English up to German)

**Additional context**
none.

**Comment by thanksmister** [comment]
There is already an option to remove refresh.  Please check the settings.  You can also refresh remotely using MQTT or HTTP.

**Comment by ogrady** [comment]
Found it! Being able to refresh through swiping put me into some sort of kiosk-mode where I wasn't able to get back into the settings. Rebooting the device and catching the right moment before fully loading the dashboard got me back into the settings and BOOM, there it was. Sorry for the unnecessary issue and thanks for the quick response!
