### ISSUE TITLE
Simplify troubleshooting

### ISSUE THREAD

**Issue by TheQue42** [thanksmister/wallpanel-android#275]
**Is your feature request related to a problem? Please describe.**
I am trying to troubleshoot why my TTS (speak: "text" doesnt work), but apart from using wireshark and trying to validate the mqtt message, I have no way of debugging.

**Describe the solution you'd like**
Logs somewhere! Preferrable a port I could just point my browser to on the device, where various selected logs can be output. Even better would be to be able to change settings via network, but I cant get everything at first go ;-) 

**Describe alternatives you've considered**
Local logs on the device, but that means running around different devices, trying to read logs, instead of my 43" monitor :-)

**Additional context**
Add some info on how to troubleshoot errors.
I got the TTS message working ONCE, before I had figured out that I had to change the base-topic for my two devices.
Since that neither device is accepting "speak" commands.

In home assistant (from where I am trying to trigger speak) I have logs from:

`DEBUG (MainThread) [homeassistant.components.mqtt] Received message on wallpanel/wpsonysensor/magneticField: b'{"value":-104.17919,"unit":"uT","id":"AK09911 Magnetometer"}'
`
and

`DEBUG (MainThread) [homeassistant.components.mqtt] Received message on wallpanel/wps6sensor/light: b'{"value":4,"unit":"lx","id":"TMD49XX RGB Sensor"}'`

Since the two devices are set as wpsony and wps6 for base topic.

But neither

`DEBUG (MainThread) [homeassistant.components.mqtt] Transmitting message on wallpanel/wpsony/command: '{"speak": "Hello there my darling"}', mid: 105`

or:

`DEBUG (MainThread) [homeassistant.components.mqtt] Transmitting message on wallpanel/wps6/command: '{"speak": "Hello there my darling"}', mid: 106`

will trigger tts.

Using the HA mobile-app, sending TTS messages work.

**Comment by thanksmister** [comment]
You would do this with external application listening to your mqtt server though, you do not need to see this in the application.  In HA you can go into integreations, then mqtt configuraiton and you can send and listen to responses.  You can also do this from the command line with mosquito or a few applications that do this.  \

**Comment by TheQue42** [comment]
I can see the MQTT messages, yes. But I cant see how wall panel is interpreting them! Why isnt my commands working? For some reason, the two wallpanels are ignoring my messages. Why? How can I figure that out?

**Comment by TheQue42** [comment]
I least, since HA doesnt complain when I *send* the messages, I assume they ARE being sent, and that its not a transport issue between HA and the mqtt server. Especially since I am using the same tool now, as when it worked, once.

**Comment by thanksmister** [comment]
Mostly likely you have some issues with your quotes.  This is how I send my test command from HA:

<img width="781" alt="Screen Shot 2021-05-26 at 4 17 02 PM" src="https://user-images.githubusercontent.com/142340/119718399-e63d6d80-be3d-11eb-9935-6c69cde3f438.png">

Try using other commands to test your configuration is correct.   Also be sure the devices support TTS.

**Comment by thanksmister** [comment]
This is the full screen, subscribed to the command as well:

<img width="708" alt="Screen Shot 2021-05-26 at 4 19 38 PM" src="https://user-images.githubusercontent.com/142340/119718632-2e5c9000-be3e-11eb-9626-ef3e8377a8f3.png">

**Comment by TheQue42** [comment]
![mqtt1](https://user-images.githubusercontent.com/38688906/119719287-e3a43d80-be68-11eb-8634-5b788def44b1.jpg)

**Comment by TheQue42** [comment]
But still no go. If I in another tab do: 
![mqtt-2](https://user-images.githubusercontent.com/38688906/119719393-046c9300-be69-11eb-9e0d-90874c2484b9.jpg)

I get good morning from the tablet.

**Comment by thanksmister** [comment]
Are you receiving any command with the application?  Like try to load url remotely.

**Comment by TheQue42** [comment]
I tried "wake: true" but at least the sony tablet stays screen-off.

**Comment by TheQue42** [comment]
Since I had issues with understanding the different purposes of client-id, base-topic, etc in the beginning, I changed these and that's where things starting failing.  I had changed the display name, and client id, but missed the base-topic.

In HA though, I can still see:
![wpsony-ha](https://user-images.githubusercontent.com/38688906/119721469-7a71f980-be6b-11eb-9144-202813e3e910.jpg)

Which do me is confusing. The topic is based on the client id, but the sensor name comes from the displayname?

**Comment by thanksmister** [comment]
You seem to have gotten yourself confused.  The client ID is the unique identifier of the device, this is used when connecting to the MQTT broker, each device must have a unique client id.    The base topic can be used to receive commands or publish messages from a specific device.  

The default command is as I displayed in the images.  `wallpanel/mywallpanel/command`  the "mywallpanel" is the base command topic.   This is the part you can configure to receive commands per device, if you have more than one.   Otherwise, I would just leave the defaults and then look at the documentation to see how to use it first, before deciding to change the names.

I suspect you have a different base topic in the application configured than the one you are using in your MQTT topics, so the app is never receiving any command.  

Here is how I would approach the issue.  Uninstall the application completely, remember some devices backup stored data, then use the default command and client id to test your MQTT before customizing everything.  Then change one thing at a time, test, and then move to the next.

**Comment by thanksmister** [comment]
I can't not really address the issue because I don't know what you have done exactly.   It looks like you turned on discovery and now maybe the commands have different names for publishing information about the device.   I would focus on just the base command and receiving a command, not what is getting published from the app.    But again, I would start over and go step by step rather than change everything.

**Comment by TheQue42** [comment]
I found it!!

I wish I would follow my own rules that I teach during troubleshooting courses.

I found the cause by turning on debugging in the mqtt server, and I could see what messages/topics where being subscribed on from the client. wallpanel/sonywpcommand......

I have set the base topic to wallpanel/sonywp, after reading the documentation saying:

`The base topic value (default is "mywallpanel")`

But...there's the missing **slash**. wallpanel/sonywp*/*

To me, a mqtt noob, the slashes are topic delimiters, so when I set the name to XYZ, I am expecting delimiters to be automatically added, if needed, but I guess not. I wouldnt be bad though, if the application simple checked for a missing slash, since I wont be the last one to make this mistake.

Thanks for all the help during troubleshooting, AND a wonderful app in general!

**Comment by thanksmister** [comment]
In the settings, for the base topic, only change "mywallpanel" part of the base topic.  This is used to receive the commands, as outlined in the wiki, you send a command using the base topic then "/command".   By default this is `wallpanel/[baseTopic]/command`   or `wallpanel/mywallpanel/command`.  

![Screenshot_1622060037](https://user-images.githubusercontent.com/142340/119725028-d32e9b80-be45-11eb-82d5-6e4be4aa3d70.png)

The client id is only needed to make the device unique for your MQTT broker, its not used to publish or receive commands.  It's only ever used to initialize the MQTT client.

**Comment by thanksmister** [comment]
> I found it!!
> 
> I wish I would follow my own rules that I teach during troubleshooting courses.
> 
> I found the cause by turning on debugging in the mqtt server, and I could see what messages/topics where being subscribed on from the client. wallpanel/sonywpcommand......
> 
> I have set the base topic to wallpanel/sonywp, after reading the documentation saying:
> 
> `The base topic value (default is "mywallpanel")`
> 
> But...there's the missing **slash**. wallpanel/sonywp*/*
> 
> To me, a mqtt noob, the slashes are topic delimiters, so when I set the name to XYZ, I am expecting delimiters to be automatically added, if needed, but I guess not. I wouldnt be bad though, if the application simple checked for a missing slash, since I wont be the last one to make this mistake.
> 
> Thanks for all the help during troubleshooting, AND a wonderful app in general!

Yeah, MQTT is not super intuitive I know, so try to stick with the examples and defaults before advancing into the realm of renaming everything.

**Comment by TheQue42** [comment]
But, this wasnt caused by "renaming everything". It was simply caused by a missing slash, which is quite easy miss to make on touch keyboards. And that the application could check the entered value for a missing slash and add if needed, doesn't seem like a major fix :-)

**Comment by thanksmister** [comment]
Haha, so you are blaming me?   Well if you want to make PR to add that check, please do.

**Comment by TheQue42** [comment]
Jeez! Where on earth did I blame you?!? I **explicitly** said earlier, that "And Yes, I am quite a n00b when it comes to mqtt specifics, so I will not at all be amazed if this is all pebkac, but I'd wish I knew _what_..."

I simply asked for simple input validation of things that might easily be misswritten. I love to TRY to create a PR, but I've never worked on github before, and my knowledge of java development is from around -95, so there's quite a startup-stretch.

**Comment by thanksmister** [comment]
That was sarcasm, hence the “haha” at the beginning.
