### ISSUE TITLE
recommended version for fire table 7

### ISSUE THREAD

**Issue by clyra** [thanksmister/wallpanel-android#276]
Which version is the recommended for a fire tablet 7 and for a fire tablet hd8?  I'm seeing some slowness and freezing on those tablets while using hadashboard (and some use of websockets/js). So, before invertigating further, I'd like to be sure that i'm on "right"/stable version. Thanks!

**Comment by thanksmister** [comment]
Maybe try https://github.com/thanksmister/wallpanel-android/releases/tag/v0.9.3.4 or some version before the update you received that caused the problem.   I am running the latest version on Fire OS without issue.

**Comment by thanksmister** [comment]
Which OS are you using for your fire os?  I have 5.6.8.0

**Comment by thanksmister** [comment]
Any version of the application will work on that device.
