### ISSUE TITLE
tap vs drag adjustments

### ISSUE THREAD

**Issue by sygys** [thanksmister/wallpanel-android#277]
Is it possible to set the touch and drag sensitivity? Operating a wall mounted tablet is different then operating it in your hand. the tablet registers drags instead of presses a lot. this results in button presses not being executed but merely the UI trying to drag the page. Its hard to keep your finger very still to press a button on a small screen on the wall. I wonder if there is a way to maybe adjust this sensitivity of drag and touch. so that it registers presses easier / more often.

Maybe im the only one having these issues and maybe it isnt even possible to adjust. But i need to press most tabs on home assistant multiple times before it actually registers a press instead of a swipe/drag.

**Comment by thanksmister** [comment]
Can you be more specific, you taking about the code screen?

**Comment by sygys** [comment]
Im sorry if im wasn't clear enough. 

I mean in the browser or whatever is used to show home assistant in within the wallpanel app. So what i mean is pressing buttons in home assistant within wallpanel. When controlling home assistant on the tablet using wallpanel most of the presses i make are registered as drags/swipes thats because it is very hard to keep your finger still when aiming for a small button on the screen. 

I just wondered if the sensitivity of the touch / drag can be adjusted so this doesnt happen.

I hope i explained it right this time. My english isn't very good with explaining these kind of things.

**Comment by thanksmister** [comment]
I would turn off the browser refresh option in the application settings, then there is no drag events captured.   If that is not on, there is nothing I can do to fix the drag events within the web page rendered.

**Comment by sygys** [comment]
I understand. i will look if i can adjust these setting in android itself
