### ISSUE TITLE
Access to WallPanel settings?

### ISSUE THREAD

**Issue by bjornesjogren** [thanksmister/wallpanel-android#28]
I cannot find a way to access the settings of WallPanel after I've saved them when initially configured them. Either I suggest an update to the documentation saying how to access them OR add an option somewhere to access them and change them.

Running WallPanel on a Lenovo Pad using Android of a version updated yesterday Nov 9, 2018

**Comment by thanksmister** [comment]
It's a full-screen application so you need to pull down on the screen from the left/right/bottom/top or see the control buttons.  It's the same as if you were using Netflix or other full-screen application.

**Comment by c-holbech** [comment]
Had the same question, so I hope this can help. On my device (android 7.1 tablet) I need to scroll up and hit the "back" arrow to access settings.

**Comment by bjornesjogren** [comment]
> Had the same question, so I hope this can help. On my device (android 7.1 tablet) I need to scroll up and hit the "back" arrow to access settings.

Thank you very much, that worked though not obvious.
