### ISSUE TITLE
[BUG] Ilegal character in the notification.

### ISSUE THREAD

**Issue by RaveGun** [thanksmister/wallpanel-android#281]
**Describe the bug**
The notification element stating that the "Wallpanel is running..." uses a special char "horizontal ellipsis" (U+2026).
This character cannot be stored in the HA database.

**To Reproduce**
I have on the same device the HA Companion App installed and I use the Notification Sensor of the app to extract the notifications out of the device. The above mentioned notification cannot be stored into my PostgreSQL because of that special character.

**Smartphone (please complete the following information):**
 - Device: Acer Iconia 10
 - OS: Android 6.0
 - Applicaiton version: 0.9.4 build 9

**Comment by thanksmister** [comment]
Wallpanel is a dedicated application, it should not be run in conjunction with the companion app.  If the companion app cannot properly store characters, it's a problem of the companion app.

**Comment by RaveGun** [comment]
Well, I have expected this answer.

But I still don't think there is much added value in using the special character instead of the regular "..." string.

**Comment by thanksmister** [comment]
That special character is what is recommended to use for the "..." in Android.  So either I have to conform to android standards, or HA has to conform to what Android recommends.   I think this is a HA issue and not an Android issue.

**Comment by RaveGun** [comment]
Yeah, interesting.

But I just disabled all Wallpanel's notifications.
Now there is no notification anymore and so there is no more text that needs to be stored into the history database.

Please close the issue.
