### ISSUE TITLE
[BUG] Can´t initialize MQTT Client

### ISSUE THREAD

**Issue by kc3577** [thanksmister/wallpanel-android#286]
Describe the bug:
I tried to activate the MQTT client on both tablets, I get the same error on both tablets, "There was an error initializing the MQTT client, please check your settings.". I have checked the settings several times and they are correct. I use it locally without ssl and only use ssl for external access. But I just can't get the client to start.  

To Reproduce:
Go to the settings and back to the web interface.
And on the start of Wallpanel

Smartphone:
 - Device: [Samsung Galaxy Tab A (2016) and Fire 10 HD Pro 2021]
 - OS: [Tab A Android 8.1.0 and Fire OS 7.3.1.9 ]
 - Applicaiton version [v0.9.5 Build 6 (on both)]

Additional note:
 My MQTT Broker runs on Home Assistant via plugin

**Comment by thanksmister** [comment]
I don't have a way to resolve the issue, the message is accurate, you don't have your MQTT client properly configured and the connection to your server cannot be established.   It could be your url, username/password, or you port.   There are tools in Home Assistant to help you test your setup or you can test from the command line as well.

**Comment by kc3577** [comment]
After checking the settings again and reading it in the github wiki, I found my mistake, the http prefix must not be set in my case. I thought that since I only followed the instructions in the app, the http was necessary according to the description. it was apparently a misunderstanding on my part.

**Comment by thanksmister** [comment]
Believe me. I get confused as well.  I think I out a example in the entry field though.  Glad you replaced it, you have less hair now probably.
