### ISSUE TITLE
Stop MQTT error on startup for Android 5.0 devices

### ISSUE THREAD

**Issue by wbilger** [thanksmister/wallpanel-android#29]
I get the error "There was an error initializing the MQTT client, please check your settings" on multiple devices on re-opening the program.
I don't get it on startup auto launch, but only after I back out, and then re-launch my page in WallPanel.
MQTT works though.

**Comment by thanksmister** [comment]
Can you provide more information such as the device, the operating system version and the version of the application you are using.

**Comment by thanksmister** [comment]
Yeah, on some older devices there is a temporary connection issue on startup.  Just ignore the message, it won't show up again and the connection will automatically reset itself.   I think this has to do with some kind of lag in the service or WiFi connection.    You still didn't provide what version of the application you are using, you can find out under the About section of the application Settings.

**Comment by wbilger** [comment]
Sorry, 0.8.4 build 7, installed from google play for all devices.
Is it the older device, or the older version of Android? 
Anyway, no complaints, I can live with it, I'll just try to give you all the info in case it helps. I do get the message every time I back out of the app into settings, and click Dashboard again, the only time I do not see the message is on a reboot and it auto launches.
Thanks for the great app btw!
