### ISSUE TITLE
Magic mirror support

### ISSUE THREAD

**Issue by lsaadeh** [thanksmister/wallpanel-android#290]
Magic mirror doesn’t seem to load and the screen just appears black!

**Comment by thanksmister** [comment]
We don't support that platform and have no way to test it.    My understanding is that you are running Android on a larger screen.   There is nothing specific that we do unless it requires a different layout.   But again, I don't have the same setup, so I don't have a way to test.

**Comment by lsaadeh** [comment]
@thanksmister just for anyone that comes across this.. it ended up working after a little playing around. Currently I’m using this app as a display for my magic mirror site hosted on my home server in server mode only.

**Comment by thanksmister** [comment]
Great, thanks for the update on this!
