### ISSUE TITLE
Storage Permission to open local html page (Tileboard)

### ISSUE THREAD

**Issue by mouth4war** [thanksmister/wallpanel-android#3]
I get an access denied error when trying a file:/// url. I think the app needs storage permission to be able to open locally stored pages.

**Comment by thanksmister** [comment]
Permissions need to be added to access local storage.

**Comment by thanksmister** [comment]
More permission required for the WebView as well https://stackoverflow.com/questions/35496930/display-local-image-in-android-webview-on-marshmallow-err-access-denied

**Comment by thanksmister** [comment]
I have added the additional permissions in v0.8.2.7, let me know if works.
