### ISSUE TITLE
opening hass homepage in wallpanel

### ISSUE THREAD

**Issue by vandura231** [thanksmister/wallpanel-android#30]
Hi, first of all thx for picking up this great  app.  I'm using a tablet with android 7.1.2  I've installed wallpanel from the playstore.  I only get the blue bar on top when opening ?  Hass (regular page and lovelace) page open fine in chrome brower.  honoustly don't know where to start.  Any help ?

Thx!!

**Comment by thanksmister** [comment]
Some type of rendering issue with the HTML/CSS/JavaScript of the page.  Usually this occurs with older devices, but your device doesn't sound that old.   You can look for a WebView component update in the Google Play store, that component is responsible for rendering the web pages within an Android application.   If that doesn't work, there is a "legacy" version of WallPanel in this same Github that uses Crosswalk browser for rendering webpages.

**Comment by vandura231** [comment]
Well, It's seems there is :-) I used another hass instance (slave) with less entities and it seems to work.
Super! thx for bringing me back on track, now I can start diggin' my ui-lovelace.yaml

**Comment by thanksmister** [comment]
Awesome!!
