### ISSUE TITLE
back to wallpanel after launching external application

### ISSUE THREAD

**Issue by luzik** [thanksmister/wallpanel-android#301]
Calling external (ring class app) is great ! But how do I go back ? When I send:

`{"topic":"wallpanel/mywallpanel/command","payload":"{'url': 'intent:#Intent;launchFlags=0x10000000;component=com.thanksmister.iot.wallpanel/com.thanksmister.iot.wallpanel.ui.activities.BrowserActivityNative;end'}"}`

Nothing changes. Is there any service that can work in background ? How can I achieve this ?

**Comment by thanksmister** [comment]
There has already been a discussion on that here https://github.com/thanksmister/wallpanel-android/issues/160

**Comment by luzik** [comment]
Yeah that's reasonable. Thx
