### ISSUE TITLE
[BUG] Sending sensor data seems to crash the system

### ISSUE THREAD

**Issue by wanno-drijfhout** [thanksmister/wallpanel-android#304]
**Describe the bug**
When I enable "Sending sensor data", it seems my tablet doesn't survive more than 90 seconds before it triggers an abrupt reboot cycle. Disabling the "sending sensor data over MQTT" seems to solve the issue, at the cost of acquiring sensor data.

See the [logcat.txt](https://github.com/thanksmister/wallpanel-android/files/6962228/logcat.txt) I've accumulated around a refresh cycle.

I'm particularly triggered by log entries like `System  : A resource failed to call destroy.` Does wallpanel correctly close system handles to sensors, especially for sensors that were unavailable or failed to yield data?

**To Reproduce**
Enable "Wallpanel to send Sensor data over MQTT" (without SSL, but with account authentication). The MQTT server requires authentication but no Access Control. Sensor values that are available are indeed sent to MQTT, because they're ultimately visible in Home Assistant.

**Device**
 - Make: Samsung Galaxy Note 10.1 (GT-N8010)
 - OS: LineageOS 16.0 and LineageOS 18.1
 - Application version v0.9.5 build 6 (may be regression since v0.9.3.1, where I didn't have the problem)

**Comment by thanksmister** [comment]
Sounds like an error with the Android SDK and getting sensor data on that device, could be that it requires extra permissions on Lineage, I don't know because I never tested on that device.   This is not an issue sending sensor data, it seems to be issue reading the device sensor data, which uses the SDK library to read sensor data.   I can look for the crash in firebase to see if there is a specific permission involved.

**Comment by wanno-drijfhout** [comment]
Obviously, just after I submitted this carefully constructed report, my tablet decided to crash again after all. It does seem to be a case of 11 minute sessions rather than 90 second sessions now, though. Disabling MQTT sensor data sending definitely does something. There's still other MQTT entries being sent (Face detection, for example), so I think the problem may still be related to something overloading because of MQTT traffic.

Now (at latest LineageOS 18.1 and latest Wallpanel without MQTT sensor data sending):
![afbeelding](https://user-images.githubusercontent.com/2872972/128882717-a30e699b-33bc-4f29-a4e9-f0f4202ce69e.png)

Yesterday (at LineageOS 16.0 and latest Wallpanel *with* MQTT sensor data sending):
![afbeelding](https://user-images.githubusercontent.com/2872972/128883068-910d1bbf-05f6-40f5-9598-1aec633c0d38.png)

**Comment by wanno-drijfhout** [comment]
> This is not an issue sending sensor data, it seems to be issue reading the device sensor data, which uses the SDK library to read sensor data.

Agreed, I think the MQTT sending itself works alright. The actual acquiring the sensor data is much more likely to involve handles and driver interaction that could cause a fatal crash. 

> could be that it requires extra permissions on Lineage, I don't know because I never tested on that device

I've added Video recording (and Voice recording) permissions, as Lineage specifically listed those as needed for Wallpanel. Wallpanel lists a number of sensor values it wishes to send to MQTT, but it immediately lists the example values of some as "Not available": Temperature, Pressure and Humidity. Does Wallpanel simply always assume those sensors are available, or is my Android device acting weirdly by reporting sensors that aren't actually available?

**Comment by thanksmister** [comment]
Hmm, could be the unavailable sensors, if they are not available, they should not appear in the list, this seems to be an issue.  If we try to get data from an non-existent sensor, then possibly boom!  Normally, only available sensors are reported.   I guess we could introduce a check to double check the sensors are actually unavailable (identified as "not available").

**Comment by wanno-drijfhout** [comment]
> if they are not available, they should not appear in the list, this seems to be an issue.

I suppose indeed. I am happy these sensors were visible, though. It's good feedback that there's something funky going on.

> If we try to get data from an non-existent sensor, then possibly boom!

I reckon this situation could cause some weird situations indeed. I could imagine a new handle of a "faulty sensor" being opened at every try and not closed, because the call to acquire the actual data failed. However, that handle should still be closed. This is just hypothetical, but it was inspired by the log entry `A resource failed to call destroy`.

Do you manage sensor handles in Wallpanel, or is this something that happens in the Android SDK itself?

**Comment by thanksmister** [comment]
It's just a call to the Android library, it returns the list of sensors available and we display then, post their data to MQTT.   So seems like something with LineageOS possibly.  There is a "SensorManager" class in Android that does all the sensor work:

```
 mSensorManager = context.getSystemService(SENSOR_SERVICE) as SensorManager
        for (s in mSensorManager.getSensorList(Sensor.TYPE_ALL)) {
            if (getSensorName(s.type) != null)
                mSensorList.add(s)
        }
```

This is from the SensorReader.kt file, it just iterates over the available sensor to add the data to a list, this is later published over MQTT by reading each individual sensor data value.

**Comment by wanno-drijfhout** [comment]
Yeah, it's a weird one.

I looked at https://github.com/thanksmister/wallpanel-android/commit/0538463bdbea5b65f8578a0174df889ac091f86d#diff-ac0ae8160f5cb2bfe45587a8a718f8f4fb4676d96c2b7637c63d93431fe26b27R82, which introduces `refreshSensors`, which would surely destroy and recreate sensor handles. It does seem it's only called whenever [MQTT connects](https://github.com/thanksmister/wallpanel-android/blob/95379504aae02678ef91c1463e141b41cf7e2b8a/WallPanelApp/src/main/java/com/thanksmister/iot/wallpanel/network/WallPanelService.kt#L334), so this seems to be a rare occurrence. I've looked in my MQTT server logs and I don't see excessive connections. I wouldn't expect problems here.

By the way, I noticed [`lightSensorEvent`](https://github.com/thanksmister/wallpanel-android/blob/95379504aae02678ef91c1463e141b41cf7e2b8a/WallPanelApp/src/main/java/com/thanksmister/iot/wallpanel/modules/SensorReader.kt#L178) gets exceptional treatment in the code. Does that have a purpose? It just seems to send the same event to MQTT twice now.

That method did make me think: could exceptions occur in SensorEventListener? Are they handled by Android or by your app? What happens if the flag `sensorsPublished` isn't set to `true` because something went wrong before (e.g., while fetching sensor values or sending an MQTT message). Could it cause a busy loop of retries just milliseconds apart?

**Comment by wanno-drijfhout** [comment]
I found some extra information that could help us trace "leaking resources": https://wh0.github.io/2020/08/12/closeguard.html. Is this "StrictMode" something you'd be willing to try integrating, to help determine if the "System : A resource failed to call destroy." is caused by WallPanel?

**Comment by wanno-drijfhout** [comment]
Time has passed and the reboot loop seems to have miraculously stopped. I have no definitive answer to what fixed the situation. I think I fully formatted and re-installed the tablet (but that could've been before this issue already). I'm currently running v0.9.5 build 7, installed via the Google Play Store (rather than sideloading an APK).

I'll close this issue now.
