### ISSUE TITLE
Any chance for support for 3rd party cookies

### ISSUE THREAD

**Issue by wbilger** [thanksmister/wallpanel-android#31]
Would be handy for embedded iframes in HA.
At least not working for me for google calendar.

**Comment by thanksmister** [comment]
How well the webpage renders is entirely up to which version of WebView (the version of Chrome used for Android applications) is supported on your device and operating system.  I am not blocking any 3rd party cookies, but this may be a security measure of the WebView sandbox.

**Comment by wbilger** [comment]
Yes, if I go to the google calendar in WallPanel and login, it keeps the login.
But, if I embed a google calendar in an iFrame in home assistant, it does not access cookie. This works on Fully Kiosk, and Chrome on same device. Same behaviour on devices with Android 5, 5.1, and 8.
Not sure if there is anything I can do?

**Comment by thanksmister** [comment]
Well then let’s investigate how we manage 3rd party cookies in Android WebView.   I will let you know what I discover.

**Comment by imbaimbaimba** [comment]
Any news on this @thanksmister ?

I think I have the same problem, but I am not sure.

I have my dakboard put in an iframe. On my pc it works fine, except for a gap between header and first card in lovelace that I cannot figure out how to remove:
[Picture](https://i.imgur.com/4jujL6K.png)

It also works fine in my Lenovo Android tablets own browser, on my iPhone's browser etc.

But on wallpanel, it doesn't seem to load properly and gives me this:
[Picture](https://i.imgur.com/M9FkOJu.jpg)

For reference, I get the same issue when trying to run it on the Home Assistant app on iOS.

**Comment by thanksmister** [comment]
This sounds like a CSS/HTML rendering problem.  The version of ChromeOS used internally by the Android application is not the same as the browser on the device, so the it won't support all web pages in the same manner.     Some compatibility issue with a recent addition to your HASS dashboard?
