### ISSUE TITLE
Enable/Disable Webcam by MQTT or Rest

### ISSUE THREAD

**Issue by wbilger** [thanksmister/wallpanel-android#32]
It would be great to be able to enable/disable the webcam via command.
Unless this is already possible, I don't see it. Thanks.

**Comment by nodinosaur** [comment]
I have created a Pull Request for this [#45](https://github.com/thanksmister/wallpanel-android/pull/45)
However is it a bit flaky, I would advise @thanksmister to give it a thorough look.

#### Camera On:
```
MQTT Topic:
wallpanel/mywallpanel/command
Value:
{"cameraOn":true}
```
#### Camera Off:
```
MQTT Topic:
wallpanel/mywallpanel/command
Value:
{"cameraOn":false}
```
But give this a try to see if it meets your needs.

**Comment by thanksmister** [comment]
Yeah, I am going to test this to see what's causing the flaky behavior.  I suspect its that everything needs to be initialized when starting the service, so turning on/off the camera requires initialization.

**Comment by thanksmister** [comment]
I think this requires more than can be done with a simple command.  The camera needs to already be on, configured for front/back, and tested.  This won't work just out of the box.   You can enable the camera feature without having it stream over HTTP.  You can enable or disable your HTTP stream using this feature, but turning on/off the camera would break unless the camera is already active.

**Comment by nodinosaur** [comment]
Ah, yes, I forgot to consider this scenario, good call.
To avoid any confusion, or issues, before this runs the command should call a diagnostic to check if everything is configured for camera and streaming settings, displaying a notification and/or directions of some sort if not set up correctly (even sent back on the stream if we want to be clever).

**Comment by yabuts** [comment]
How about to disable/enable motion detection from mqtt (let the camera state as is)

**Comment by thanksmister** [comment]
Yeah maybe, for this you can make a new feature request.
