### ISSUE TITLE
Fix for loading self-signed certificates in WebView

### ISSUE THREAD

**Issue by thanksmister** [thanksmister/wallpanel-android#33]
Currently there is an issue with loading self-signed certificates, basically it doesn't work.  Need to investigate what is required for loading and handling self-signed certificates.  This will allow users to see  load there home platform dashboard outside their network.

**Comment by JPHutchins** [comment]
Just a slight clarification here.  When entering the local IP address the app will identify that the certificate is for a different website (the DDNS).  This behavior is forcing me to use my DDNS to test the app when I would much rather connect via the LAN.  It is notable that the application is basically bricked by this and I had to reinstall in order to verify that it would in fact work when it sees that the self-signed certificate is for the correct site.  Further, if I can load my DDNS from my LAN that means I can load it from anywhere - so the remote capability IS working.  I wish I knew literally anything about how this project works, I'll take a look and try get myself curious and confused!  Thanks for the great work!

**Comment by thanksmister** [comment]
The problem with certificates is just with self signed ones.  You can do to any https location and the app works.  However with self signed certs we need to verify that you wish to load them.  This doesn’t seem to be working as the Android application uses the WebView component which is a variant of Chrome but it can be outdated depending on your device.   

From what I’ve read so far. It seems that the application needs to load the certificate in order to work,not just verify the user wants to use the self signed one.   That’s where is seems to be failing as there is no way to load the certs from the local key store on the device.   

I would really like to look at the code Fully Kiosk Browser is using to see how they are handling certificates but they didn’t open source their code. Until I find a definitive solution, I’m not able to resolve the issue.

As far as you application locking up, that’s something I haven’t seen before and perhaps related to rendering issues.

**Comment by thanksmister** [comment]
That's strange, I will test this and see what I find.   If it works, then I will add this to the next release.  Thanks for helping.

**Comment by thanksmister** [comment]
Yeah, its the super that is also canceling the request, even though the documentation says that its up to the developer to call cancel or proceed, cancel is already being called:

```
/**
     * Notify the host application that an SSL error occurred while loading a
     * resource. The host application must call either handler.cancel() or
     * handler.proceed(). Note that the decision may be retained for use in
     * response to future SSL errors. The default behavior is to cancel the
     * load.
     *
     * @param view The WebView that is initiating the callback.
     * @param handler An SslErrorHandler object that will handle the user's
     *            response.
     * @param error The SSL error object.
     */
    public void onReceivedSslError(WebView view, SslErrorHandler handler,
            SslError error) {
        handler.cancel();
    }

```

**Comment by thanksmister** [comment]
You can try the latest release v0.8.5-beta.0

**Comment by viqviq** [comment]
aw, still not perfect.
The continue button works well, but the user experience not the best.
I left the app open to night and in the morning i saw thar there are many "SSL certificate error" message poped up.
(Maybe due automatic refresh of the page during night?)
[https://imgur.com/a/cTTA3Qm](url)

**Comment by thanksmister** [comment]
I don't see a way around this if your web page is refreshing, the permission has to be asked due to the security  issues with SSL self-signed certificates.   If we remove the dialog, then the app can't be published to Google Play.  What Google doesn't want is apps to load insecure web pages without user consent.

**Comment by viqviq** [comment]
I see :(
What if we create a new boolean under the Configuration: "Allow untrusted sites", and if the user set it true, than the dialogue is not shown. Will Google disallow the app with this setting?
Thanks

**Comment by thanksmister** [comment]
I think it will be disallowed because you can't automatically load an untrusted site, which is exactly what this settings option would allow.

**Comment by thanksmister** [comment]
Here is a question, why does https://untrusted-root.badssl.com ask for the permissions window just once?  Why is the site you are loading completely refreshing itself?  The application isn't refreshing it automatically.  This is the issue no?

**Comment by thanksmister** [comment]
@viqviq We can try to just show the message once and then auto accept on each subsequent attempt.  Laving the web browser window and returning will show the dialog again, but during the same web page session, we will ignore subsequent messages.  Hopefully this passes Google's requirements.

**Comment by thanksmister** [comment]
Ok, try the latest release to see if that helps.
