### ISSUE TITLE
Screensaver mode

### ISSUE THREAD

**Issue by vitalykorolev** [thanksmister/wallpanel-android#34]
It'd be nice to be able to load some sort of screensaver (blank screen, another URL, time) which would get disabled on motion or sound. This would be an alternative to wake on motion which doesn't work well on my device as it gets locked as soon as screen turns off.

**Comment by thanksmister** [comment]
Yeah that would be a good option.  I have this in my other application for the MQTT alarm panel application.  That way the screen can stay on.  But could you use the screen dimming feature that’s already there to dim the screen, there is an option to brighten the screen in motion.
