### ISSUE TITLE
App shortcut/activity to launch dashboard

### ISSUE THREAD

**Issue by mouth4war** [thanksmister/wallpanel-android#4]
I don't see anything apart from WelcomeActivity in Tasker. This requires a further click on Launch Dashboard to open the dashboard. Can we have an activity to LaunchDashboard?

**Comment by thanksmister** [comment]
WelcomeAxtivity has logic to open the dashboard after automatically if you’ve already been to the settings.  It’s the same as if you clicked on the wall panel app icon.  So if you’ve already gone through the settings, any subsequent launches of the application will redirect you to the dashboard automatically.   The welcome page is only shown on intial install and launch but you need to first visit the settings page before the logic will take you to the dashboard.
