### ISSUE TITLE
Amazon Fire 7 Tablet, going to sleep

### ISSUE THREAD

**Issue by Madseason41** [thanksmister/wallpanel-android#46]
**Describe the bug**
With 0.8.5.4, with prevent device from sleeping selected, after a few minutes the device goes to sleep.

**To Reproduce**
1. Update to 0.8.5.4
2. Start App with no setting changed (if prevent device from sleeping was selected on prior config). Screen saver option is not selected
3. Launch app and wait a few minutes. Screen will go blank.
4. Delete app, re-download 0.8.5.1, select prevent device form going to sleep. Function is now back to expected behavior.

 - Device: Amazon Fire 7
 - OS: latest
 - Version 8.5.4

**Comment by thanksmister** [comment]
I am investigating this, I have the same Fire 7 tablet now.   I can reproduce the issue.

**Comment by thanksmister** [comment]
fixed in next release
