### ISSUE TITLE
.wav files not playing.

### ISSUE THREAD

**Issue by methodnet** [thanksmister/wallpanel-android#47]
Hello, 

I am testing this out with TileBoard and have events that will play .wav files. The .wav files play with other browsers but will not play in WallPanel. Are .wav or other audio files supported?

Running 0.8.5 Build 4

**Comment by thanksmister** [comment]
The application doesn't use a web browser to play sounds, it uses the Android Media player which does not support .wav files.

**Comment by methodnet** [comment]
Ahh... Thanks for the update!

**Comment by methodnet** [comment]
Yes, just searched myself and see the following is supported. 

WAVE	•
(Android 4.1+)	•	8- and 16-bit linear PCM (rates up to limit of hardware). Sampling rates for raw PCM recordings at 8000, 16000 and 44100 Hz.	WAVE (.wav)

Let me double check my files to make sure they can play through the media player separately.

**Comment by methodnet** [comment]
Update: Google Play is the only thing that is installed (fresh Tab A) and plays both the .wav and .m4a files. Is it perhaps a permission issue with that app? Is there another app I should install and set as default for media?

**Comment by TheAlphaLaw** [comment]
@methodnet Did you ever get this to work? I can't seem to play any audio file this way.

**Comment by TheAlphaLaw** [comment]
@methodnet @thanksmister 

This is now working on my end. It only seems to work with local files. Push a few sound files to my HA instance and they now play fine, mp3's included!
