### ISSUE TITLE
Dedicated topic for notification (TTS)

### ISSUE THREAD

**Issue by PrimusNZ** [thanksmister/wallpanel-android#5]
It would be great is there was a dedicated subscribe topic to allow the device to utilize tts via the MQTT format that Home Assistant uses for notifications
https://www.home-assistant.io/components/notify.mqtt/

**Comment by thanksmister** [comment]
There already is, check the remote commands in the documentation. You would send walloanel/mywallpanel/command/speak as the topic and the payload as what you want to say.  That’s is just one of the already established commands.

**Comment by PrimusNZ** [comment]
You own documentation states to send to wallpanel/[baseTopic]/command with a payload of `{ 'speak' : 'Hello' }` - not wallpanel/mywallpanel/command/speak with the payload you wish to speak.
I jhave just tested this and it does not work

`wallpanel/[baseTopic]/command` does, `wallpanel/mywallpanel/command/speak` does not

**Comment by thanksmister** [comment]
I will check but that feature is there if it’s not working it’s kust a bug.

**Comment by thanksmister** [comment]
I just tested from HASS in the latest version and it all appears to be working exactly as documented. Here is what I put in HASS: 

<img width="489" alt="speak" src="https://user-images.githubusercontent.com/142340/43356728-a4fe94f4-924c-11e8-9789-41fed1b01e1a.png">


Its not command/speak, you put "speak" in the payload, see the documentation for TTS for an example:

https://github.com/thanksmister/wallpanel-android#google-text-to-speach-command

So no, there will be no dedicated topic other than command. However, it's easy to send this message using MQTT from HASS using the command topic with "speak" in the payload json object.  This makes is more flexible to add additional commands.
