### ISSUE TITLE
Fingerprint -> MQTT

### ISSUE THREAD

**Issue by Ingalara** [thanksmister/wallpanel-android#50]
**Is your feature request related to a problem? Please describe.**
No current issues

**Describe the solution you'd like**
It would be great if you could register different fingerprints with Android, and when a fingerprint is read from Wallpanel it sends an MQTT message with a unique fingerprint ID to the MQTT broker.

This could be used to trigger rules like disable alarm, or even could allow for kids to "clock in" or do their chores etc from the panel.

**Describe alternatives you've considered**
A PIN pad is an alternative, but PINs are easy to forget or be shared etc. Biometrics is way more high tech!

**Additional context**
I think the MQTT Alarm Control Panel already has a similar feature so hoping code may be able to be shared?

Thanks!

**Comment by thanksmister** [comment]
The reason to use a pin and a fingerprint unlock is because many older devices do not have fingerprint scanners.    But just for publishing MQTT message on scan, its a good idea.
