### ISSUE TITLE
Wallpanel don't show custom graph widget on HADashboard

### ISSUE THREAD

**Issue by voodoobg** [thanksmister/wallpanel-android#51]
**Describe the bug**
I'm using wallpanel with HADashboard and everything works fine, but i've installed this custom widget that gets data from the InfluxDB and shows some graphs:
https://github.com/tjntomas/HADashboard-widgets/tree/master/custom_widgets/basegraph

On my computer and on the tablet with mozilla firefox everything works, but when I load the dashboard with the graphs on Wallpanel, they don't show up and the navigation buttons icons don't show also (they don't work either). I've installed the latest version of WebView but no luck either.

**To Reproduce**
1. Go to Dashboard that has graph custom widget installed
2. See error

**Expected behavior**
Widget shows as it shows in the browsers, like this:
![how-should-look-like](https://user-images.githubusercontent.com/31035770/51424455-95b30700-1bd6-11e9-8bce-3bb87c4d7d7f.jpg)

**Screenshots**
![img_20190119_103215](https://user-images.githubusercontent.com/31035770/51424443-2d642580-1bd6-11e9-87b7-88a17a707ed9.jpg)

**Smartphone (please complete the following information):**
 - Device: Eepad Transformer 101
 - OS: Android 6
 - Browser Wallpanel/Mozila Firefox

**Additional context**

**Comment by thanksmister** [comment]
The browser used by the application is a version of ChromeOS but not the same as your browsers and not the same as WebKit for Safari.  Your Android version determines the version of Chrome OS used by the application.  

You are having compatibility issues with the widget you installed and there is no way for me to address it.   You can try to update your Android WebView component from Google Play if one is available or your Android version.   There is also a Legacy version of WallPanel in the same GitHub that offers html support for older devices.
