### ISSUE TITLE
Add ability to open/close another app on the device via MQTT

### ISSUE THREAD

**Issue by mrjack711** [thanksmister/wallpanel-android#52]
Is it possible to add the ability to open other apps installed on the device via an MQTT command?
In addition to this, could an app be opened with a shortcut that would open the default app on the device that is associated with that shortcut?
Finally, is it then possible to close the app via MQTT or bring Wallpanel to the foreground?

**Comment by thanksmister** [comment]
None of this is currently possible and I am not sure this would be a feature that I would want to implement.
