### ISSUE TITLE
both cameras in use - one for screen activation, one for streaming

### ISSUE THREAD

**Issue by pejotigrek** [thanksmister/wallpanel-android#53]
I really like the face/motion recognition used for screen activation, and while playing with my wall-mounted tablet [Home Assistant dashboard via Wallpanel], I also thought about another kind of usage: **door peephole** - phone mounted on door, with back camera pointed thru the existing peephole.

I understand, that using both cameras in the same time can be CPU and battery consuming, so we can make some limitations:

- only one camera at time can be switched on - mainly the front camera is on, just to be able to pickup movement or near faces
- when front camera detects movement and/or face [selectable in options: face, movement, face&movement], it switches to backcamera for selectable amount of time [to set in options or - when activated via MQTT in the payload] or as long as somebody is keeping finger on the screen [yeah, that sounds cool IMHO, but I guess it can interfere with other options, so it's not a "must-have" ;)].
- when back camera is on, streaming live is possible, then if the back camera turns off, streaming is offline
- one-time photos possible after MQTT command
- you can switch cameras with MQTT message, just to have a look from other computer/phone without standing next to the door

examples:

**SCENARIO no.1:**
somebody approaches [inside home] the door, front camera recognizes face/motion and then turns on screen, shows stream from the back camera on the screen, sends MQTT message & turns on stream from the back camera, so other devices can join in [streams manually limited via options, so even weaker phones/networks could enable that]

**SCENARIO no.2:**
sending MQTT message to the "peephole-phone" turns on streaming for some time [options selectable, or maybe as a MQTT payload?] so one can check the stream even if there's nobody at the door [inside or outside]. this will enable some video possibilities for DIY MQTT doorbells - I'm planning to add MQTT button as my doorbell button, it will send MQTT message to Home Assistant on every press. then I'd be able to send another MQTT message to the "peephole-phone" to turn on streaming/grab a picture and use it somehow [view on chromecast-enabled tv maybe? it's up to Home Assistant's configuration :)]

**SCENARIO no.3:**
I'm using Telegram messaging app as additional Home Assistant command/notification means. so with the MQTT turning on/off mentioned in second scenario, I'll be able to grab a picture from back camera and send it via telegram to everyone that asked for it - on demand [or after mentioned MQTT doorbell press].

phew, congratulations if you're still reading ;)

what do you think about that? I know that it doesn't look like the main function of the app, but I can see it like expansion of the features :) is it possible?

**Comment by thanksmister** [comment]
I think this is a totally different application you have described, but its not something I want to add to this application.

**Comment by thanksmister** [comment]
I think its just a totally different application, I do not want to add this feature to the application, two streaming cameras at the same time.  I have doubts it would work for one, and the heaviness of that feature is too onerous for this app.  What you need is an entirely separate app just for this feature alone.

**Comment by pejotigrek** [comment]
ok ok, I know you don't want and won't add it, but just to be clear: my idea was just against the constant stream of one or even two cameras, so you probably did understand that wrong or maybe I did some mistake phrasing that (English is not my first language).

streaming from back camera was optional and on demand only (right now you've got constant stream in your app), and front camera was just used to wake up the screen (then it gets shut off & video turns on back cam to show it's stream on screen).

so yeah, more battery efficient & less heat I guess.

anyway, I know your opinion, gonna search another solution :)
