### ISSUE TITLE
Brightness to 100% on Fire HD 7

### ISSUE THREAD

**Issue by rasathus** [thanksmister/wallpanel-android#56]
**Describe the bug**
When ever the app gains focus it overrides the system setting for brightness, and increases the brightness to 100%.  This appears to occur regardless of whether the camera based dimming behaviour is enabled.

**To Reproduce**
1. Set the system brightness to ~50%
2. Open the wallpanel app
3. Note sudden burning sensation in retinas as the screen brightness is increased to 100%

**Expected behavior**
Either the system brightness should be honoured, or some option to disable the override behaviour should be made available.

**Smartphone (please complete the following information):**
 - Device: Amazon Fire HD 7
 - OS: Fire OS
 - Version 5.6.1.0

**Comment by djchen** [comment]
I have the Fire HD 8 and I think I'm running into a similar problem. It seems like whatever brightness you had your screen at when you first launched the app, it will revert to that brightness if you change it.

I initially had the problem where my screen brightness kept getting changed to 50% when the screen is on. I uninstalled the app, set my brightness to 75%, re-installed the app, re-configured it, and now when I change the brightness to 50%, it will revert back to 75%.

**Comment by HFsi** [comment]
I have the same issue on a Samsung Galaxy A3 that was working fine before the last update of the app

**Comment by thanksmister** [comment]
I need to know the application version number.  You can find the version number of the application in the settings, from the about section.   For the application brightness change to work, you need to change the brightness of the device, before going into the settings.  It's funky, but its the only way to know you intent do reset the brightness.  Under normal conditions, you would already have the brightness set before entering the settings.  The other option is to use the MQTT command to adjust the brightness level to what you want.

**Comment by HFsi** [comment]
The version is 0.8.6 Build 2
I don´t change the settings, either if I quit the app, adjust the brightness of the device to auto, and restart, or if I do the same thing in the configuration menu (without changing anything, simply goiing back from the panel and reloading it) the auto brightness is unselected and changed to 100%

**Comment by thanksmister** [comment]
There seems to be some interference with the screen brightness level and when a user is present, so it resets the screen brightness to the default before a user can enter the settings to save the new screen brightness level.   I will issue a new update shortly!!

**Comment by HFsi** [comment]
Same behavior...I´ve just updated the app

**Comment by thanksmister** [comment]
I have not seen this issue under v0.8.6 Build 3.  Be sure you are not setting the screen brightness using MQTT commands.   If you change the devices brightness level before entering the application settings, the screen brightness level is respected.  If you manually change the screen brightness level using MQTt command, that level is respected.

**Comment by HFsi** [comment]
I´ve never used the brightness command trough MQTT, I only use the 'Wake' command

**Comment by thanksmister** [comment]
The brightness wake is redundant now if you use the screensaver.  The screen dims automatically when the screensaver is on and brightens back to normal (your last saved brightness level) when awake.  Can you confirm your version number, go into app settings and then about.

**Comment by HFsi** [comment]
I don´t use the screensaver nor the brightness wake, just the wake....this is my command in HA.
{
  "payload": "{'wake':True}",
  "retain": "false",
  "topic": "a3/command"
}
The screen sleeps through Android config, not HA Dashboard.
The version is 0.8.6 B3.
Restarted the phone, just in case.
And I can confirm that the Android auto brightness is working, because if I exit the Dashboard app, it addapts to the ambient brightness during wake or when I wake up with the side button

**Comment by thanksmister** [comment]
So the auto brightness is working?  You have an issue with the wake, is that correct?

**Comment by HFsi** [comment]
The wake itself works fine, the issue is that doesn't honour the Android brightness, for example:
If I set the phone brightness to 50%, then load the app, when the wake command is sent, the screen is activated but at 100% of brightness

**Comment by thanksmister** [comment]
Ok that is different than what the ticket states that is why there is a confusion.  The issue you have is different than the one fixed and it’s the first time It’s been reported.  I will take a look at the wake code but the original issue for this ticket has been addressed.

**Comment by HFsi** [comment]
Can I provide you with further info? A video maybe? So there is no confusion about what´s happening

**Comment by djchen** [comment]
> @djchen @HFsi Some mqtt broker submit there last value on client connect. May this be the reason?

This issue has been fixed for me with the latest version. I don't use it with MQTT yet.

**Comment by HFsi** [comment]
Not for me.
For now I'm sending the wake command, followed by a brightness command to lower it down
