### ISSUE TITLE
Show still or MJPEG image from the camera stream feature in Home Assistant 

### ISSUE THREAD

**Issue by Underknowledge** [thanksmister/wallpanel-android#67]
With v.0.90 the `stream:` component was added to proxy live streams through Home Assistant. 
At the moment I`m not shure if a rtsp stream is needed or if the mjpeg stream would work when a still image url would be added. 

**Describe the solution you'd like**
(Maybe!) add a still_image_url for HA.

**Describe alternatives you've considered**
Could run another app in the background.

**Comment by thanksmister** [comment]
The application loads web pages, how can you solve the issue with streams, is it currently not showing in the rendered HA dashboard in the application?   Please describe the issue better or feature if this is a feature.

**Comment by WagnerBeccard** [comment]
My bad sorry. 
Best would be to take a look at the [Home Assistant Release-Notes ](https://www.home-assistant.io/blog/2019/03/20/release-90/#camera-streams-for-everyone) wallpanel lives in front of the spyhole of my door. After I already have a way to retive doorbell presses it would be possible to let the chromecast bring up the stream. But therefore the generic camera platform is neeeded. Just would be a neat feature.

**Comment by thanksmister** [comment]
I think it would be a good feature to send over MQTT a path of the URL or MJPEG stream to show temporarily in the application.  So it could, for example, show a dialog with the stream then dismiss itself automatically after some time or on another MQTT command or manually.   Let's label this as a feature request.

**Comment by thanksmister** [comment]
I would not make this a HA specific feature, I think you can show any MJPEG stream now using a webview, the introduction of HA streams doesn't provide anything additional.  What we need is some MQTT commands to bring up a type of camera view to show a particular image or stream.   The image still or MJPEG URL would need to be provided by HA or other home automation platform.
