### ISSUE TITLE
Proximity sensing

### ISSUE THREAD

**Issue by thomasnordquist** [thanksmister/wallpanel-android#68]
I started writing my own app today for the whole purpose of completely disabling the LCD backlight while no-one is watching, and re-enabling it when the display receives a touch event. (There are a few ways if you are root, or you have OLED)

Then I thought, I'd like to enable the display when I'm looking at it, why not use the front camera to detect movement.

If you like the idea, knock yourself out. I had quite some fun 😊

## I started with a very simple approach: 
- Take a small picture
- Count pixels that differ from the previous image
- Average noise to get a narrow range where change can be detected even in difficult lighting conditions. (Noise changes with lighting conditions)

## My Filter Pipeline:
1. Capturing a picture from a video stream
2. Scale it down to an 8x8pixel picture to save computation time and reduce noise (by averaging the surrounding pixels)
3. Average the RGB components of each pixel (from color to black&white)
   1. Compute a threshold which that allows only a few pixels to be detected as changes
   2. average threshold over a few samples
4. Count how often changes were detected in a row/succession (+1 if enough pixels change, -1 if a few or none have changed)
5. Factor in movement speed, to capture slower movements, depending on the angle one walks up to the display (fewer pixels change but occur in a longer duration).
    `changed_pixels_fast_frame * how_many_updates_in_susccession_detected` [I created some kind of score to take duration into account](https://github.com/thomasnordquist/wallmount-android-dashboard/blob/031854602f15f5af60b196575ec813dbfb7c2834/src/movement-detection.js#L75)

## My Implementation
Don't expect much ^^
https://github.com/thomasnordquist/wallmount-android-dashboard/blob/81739aeab7de275685d68a3507f79a3e03fd6658/src/movement-detection.js

I'm sure there are many ways to solve this problem, I really loved the challange.
Took about 2h to get the first results and then a lot of testing. It works suprisingly well with different camera models (tablets / MAC)

Another 2-3h went into figuring out why some scenarios were different from others.
- Light / dark lighting was fixed with an adaptiv threshold
- Filtering sudden lighting changes (turning room lighting on / off) by factor in time. [(At least two frames in succession need changes so a positive score is reached)](https://github.com/thomasnordquist/wallmount-android-dashboard/blob/031854602f15f5af60b196575ec813dbfb7c2834/src/movement-detection.js#L75)
- Walking different angles / speeds in fron of the camera made clear that a time coefficient is required to account for more gradually (but continuous) occuring changes
- I tried to detect changes rather early, the noise averaging helps a lot to detect the tinyest changes in very bad lighting and counting how often changes were detected avoids false positives

Visually debugging the detectes changes also helps a lot.
<img width="250" alt="Bildschirmfoto 2019-04-01 um 01 27 14" src="https://user-images.githubusercontent.com/7721625/55296701-7679f680-541d-11e9-8a2d-f1e621330d6b.png">

## Performance
I didn't measure, the 40$ kindle fire has no trouble and stays cool, even though I do all the processing in Javascript 😅

## Almost forgot
... since you seem to use MQTT a lot, check out https://mqtt-explorer.com

**Comment by thanksmister** [comment]
This is super interesting.  The application currently uses something similar to detect motion, but it's not as intuitive as what you are building.   I am wondering how hard it would be to convert your JS code over to Java/Kotlin so I could do something similar.

**Comment by thanksmister** [comment]
Thanks for the tip on https://mqtt-explorer.com, I do use MQTT extensively and often need to see the traffic between my IoT devices and HA.

**Comment by thomasnordquist** [comment]
I must have missed the feature then, I actually looked for it ^^
I expected it close to the screen / screensaver settings, not the sensors 😅

![ezgif-3-e33837bf04d2](https://user-images.githubusercontent.com/7721625/55296962-ffdef800-5420-11e9-906f-fd924a76aff8.gif)

I'll run some tests tomorrow and compare both solutions.
The easyest way would probably to build upon jjoe64's work, since all the stuff requiring knowledge of Android: media streaming, scaling and some color processing is already working.

**Comment by thanksmister** [comment]
I think I burned out two batteries running the motion detection with the camera.  I am on an Amazon 7 tablet now and do not use motion detection.   I think the current implementation runs the device a little hot, plus the with the screen saver, the screen is still drawing power.   There is no way to wake the device entirely from deep sleep, so its always going to be bad on the device.

**Comment by thomasnordquist** [comment]
The backight also produces a lot of heat.
I took a look at the current implementation, of the motion detection.
I was not yet sure how to efficiently scale down the `Frame` provided to the MotionDetection.

# Backlight
## Not a viable solution for everyone
I rootet my kindle fire 7, 7th gen (possible since march) and use the kernel PWM subsystem to disable the backlight completely, with a disabled backlight the tablet can run a week or so on battery while a app is still running.

https://github.com/thomasnordquist/wallmount-android-dashboard/blob/84d6ca69b58bdb21e29646e50b2947ee2e88791f/src/screensaver.js#L65-L68

## Other root alternatives
There may also be a way to control the minimal brightness of the OS when being root, that do not require knowledge of the tablet hardware specifics.
There are a few apps on the appstore that claim to lower system brightness (without a overlay?)

## Non-Root alternatives
Without root I turned down the backlight as far as possible and display a black overlay, so as much light is consumed as possible. 
Reduced backlight will reduce temperature and display wear. 
The overlay (all black) will absorb the light evenly / wear down the display evenly.

**Comment by thanksmister** [comment]
I am turning down the brightness of the screen and use a percentage of the current screen setting, you can also set the screen brightness over MQTT.   Though I don't have an all black screensaver, it shows the clock.  It might be a good idea to use a black screen saver along with setting the brightness level as low as possible automatically to prevent the screen, but a constantly running camera on some devices seems to be a battery killer.  I burned out a Nexus 6 and a Samsung Galaxy S5, both with swollen batteries.   Granted, they could have had older batteries, but two is not a coincidence to me.

**Comment by thomasnordquist** [comment]
I'm not sure how camera usage / increased computation would burn out a battery, especially if the USB cable should provide all the power needed.

I'll check if i can compare device temperature for both devices, first impression was that the current implementation with @jjoe64 runs twice the framerate + compares 300k pixels on a kindle fire 7. (Compared to 7fps and 64 pixels)

Not sure if the 640x480pixels are device/camera dependent.

### There may also be other factors at work:
- Temperature may be a factor, but the the device would need to run hot all the time.
- The most devastating thing for lithium batteries is to be charged all the time to 100%.
    [Don't keep it plugged in when it's fully charged](https://www.sciencealert.com/how-to-charge-phone-battery-to-last-longer-advice-science)
    Some devices have protection for those scenarios, especially if they are designed to run mostly on mains power, like notebooks.

**Comment by thanksmister** [comment]
I don't think its the heat, it's probably keeping it plugged in the all the time, but I wouldn't expect this issue with the Pixel 2.  I could have just had some really bad luck!  I do think your approach for motion detection is more efficient than @jjoe64.  Plus you seem to be thinking about how motion interacts with the environment, like lights on/off, people walking past the device instead of up to the device for interaction.

**Comment by thomasnordquist** [comment]
I built a prototype today, at first I liked the android vision framework, sadly they do not expose any compatible image formats. Native image scaling is not possible without a very serious performance impact. `Camera2` should fix this though, I believe it allows multiple preview callbacks and access to usable bitmap formats.

I ported the processing pipeline from JavaScript and used the "scaled" image stream as an input.
I believe I am at ~9% cpu usage (single core).

Still needs a lot of work, but seems to run smootly :P
https://github.com/thomasnordquist/wallpanel-android

Kotlin is quite a nice Language

**Comment by thanksmister** [comment]
The `MotionDetector` class you are working with is actually part of Google Vision, but it hooks into the Camera2 api to git an image to process for the motion detection.   Take a look at the `CameraReader` which uses the `MotionDetector` to process motion, much like the `FaceDetector` looks for faces.   I think there are also native image processing libraries (NDK) which process images much faster and in native C code.

**Comment by thanksmister** [comment]
Where is this package from de.t7n.android.motiondetection?  I am looking at your commits.

**Comment by thomasnordquist** [comment]
I currently sample about 3000 pixels in a grid and re-assemble them to a smaller picture before resizing them to 8x8.
(instead of transforming 300k pixels, which took ~500ms, with sampling ~12ms)
Using native a native resize would definitely remove some "strange" code.

The package is definitely there, at least now 😅

**Comment by thanksmister** [comment]
> (instead of transforming 300k pixels, which took ~500ms, with sampling ~12ms)
wow

**Comment by thanksmister** [comment]
I am using Google Vision API from Google Services, which runs locally to get images from the Camera2 API, its hard to find information, but here are some samples for their library: https://github.com/googlesamples/android-vision/tree/master/visionSamples.  This library allows me to do face detection locally on the device, but it uses detectors to plug into the vision library so you can build custom detectors, in my case, I built a motion detector library to process images from the video.

**Comment by thomasnordquist** [comment]
### Native scaling vs sampling

- Using native scaling ~4ms per frame can be achieved, but technically difficult. (Spent like 8h trying to make it work properly)
- With sampling ~11ms

### Average CPU usage

| Current implementation | New Implementation | 
|:--:|:--:|
| <img width="184" alt="Bildschirmfoto 2019-04-02 um 17 13 17" src="https://user-images.githubusercontent.com/7721625/55418736-8dcaf800-5573-11e9-9613-2beccd8c001a.png"> | <img width="184" alt="Bildschirmfoto 2019-04-02 um 17 13 09" src="https://user-images.githubusercontent.com/7721625/55418738-8f94bb80-5573-11e9-966a-14e9eb4d30b1.png"> | 

Next step would probably be to write a "debug overlay", so see how the detector behaves in real-time.
