### ISSUE TITLE
Mitigate image retention

### ISSUE THREAD

**Issue by thomasnordquist** [thanksmister/wallpanel-android#69]
When having a panel on for a very long time, image retention is bound to happen.
Commercial solutions (Kiosks) shift the content continuously to mitigate this.

Can also be seen in Smartwatches and Smartphones. (Phones shift the time, battery and signal quality icons. Smartwatches the whole watch face)

I'm a little bit more comfortable with web applications then android, I'd probably calculate how much the content needed zooming to have (let's say 16x16px) wiggle room, and then translate the whole content to a random location, 1px every minute. [Scale & Translate](https://www.w3schools.com/cssref/css3_pr_transform.asp)

Dead-simple but a very cool feature if the screen stays on.
Did this for a few dashboards which basically run 24/7

**Comment by thanksmister** [comment]
This is one reason why I added screensavers that rotate the image and/or information to prevent the screen burning.   But what you are suggesting would be a really cool implementation, so the panel can be on at all times.   If you come up with something in JS, I might be able to port it over to Java/Kotlin.
