### ISSUE TITLE
Enable/disable camera streaming via mQTT is not working

### ISSUE THREAD

**Issue by akasma74** [thanksmister/wallpanel-android#70]
**Describe the bug**
According to the docs, it's possible to enable/disable camera streaming.
However, it does not seem to react on appropriate MQTT messages.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable MJPEG streaming
2. Open camera url in browser
3. Issue
`mosquitto_pub -h 192.168.0.34 -u xxx -P xxx -t home/wallpanel/entrance/command -m '{"camera":false}'`
4. You'll still see a live stream in your browser

**Expected behavior**
Streaming should stop on camera:false.

**Smartphone (please complete the following information):**
 - OS: OS X 10.11.6
 - Browser Google Chrome
 - Version 73.0.3683.86

**Comment by thanksmister** [comment]
You didn't provide the version of the application you are using, you can check this under the settings and the about section.  Do you have your camera on in the settings?

**Comment by akasma74** [comment]
Sorry, it's v0.8.6-beta.1
Yes, I turned the camera on and can see live stream in browser even after issuing that mqtt command.

Hoped to get the video feed in my HA frontend but soon realised it's not possible yet as it is not generic ip camera.

**Comment by thanksmister** [comment]
Doesn't HA have a generic IP camera component, I know I can use IP Webcam and stream it to HA.  You can also add the live stream to your HA from this application.   I will investigate the camera on/off feature.   But essentially it just shuts off the streaming server in the application, the camera is still active.

**Comment by akasma74** [comment]
> Doesn't HA have a generic IP camera component

It does indeed and the streaming capability is limited by that very component only so far.
I'm not sure that I can define this application's camera as generic ip camera, they have different parameters..

**Comment by thanksmister** [comment]
The camera is a MJPEG camera stream, you can add it to the front end as a generic camera using the Generic MJPEG component https://www.home-assistant.io/components/camera.mjpeg/.
