### ISSUE TITLE
Review of sensor/motion behaviour

### ISSUE THREAD

**Issue by akasma74** [thanksmister/wallpanel-android#71]
**Is your feature request related to a problem? Please describe.**
The app has an option to enable motion detection that I personally use so the app can wakes my tablet up if motion detected as they are linked.
I also enable MQTT because I want to get the app's status (online/offline).
That AUTOMATICALLY means I receive data from ALL available sensors as there is no option to opt out from any particular one etc.
It's not an issue, but I think that motion sensor implementation is not quite correct.
Currently when motion detected, it publishes something like

> 09:47:20: (0) home/wallpanel/entrance/sensor/motion {"value":true}

and then after Motion Reset Time seconds (5 seconds in my case)

> 09:47:25: (0) home/wallpanel/entrance/sensor/motion {"value":false}

**Describe the solution you'd like**
I think it can act as a standard PIR, for example: when motion detected, it sends a signal and does not send any more signals within a set period of time (typically 3 minutes for battery-powered devices to save energy).
I don't think sending that second mqtt message makes sense and it's better to send only {"value":true} messages and don't publish anything (even if motion detected) within the next Motion Reset Time seconds.
That way it won't be controversial (as having pair {"value":true} and {"value":false} might be interpreted as "there was motion between this and that time") and will help to ease mqtt traffic.
Hope it makes sense.

**Comment by thanksmister** [comment]
You can ignore the second value if you wish, I use the second value for my automations and so do others.  Rather than remove it for everyone, just ignore the value if its false.

**Comment by akasma74** [comment]
Well, at least it creates unnecessary load on MQTT broker.
And as I mentioned, the only meaningful event is the {"value":true}.
Automations can be changed to reflect the nature of this event - in HA it's just adding "delay_off:".

But it's up to you really.

**Comment by allofmex** [comment]
@akasma74 
Other motion sensors send motion:false too (example zigbee hue motion sensor). How else should it let you know if there is **still/continuous** motion or not!?

**Comment by akasma74** [comment]
@allofmex I don't own any motion sensors that send motion:false but I do believe you ;)

The thing is I use my sensors to trigger a security alarm. Therefore I don't need to know if there's still/continuous motion - as soon as I get a motion detected message, it's time to raise the alarm and anything extra just doesn't make sense.

Maybe there are circumstances when people use their motion sensors differently, but I'm not aware of that.
