### ISSUE TITLE
Show Android Soft Buttons

### ISSUE THREAD

**Issue by etchings13** [thanksmister/wallpanel-android#73]
The current version of this app is in full screen mode which forces an extra swipe to activate the phone's dock (home/back buttons). It would be great if this was visible so you can open the app, do what needs to be done, then quickly exit with the phone's home button.

**Comment by etchings13** [comment]
The current version of this app is in full screen mode which forces an extra swipe to activate the phone's dock (home/back buttons). It would be great if this was visible so you can open the app, do what needs to be done, then quickly exit with the phone's home button.

**Comment by etchings13** [comment]
<img src="https://user-images.githubusercontent.com/1736287/55367648-ad9ae700-54b3-11e9-800e-367bdda62a1c.png" width="40%" height="40%"> <img src="https://user-images.githubusercontent.com/1736287/55367652-affd4100-54b3-11e9-95be-fefc3da20e78.png" width="40%" height="40%">

**Comment by Tofandel** [comment]
The app is kinda made as the name suggest to be just always open on a tablet, it's normal to have fullscreen mode
