### ISSUE TITLE
MQTT bug with Paho library v1.2.0

### ISSUE THREAD

**Issue by thanksmister** [thanksmister/wallpanel-android#74]
**Describe the bug**
Seems to be a disconnect issue with the Paho library.

**To Reproduce**
Launch app
1 Allow app to connect via MQTT and load web page
2 Click back to access settings page.
3 Click Dashboard to return to web page.
4 "Error connecting to MQTT..."

**Expected behavior**
MQTT connection either maintained while settings screen open or cleanly disconnected then reconnected.

**Possible Issue Cause**
from @allofmex 

I assume this error is because of https://github.com/eclipse/paho.mqtt.java/issues/634
Had the same problem too. It seems to be fixed in paho.mqtt in meantime. Guess it requires a library update for wallpanel..

Another solution may be to change
https://github.com/thanksmister/wallpanel-android/blob/cbde6445e6e0751bdd42e1641cafd3f87156bf45/WallPanelApp/src/main/java/com/thanksmister/iot/wallpanel/network/MQTTService.kt#L167

to 
`
mqttClient = MqttAndroidClient(context, mqttOptions?.brokerUrl, mqttOptions!!.getClientId(), MemoryPersistence())`

Works for my devices, but I don't really know if current FilePersistence is needed for some wallpanel functions.

**Comment by thanksmister** [comment]
> Works for my devices, but I don't really know if current FilePersistence is needed for some wallpanel functions.

@allofmex I am not using the `FilePersistence` so it should be fine to try your solution.  I will test this out as soon as I can.

**Comment by allofmex** [comment]
> I am not using the FilePersistence

As far as I understand is FilePersistence the default (no Persistence provided in MqttAndroidClient constructor)

I don't expect sideeffects by MemoryPersistence too.

It also solved another "no storage location found" crash on one of my devices (Sony Xperia Ray, Android 4.4.2)

**Comment by thanksmister** [comment]
I am testing the change now, no initial issues discovered.
