### ISSUE TITLE
Blue bar on screen

### ISSUE THREAD

**Issue by Jigglefrizz** [thanksmister/wallpanel-android#75]
**Describe the bug**
Main page (homeassistant, lovelace) shows only a blue bar on android tablet. Does not get to the login page.
Does work in chrome.

**To Reproduce**
Duck dns page on android 4.4

**Expected behavior**
Log in page.

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thanksmister** [comment]
Do you know which device you have, the version of Android its running?

**Comment by thanksmister** [comment]
I can see from your Google review that you are running Android 4.4.  Older devices have a really outdated version of the WebView component, which renders web pages inside of Android applications. This is not the same as the Chrome OS application you use on your phone.  

They will not render the same pages the same.  The CSS/HTML you are using on your home automation platform page is incompatible with the version of the WebView component used on your device, it can not render the page properly. 

You can try updating your WebView component from Google Play, use different CSS/HTML for your web page, or you can try the legacy version of the application available here https://github.com/thanksmister/wallpanel-android-legacy.  Other than that, there is nothing I can do to make your old device render more modern web pages with an Android application.

**Comment by bramkragten** [comment]
You could look into [crosswalk](https://crosswalk-project.org/blog/crosswalk-final-release.html) maybe? Not developed anymore but might work for older devices?

**Comment by thanksmister** [comment]
@bramkragten  The legacy version already uses crosswalk, take a look at the project https://github.com/thanksmister/wallpanel-android-legacy.   It's no longer supported on newer versions of Android Studio and new Android code repositories.   This is why I cut a legacy branch and moved on without including crosswalk in the current project, its not longer viable to work with if I want to continue to use the latest Android development tools.

**Comment by bramkragten** [comment]
Ohw cool sorry, didn't check the link :-)
