### ISSUE TITLE
Make brightness values configurable

### ISSUE THREAD

**Issue by djchen** [thanksmister/wallpanel-android#76]
**Is your feature request related to a problem? Please describe.**
The Configuration.PREF_BRIGHTNESS_FACTOR isn't adjustable.

**Describe the solution you'd like**
Make this value adjustable via settings and perhaps allow both a % and an absolute value.

**Additional context**
I think it would also be useful to have the app adjust the brightness of the screen when it's on, based on the light sensor value.

**Comment by thanksmister** [comment]
Not many devices have the light sensor, so this would not be a good option.   It would be better to have day/night mode adjustments that change the brightness.   I am setting them manually now as % of the device brightness out of convenience when using the built in screen saver.  You have the option on some devices (all but Amazon) to use the Android Daydream feature which adjusts the brightness automatically, just don't use manual brightness controls or the built-in screensaver.   The screen saver was built for devices that do not have Daydream (like Amazon tablets) and need a way to both adjust the brightness and offer a screensaver feature.

**Comment by djchen** [comment]
> It would be better to have day/night mode adjustments that change the brightness. I am setting them manually now as % of the device brightness out of convenience when using the built in screen saver. 

That is a good idea!

I also mean to be able to adjust the brightness during the screensaver. It seems like right now that is hard coded to 10% of the pre-screensaver brightness?

**Comment by thanksmister** [comment]
Yeah, its a percentage of the screen brightness value and its hard coded to 10%.  In the future we will make this customizable.
