### ISSUE TITLE
Waking the screen

### ISSUE THREAD

**Issue by ACJUK** [thanksmister/wallpanel-android#78]
Hi

I have a Raspberry Pi running as a security camera over the front door.  The motion detection allows me to do an http request when motion is detected.

Is there a way that I could do an http request to wake the screen on a Kindle Fire?

**Comment by thanksmister** [comment]
There are http commands you could use, check the documentation https://github.com/thanksmister/wallpanel-android/blob/master/README.md#commands

**Comment by ACJUK** [comment]
Perfect.  I did look at that but this is all a bit new to me.  I installed Postman and tested it - worked fine.  Just got to chuck it in a Python script on the Pi and I reckon it'll be job done.

You really should allow donations for this.  I feel bad using it and asking for help when I can't contribute technically.
