### ISSUE TITLE
Add option to use GeckoView instead of WebView

### ISSUE THREAD

**Issue by thanksmister** [thanksmister/wallpanel-android#80]
Let's add an option to use [GeckoView](https://wiki.mozilla.org/Mobile/) for rendering the web pages.

**Comment by sobachatina** [comment]
I'm using old tablets with Android 4.4.2 and can't upgrade chrome. Firefox works well.
I would love to be able to use wallpanel.

**Comment by thanksmister** [comment]
There is a legacy version of WallPanel that supports Android 4.*, look for it from the list of repositories.

**Comment by nagyrobi** [comment]
+1 for this. Google's WebView is still limited and resource intensive. For example on my MT8127-based tablet, running Android 5.0.1, and on another Cortex-A7-based device running Android 7.1.2, although Webview is up-to date, Home Assistant's Lovelace is very laggy. Switches move slowly etc. I was about tho throw these devices in the trash.

The legacy version of WallPanel runs much better using Crosswalk on these devices. But Crosswalk development seems to stale, while Firefox/GeckoView keeps up. I really suggest to make recent releases using GeckoView too.

This helps us protecting the environment. We can still use the good old hardware.

**Comment by thanksmister** [comment]
@sobachatina the application does not depend on which browser your device has installed, it depends on which version of the Android OS have and which version of the Android WebView component.  WebView uses a subset of Google Chrome OS to render web pages within an Android application.  

So switching to GeckoView also poses its own issues and support problems.  I decided not to switch to GeckoView but instead migrate the entire project to Flutter, making it cross platform.  This will not solve your issue with rendering though, so use @nagyrobi suggestion.  

The legacy version is the best for older devices, use the legacy version but keep in mind that Crosswalk is no longer supported so this version of the application is no longer supported.
