### ISSUE TITLE
SSL Certificate Error

### ISSUE THREAD

**Issue by hoangtridung** [thanksmister/wallpanel-android#83]
A msg popup more time:
" SSL Certificate Error
The certificate authority is not trusted. Do you want to continue anyway"

**Comment by thanksmister** [comment]
It means you are loading a site with a self signed certificate, it’s up to you to trust the cite you are loading.

**Comment by hoangtridung** [comment]
I using HA site with DuckDNS and LetsEncrypt certificate. How to bypass that msg ?
