### ISSUE TITLE
Add Alarmpanel functionality - or ability to switch to AlarmPanel via MQTT?

### ISSUE THREAD

**Issue by BoneheadFraggle** [thanksmister/wallpanel-android#84]
**Is your feature request related to a problem? Please describe.**
I use WallPanel and AlarmPanel on three cell phones in my house and garage, but I'd really like to be able to use the same phone for both purposes.

**Describe the solution you'd like**
I'd like AlarmPanel and WallPanel to be or at least feel integrated. They already share many features, The only thing I miss in WallPanel is the ability to use it as keypad for the alarm. 

Scenarios:
1. Manually swipe to start/show AlarmPanel, but within the same app, not by entering the OS and start AlarmPanel also. It's possible, but not the integrated user experience I'd like. 
2. If the alarm state changes, then show AlarmPanel for 10-30s
3. If the alarm is armed away, always show AlarmPanel.

**Describe alternatives you've considered**
I could use the alarm lovelace card, but that doesn't provide the same "real app" response and experience.
If you don't like the idea to combine the apps, would it be possible to install them both, and let MQTT control which one shows on the phone? Then I could gain most of the desired functionaly by MQTT-commands from HA, using the WallPanel motion sensor, alarm state and so on.

**Additional context**
[I previously suggested to add some WallPanel features into AlarmPanel](https://github.com/thanksmister/android-mqtt-alarm-panel/issues/84) but after using WallPanel for a couple of months, I think it would be even better to add a little AlarmPanel to it instead.

I hope you see the possibilities I do, but anyhow - many thanks for all your work with AlarmPanel and WallPanel. They both work really well - I just think they would be even more awesome combined

**Comment by thanksmister** [comment]
That's a lot of work, but thanks for the suggestion.
