### ISSUE TITLE
Screensaver - Screen not dimming.

### ISSUE THREAD

**Issue by MarkHofmann11** [thanksmister/wallpanel-android#87]
Tried all the different percentages 10%-90% screen dimming.  When the clock screensaver starts, it continues to be at the original 100% brightness.  

When I first ran Wallpanel, I saved the screen brightness setting in the app (which was at 100%).  Have been unable to get the screen to dim, which might be causing my tablet to drain to 0% while on the charger.

**Comment by thanksmister** [comment]
It doesn't sound as though your device has permission to adjust the screen brightness manually.  

There is a manual button to set the screen brightness now.  So if you have brightness permission on, you go to settings, adjust your screen brightness to the desired setting, then press the capture button.    

I have tested the latest release and it seems to be working as designed.

**Comment by thanksmister** [comment]
![screen](https://user-images.githubusercontent.com/142340/57989286-f7915980-7a6e-11e9-916b-abe8fc8b5341.png)
![screensaver](https://user-images.githubusercontent.com/142340/57989287-f829f000-7a6e-11e9-9190-3ef39180b1d1.png)

A good way to check if the screen has dimmed is to slide down the notification tray and check the screen dim value.  One is 255 for 100%, the other is 26 for the screen saver, or 90% of 255.

**Comment by MarkHofmann11** [comment]
That makes sense.  I thought when you "Capture screen brightness", that was what you wanted it to be when normally on (not when the screen saver was on).  I kept setting the brightness to 100% and then captured it.  I thought the 50% setting would then take 50% less brightness from my 100% setting.  

So I need to check capturing brightness at 25% or something, then manually change it back to 100%.  Then the screensaver should go to 25%.  

Will give that a try later today.  Thanks!

**Comment by thanksmister** [comment]
No, you capture the current brightness setting of the device.  The screensaver is a percentage of that setting.  So if you want your default brightness to be 100%, you capture it at 100%.  The screensaver will be a percentage of this amount.   What I showed with the pictures was that its actually working.  The first photo is 100% brightness, the second one is 90% brightness when the screensaver was on.   I was asking how are you determining that the screensaver dimming isn't working?

**Comment by thanksmister** [comment]
If the issues persists, perhaps it's an issue with some setting not getting updated.   I looked for crash reports, but didn't find anything specifically related to the application.   I would recommend maybe uninstalling the app then installing it again to see if the issue persists.   Until we find out more about this or have other reports, its the best I can recommend at the moment.

**Comment by MarkHofmann11** [comment]
I have been running build #3 which other than an occasional "screen not reverting to full brightness after screensaver enabled".  Problem is when that happens, the only way to fix it is to uninstall to clear all settings and re-install.

I updated from build #3 to the latest version via Google apps store.  I can try uninstalling #3 first, then installing the latest from scratch and see if anything is different.

The only issue I have seen with the latest is I have been unable to get the screen to dim when the screensaver is on, no matter what percentage I use.  I tried everything from 90% to 10%, no difference in screen brightness.  I also can't find an option on my Android version to grant screen brightness control to an app, but it works in build #3.  Had to revert to #3 because my battery was draining out even with it plugged in.

I'll do more testing later today.

**Comment by thanksmister** [comment]
The brightness permissions are under the Settings > Apps > Advanced > Special app access.  Then look for Modify system settings.   WallPanel  should be listed there and allowed.   It's different on each device,  this is for a Pixel phone running Android 9.

**Comment by MarkHofmann11** [comment]
I can get to the app permissions, but there is no selection to "modify".  I'm using a Samsung Galaxy Tab A 7" to HADashboard.  On my phone (Samsung Note 9), I can modify the settings.

**Comment by thanksmister** [comment]
Its a device permissions, not app specific.  So usually you go into settings, select Apps & Permissions then there is an option for advanced or default permissions, sometimes there is a settings icon in the menu that looks like a gear or drop down menu item.  These are permissions to control your device.  Its specific to the OS you are running.    If you uninstall the app and reinstall it, it will ask for this permission the first time you select Screen Brightness in the settings.  You will see it takes you to a special permission screen.

**Comment by alvinngct** [comment]
do you know where is the setting for kindle fire? mine can dim and cant seems to find the option

**Comment by joejdavis** [comment]
Having the same problem with Amazon Fire Tablet. In the permissions section it has modify system settings but I can't get the screen to dim through the screensaver or MQTT commands.
