### ISSUE TITLE
API returns 'false' for Fire 7 tablet

### ISSUE THREAD

**Issue by BongoEADGC6** [thanksmister/wallpanel-android#88]
Unable to run API commands. Status works fine but commands do not work.

**To Reproduce**
1. Run command
` curl -XPOST 172.20.1.120:2971/api/command -d '{"reload": true}'
{"result":false}`

**Expected behavior**
Expected page to reload

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: 2017 Fire 7 Tablet
 - OS: Lineage OS
 - Browser: stock browser

**Additional context**

**Comment by thanksmister** [comment]
I tried the post with Postman and it worked fine, I think it's your curl command.
