### ISSUE TITLE
Face Detection on Amazon Fire 7 not working

### ISSUE THREAD

**Issue by bluesheep** [thanksmister/wallpanel-android#9]
I can't seem to get Face or QR detection working on the Amazon Fire 7 tablet. Motion detection is working fine. I have it configured to use the forward camera, landscape orientation.

I've tried rotating the tablet in case orientation made any difference but no luck.

**Comment by thanksmister** [comment]
Have you used the camera test for testing face detection and QR code reading? If so what was the result of you tested each individually?

**Comment by bluesheep** [comment]
I'm got an Amazon Fire 7 (7th Gen) running FireOS 5.6.1.0
I updated the app from the Play store, its on v0.8.3 Build 2

I've also tested using the back camera with no luck either. Having skimmed the code I can't see any reason why the motion detector would work but not the facedetector.

**Comment by thanksmister** [comment]
I don't have a fire tablet to test on but I do have v0.8.3 Build 2 running on a Lollipop devices without any issues.  Maybe you can try lowering your FPS for the camera and see if that helps.  That is in the camera settings and is 15 FSP by default.

**Comment by bluesheep** [comment]
I've just tried lowering the framerate, it didn't make a difference. One thing I did note is that the framerate doesn't appear to change on the test camera. I dropped it down to 1FPS.

**Comment by thanksmister** [comment]
I don't think the test camera is setup to use a reduced FPS, I will have to look.   Have you tried outputting Face Detection over MQTT to see if its outputting.  I know in the test application it has a toast popup that appears, but I am wondering if this toast is just not visible.    You might also test using Face Detection with the option of turning on the screen if a face is detected to see if that works.  I assume you already did this part.   

At this point I have no other suggestions to offer.  Motion works, but its using the same Google Vision API for face detection and QR code reading.   So theoretically if one should work, so should the others.  There is nothing I can change to help, it could be the custom rom on the FireTablet lacks the latest Google Services which might have an issue with Lollipop that was fixed in a newer version of Google Services.

**Comment by thanksmister** [comment]
You are not receiving any MQTT at all, not even sensors or motion detected?  You mentioned motion detection was working.    Maybe you didn't yet setup your MQTT to talk with HASS?

I already have logs for crashes and errors within the application and I have not received any errors with your particular device.   It's an odd behavior, as I said, I use the same library to detect motion as I do with face recognition and QR code reading.   

You could try the previous version of this application, it may work for you https://github.com/WallPanel-Project/wallpanel-android.   I will work on adding some more logging information for the camera test but not sure when I will have a new version available.

**Comment by thanksmister** [comment]
I will investigate the FPS option to see if this is updating properly.  On some older devices the camera speed needs to be lower to work properly.

**Comment by thanksmister** [comment]
You may want to give the latest version a try, there was an issue with Face Detection on some Android devices and it seems to be working now in the latest release.  The FPS are being set on the video, its up to the video player to increase FPS if possible, so setting it to a value of 1 won't slow down the image you see within the app, just streaming.

**Comment by thanksmister** [comment]
I am closing this issue since there doesn't seem to be any response.

**Comment by mariusbalcytis** [comment]
Sorry for commenting on the closed issue. Just wanted to clarify related situation. I've got 7th gen Fire 10 and when face detection is turned on, notification appears "Missing appropriate libraries..."
Can this be fixed somehow? Or is this completely OS related?

**Comment by thanksmister** [comment]
That means you are missing the Google play services which is too bad.  I use the libraries for face detection from Google play on the device, not cloud.

**Comment by Tofandel** [comment]
I have the same message on a brand new teclast tablet on Android 9, but Google play services are enabled.. Any idea?

**Comment by maxkueng** [comment]
I have the same issue on a Lenovo Tab M8 running Android 9 and I get the same message saying that the appropriate libraries are missing. You say that this is because Google Play Services are missing. I do have Google Play Services version 20.6.16 (100400-296104215) installed. However, when I look it up on Google Play Store I only get a button to deactivate it, nit update it.

So my tablet is running the Android version from Lenovo (with preinstalled apps, etc.). Do you think I could get a better version Google Play Service if I flashed a different ROM on to it?

This is a really awesome app, BTW! Thanks, Mister!

**Comment by EddyYama** [comment]
I'm using Fire HD 10 (7th gen). The Google play services are enabled.
When face detection is turned on, notification says "Missing appropriate libraries...". 
No luck.

**Comment by rahaaas** [comment]
Same here...

**Comment by Tofandel** [comment]
You might want to `Restart` your device, the problem was gone for me after a reboot

**Comment by VaguerOdin** [comment]
Same here... Fire HD 10 (11th). Google Play services enabled and working. All latest updates. Reeboot has no luck. Missing appropriate libraries..
Thanks for tour work

**Comment by Hukuma1** [comment]
+1 for the above. Used Fire Toolbox v20 and got everything cleaned out + installed Google Play services and installed Wallpanel from the Play Store. Fire HD 10 11th gen.

Do we need the stock Camera app from Amazon for it to function properly? (that gets deleted during debloat)

Do we need to have the Wallpanel app be the default launcher for this to work? (it's not, I use Nova)

Would love to debug this further or if needed will open new issue. Thanks!

**Comment by MiBe17** [comment]
Another +1 for this issue. I have a Fire HD 10 (9th gen) debloated and experience the exact same problem. This issue seems not to be solved, so could it be reopened please?

**Comment by n3roGit** [comment]
I have the same issue with newest fire hd 10 tablet

**Comment by Zerwin** [comment]
Just tested with a factory reset Fire 10 Tablet and also after installing Google Play Services via Fire Toolbox, both times it complained about missing libraries.

**Comment by Hukuma1** [comment]
Looks like this project has been taken over by a new maintainer.

Shall we open a new issue, or can this one be re-opened/investigated, @thecowan?

**Comment by smitterson** [comment]
According to [this](https://developers.google.com/android/reference/com/google/android/gms/vision/face/FaceDetector) the FaceDetector is deprecated and should be replaced with the ML Kit version. Perhaps the version of Google Play Services installed by the Fire Toolbox is lacking the older FaceDetector used by the Wallpanel app?

**Comment by Hukuma1** [comment]
Nice find!

Does it go the other way too? Would Wallpanel app be able to add support for ML Kit version?

**Comment by Zerwin** [comment]
Took a look with my limited understanding of Android apps, seems like the entire camera setup would have to be rewritten to use ML Kit. Definitely something out of my reach of capabilities.

I might try to find a version of the Google Play Services that still support the old API's, maybe that will work out.

On another note, is this project still active ? The last commit has been in October last year.
