### ISSUE TITLE
How to enter settings menu

### ISSUE THREAD

**Issue by Derkades** [thanksmister/wallpanel-android#90]
I feel like an idiot but I can't figure out how to go to the settings menu. The app is showing the github page without any buttons or a hamburger menu to go to settings

**Comment by thanksmister** [comment]
It’s a full screen app like Netflix, just swipe up or down on the screen to see your device navigation menu.

**Comment by Derkades** [comment]
Yes, that'll bring up my system status bar. I want to access the settings menu of this app, how do I do that?

**Comment by thanksmister** [comment]
Hit the back button, that’s what I was referring to.  Bring up the navigation and hit back which takes you to the settings.

**Comment by Derkades** [comment]
Oh, it's as simple as hitting the back button. Thanks!
