### ISSUE TITLE
HA page does not render (JS issue?)

### ISSUE THREAD

**Issue by guandalf** [thanksmister/wallpanel-android#98]
**Describe the bug**
Home Assistant loads only the HTML, but no redirect to login is performed. 

**To Reproduce**
1. Enter HA url (IP address)
2. Go to DASHBOARD

**Expected behavior**
Redirect to login and show home assistant page

**Smartphone (please complete the following information):**
 - Device: 791 (cheap chinese 7 inch tablet)
 - OS: Android 5.1.1
 - Browser stock
 - Version 75 (Android System Webview)

**Additional context**
Works on chrome. Does not work on stock browser. I disabled "internal" Android System Webview and updated it from play store

**Comment by Yonguelle** [comment]
I have axact same issue on tablet Lenovo yoga 8 B6000. Android 4.2.2.
On wallpanel and stock browser i can only see background off hassio. No login page.
On other browsers works fine. 

Is it possible to wallpanel use different than stock browser?

**Comment by stbkde** [comment]
Same issue on Samsung Galaxy Tab 2 10.1 with Android 4.2.2. 
The UI only works with the Opera browser. Chrome shows the same like Wallpanel: Only a blue bar and then nothing's happens.

**Comment by thanksmister** [comment]
Some older devices like Lenovo and those running older operating systems cannot display every webpage and it has nothing to do with which browser you have installed.  Android applications use their own internal rendering engine for the WebView component.  Unfortunately, this isn't consistent across all devices and support for html pages isn't the same on older Android OS.   You can try the legacy WallPanel application, and if that doesn't work, you need to simplify your webpage.  Outside of that, it is entirely out of my hands and I cannot fix your redner issues.

https://github.com/thanksmister/wallpanel-android-legacy
